;;; 110-init-elpaca.el --- TODO: add commentary -*- lexical-binding: t; -*-
;;
;; Copyright (c) 2024 Free Software Foundation, Inc.
;;
;; Author: Luis Henriquez-Perez <luis@luishp.xyz>
;; Homepage: https://github.com/Luis-Henriquez-Perez/dotfiles/
;;
;; This file is not part of GNU Emacs.
;;
;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License as
;; published by the Free Software Foundation, either version 3 of the
;; License, or (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful, but
;; WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
;; General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program. If not, see <http://www.gnu.org/licenses/>.
;;
;;; Commentary:
;;
;; TODO: add commentary
;;
;;; Code:
;;; bootstrap
(defvar elpaca-core-date '(20231211))
(defvar elpaca-installer-version 0.11)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil :depth 1 :inherit ignore
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (<= emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let* ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                  ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                  ,@(when-let* ((depth (plist-get order :depth)))
                                                      (list (format "--depth=%d" depth) "--no-single-branch"))
                                                  ,(plist-get order :repo) ,repo))))
                  ((zerop (call-process "git" nil buffer t "checkout"
                                        (or (plist-get order :ref) "--"))))
                  (emacs (concat invocation-directory invocation-name))
                  ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                        "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                  ((require 'elpaca))
                  ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (let ((load-source-file-function nil)) (load "./elpaca-autoloads"))))
(elpaca `(,@elpaca-order))
;;; do not process too many orders at once
;; Doing so causes me performance problems.
(setq elpaca-queue-limit 10)
;; Wait longer.
(setq elpaca-wait-interval 0.2)
;;; recipes
(elpaca jit-spell)
(elpaca ace-jump-helm-line)
(elpaca ace-link)
(elpaca ace-window)
(elpaca aggressive-indent)
(elpaca all-the-icons)
(elpaca all-the-icons-nerd-fonts)
(elpaca beacon)
(elpaca buffer-terminator)
(elpaca burly)
(elpaca cape)
(elpaca caps-lock)
(elpaca captain)
(elpaca consult)
(elpaca corfu)
(elpaca ctable)
(elpaca cyberpunk-theme)
(elpaca dash)
(elpaca dashboard)
(elpaca denote)
(elpaca dimmer)
(elpaca dirvish)
(elpaca doct)
(elpaca doom-themes)
(elpaca easy-escape)
(elpaca eat)
(elpaca edit-indirect)
(elpaca elfeed)
(elpaca elmacro)
(elpaca embark)
(elpaca embark-consult)
(elpaca emmet-mode)
(elpaca emms)
(elpaca eros)
(elpaca (escr :repo "Luis-Henriquez-Perez/escr" :branch "master" :host github))
(elpaca eshell-prompt-extras)
(elpaca eshell-syntax-highlighting)
(elpaca eshell-up)
(elpaca eshell-z)
(elpaca esup)
(elpaca evenok)
(elpaca evil)
(elpaca evil-cleverparens)
(elpaca evil-collection)
(elpaca (evil-easymotion :fetcher github :repo "Luis-Henriquez-Perez/evil-easymotion"))
(elpaca evil-exchange)
(elpaca evil-fringe-mark)
(elpaca evil-goggles)
(elpaca evil-iedit-state)
(elpaca evil-lisp-state)
(elpaca evil-nerd-commenter)
(elpaca evil-surround)
(elpaca evil-textobj-column)
(elpaca evil-textobj-entire)
(elpaca evil-textobj-line)
(elpaca evil-textobj-syntax)
(elpaca evil-visual-mark-mode)
(elpaca expreg)
(elpaca exwm)
(elpaca fancy-narrow)
(elpaca fennel-mode)
(elpaca filladapt)
(elpaca fit-text-scale)
(elpaca git-gutter)
(elpaca goto-chg)
(elpaca green-screen-theme)
(elpaca grugru)
(elpaca helm)
(elpaca helm-system-packages)
(elpaca helpful)
(elpaca hide-mode-line)
(elpaca highlight-indent-guides)
(elpaca highlight-quoted)
(elpaca htmlize)
(elpaca humanoid-themes)
(elpaca hungry-delete)
(elpaca hy-mode)
(elpaca leuven-theme)
(elpaca lispy)
(elpaca lispyville)
(elpaca lorem-ipsum)
(elpaca lua-mode)
(elpaca macrostep)
(elpaca marginalia)
(elpaca markdown-mode)
(elpaca minimal-theme)
(elpaca modus-themes)
(elpaca monkeytype)
(elpaca nerd-icons)
(elpaca nerd-icons-completion)
(elpaca no-littering)
(elpaca noccur)
(elpaca notmuch)
(elpaca orderless)
(elpaca org-appear)
(elpaca org-bookmark-heading)
(elpaca org-fancy-priorities)
(elpaca org-ml)
(elpaca org-pretty-tags)
(elpaca org-superstar)
(elpaca org-tidy)
(elpaca (outli :fetcher github :repo "jdtsmith/outli"))
(elpaca password-store)
(elpaca pcre2el)
(elpaca php-mode)
(elpaca powerline)
(elpaca rainbow-delimiters)
(elpaca rainbow-mode)
(elpaca redacted)
(elpaca restart-emacs)
(elpaca sdcv)
(elpaca sly)
(elpaca smartparens)
(elpaca ssh-agency)
(elpaca standard-themes)
(elpaca stripe-buffer)
(elpaca sudo-edit)
(elpaca super-save)
(elpaca tango-plus-theme)
(elpaca telephone-line)
(elpaca tempel)
(elpaca tempel-collection)
(elpaca textsize)
(elpaca transpose-frame)
(elpaca transwin)
(elpaca ts)
(elpaca vc-auto-commit)
(elpaca vertico)
(elpaca w3m)
(elpaca web-mode)
(elpaca wgrep)
(elpaca which-key)
(elpaca ws-butler)
(elpaca xr)
(elpaca yeetube)
(elpaca zoutline)
(elpaca (zone-matrix :host github :repo "ober/zone-matrix" :branch "master" :ref "d6c627e"))
;;; provide
(provide '110-init-elpaca)
;;; 110-init-elpaca.el ends here
