;;; 910-text-abbrevs.el --- TODO: add commentary -*- lexical-binding: t; -*-
;;
;; Copyright (c) 2024 Free Software Foundation, Inc.
;;
;; Author: Luis Henriquez-Perez <luis@luishp.xyz>
;; Homepage: https://github.com/Luis-Henriquez-Perez/dotfiles/
;;
;; This file is not part of GNU Emacs.
;;
;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License as
;; published by the Free Software Foundation, either version 3 of the
;; License, or (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful, but
;; WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
;; General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program. If not, see <http://www.gnu.org/licenses/>.
;;
;;; Commentary:
;;
;; TODO: add commentary
;;
;;; Code:
(require 'abbrev)

(define-abbrev-table 'text-mode-abbrev-table
  '(("emal" "email")
    ("stil" "still")
    ("customizaton" "customization")
    ("comiled" "compiled")
    ("imngtha" "I am going to have a")
    ("progrmatically" "programatically")
    ("frtm" "furthermore")
    ("tdwiw" "to do what I want")
    ("muisc" "music")
    ("musc" "music")
    ("picures" "pictures")
    ("picure" "picture")
    ("pics" "pictures")
    ("foms" "forms")
    ("til" "until")
    ("craclking" "crackling")
    ("horu" "hour")
    ("kep" "keep")
    ("iimet" "it is much easier to")
    ("hled" "highlighted")
    ("tras" "trash")
    ("scrapt" "scraped")
    ("sko" "some kind of")
    ("lm" "let me")
    ("imc" "in many cases")
    ("woht" "without having to")
    ("redef" "re-define")
    ("redefing" "re-defining")
    ("invis" "invisible")
    ("resly" "respectively")
    ("avod" "avoid")
    ("agneda" "agenda")
    ("ater" "after")
    ("unl" "unless")
    ("lop" "loop")
    ("vanila" "vanilla")
    ("vannilla" "vanilla")
    ("cimpiled" "compiled")
    ("cont" "cannot")
    ("kbinding" "keybinding")
    ("idnkt" "I did not know that")
    ("b" "be")
    ("rm" "remove")
    ("otherw" "otherwise")
    ("symb" "symbol")
    ("atl" "at least")
    ("normuch" "notmuch")
    ("smome" "some")
    ("snaphsot" "snapshot")
    ("comiled" "compiled")
    ("trwi" "the reason why I")
    ("harddrive" "hardrive")
    ("mself" "my self")
    ("doit" "do it")
    ("eare" "are")
    ("awes" "awesome")
    ("fav" "favorite")
    ("metod" "method")
    ("wpps" "wallpapers")
    ("wpp" "wallpaper")
    ("walpaper" "wallpaper")
    ("walpapers" "wallpapers")
    ("sfw" "SFW")
    ("nsfw" "NSFW")
    ("triend" "tried")
    ("havnet" "have not")
    ("dled" "downloaded")
    ("wallpaer" "wallpaper")
    ("wallpaers" "wallpapers")
    ("wek" "week")
    ("wk" "week")
    ("ai" "AI")
    ("itint" "I think I need to")
    ("sysd" "systemd")
    ("kebd" "keybinding")
    ("webscrpa" "webscrape")
    ("fringnes" "fringes")
    ("wms" "window managers")
    ("wm" "window manager")
    ("dki" "I do not know if")
    ("websti" "website")
    ("thest" "test")
    ("idkwi" "I do not know I")
    ("dkwi" "I do not know I")
    ("exe" "executable")
    ("exable" "executable")
    ("aproxl" "approximately")
    ("aprox" "approximate")
    ("instaled" "installed")
    ("oses" "OSes")
    ("wroth" "worth")
    ("adament" "adamant")
    ("foh" "figure out how")
    ("taw" "that would")
    ("m" "my")
    ("f" "for")
    ("doc" "documentation")
    ("fmc" "for my case")
    ("profle" "profile")
    ("iia" "if I am")
    ("vodi" "void")
    ("r" "are")
    ("w" "with")
    ("deping" "depending")
    ("hvnt" "have not")
    ("ihvnt" "I have not")
    ("amap" "as much as possible")
    ("thtb" "that had to be")
    ("wpap" "wallpaper")
    ("wpapa" "wallpaper")
    ("mnt" "mount")
    ("mnted" "mounted")
    ("rel" "relative")
    ("hdd" "harddrive")
    ("rom" "from")
    ("targ" "target")
    ("disale" "disable")
    ("dis" "disable")
    ("src" "source")
    ("refingt" "referring to")
    ("refing" "referring")
    ("conveneince" "convenience")
    ("upd" "update")
    ("ad" "add")
    ("disal" "disable")
    ("disb" "disable")
    ("disa" "disable")
    ("t" "the")
    ("n" "and")
    ("tog" "toggle")
    ("dbl" "disable")
    ("db" "database")
    ("sys" "system")
    ("pasw" "password")
    ("vced" "version-controlled")
    ("hardcode" "hard-code")
    ("machinge" "machine")
    ("tdo" "TODO")
    ("exter" "external")
    ("ntitai" "now that I think about it")
    ("proply" "properly")
    ("succy" "successfully")
    ("sucy" "successfully")
    ("vidoes" "videos")
    ("videoes" "videos")
    ("usb" "USB")
    ("mont" "mount")
    ("moutn" "mount")
    ("ddots" "https://github.com/Luis-Henriquez-Perez/dotfiles")
    ("vc" "version-control")
    ("omo" "on my own")
    ("sbs" "step by step")
    ("preseve" "preserve")
    ("ocmment" "comment")
    ("misce" "miscellaneous")
    ("ft" "for the")
    ("amout" "amount")
    ("ihnb" "I have not been")
    ("hb" "has been")
    ("repoo" "repository")
    ("brach" "branch")
    ("tp" "to")
    ("advics" "advices")
    ("niet" "convenient")
    ("iwtd" "I want to do")
    ("sbm" "should be more")
    ("whci" "which")
    ("whcic" "which")
    ("alting" "alternating")
    ("alply" "apply")
    ("fgo" "figure out")
    ("intfow" "I need to figure out how")
    ("intfowt" "I need to figure out how to")
    ("numer" "number")
    ("individ" "segment")
    ("sement" "segment")
    ("sements" "segments")
    ("buitl" "built")
    ("nows" "now is")
    ("nls" "newlines")
    ("wb" "will be")
    ("smething" "something")
    ("osaat" "one step at a time")
    ("enw" "new")
    ("positoin" "position")
    ("iwr" "I would rather")
    ("pice" "piece")
    ("loking" "looking")
    ("pices" "pieces")
    ("picecs" "pieces")
    ("exising" "existing")
    ("capabilties" "capabilities")
    ("leasure" "leisure")
    ("improvment" "improvement")
    ("fillng" "filling")
    ("exhaused" "exhausted")
    ("surly" "surprisingly")
    ("autofilling" "auto-filling")
    ("autofills" "auto-fills")
    ("autofill" "auto-fill")
    ("mto" "more than one")
    ("perh" "perhaps")
    ("forme" "for me")
    ("sepd" "separated")
    ("seped" "separated")
    ("otw" "otherwise")
    ("aggresively" "aggressively")
    ("pargraphs" "paragraphs")
    ("inev" "inevitable")
    ("inevitale" "inevitable")
    ("relzd" "realized")
    ("rlzd" "realized")
    ("rlzed" "realized")
    ("rlz" "realize")
    ("para" "paragraph")
    ("ime" "I mean")
    ("alrh" "already have")
    ("perfl" "perfectly")
    ("thex" "text")
    ("iss" "is")
    ("iimportant" "important")
    ("speace" "space")
    ("wheele" "wheel")
    ("whele" "wheel")
    ("jfgm" "just for good measure")
    ("whb" "will have been")
    ("figu" "figure")
    ("delets" "deletes")
    ("shndt" "should not")
    ("itac" "in that case")
    ("itic" "in this case")
    ("idhtwa" "I do not have to worry about")
    ("idhtw" "I do not have to worry")
    ("nvtl" "nevertheless")
    ("nethes" "nevertheless")
    ("nteotw" "not the end of the world")
    ("swwhi" "so what will happen is")
    ("coped" "copied")
    ("biultin" "built-in")
    ("biult" "built")
    ("letss" "let us")
    ("wsp" "whitespace")
    ("enteirely" "entirely")
    ("ifl" "I feel like")
    ("miself" "myself")
    ("goint" "going to")
    ("motiva" "motivation")
    ("edev" "Eldev")
    ("fro" "from")
    ("kio" "kind of")
    ("ynt" "you need to")
    ("ihstdw" "it has something to do with")
    ("btti" "but the thing is")
    ("jtnaf" "just to name a few")
    ("fie" "file")
    ("eldev" "Eldev")
    ("warnis" "warnings")
    ("warni" "warning")
    ("wanrings" "warnings")
    ("trakc" "track")
    ("trakcs" "tracks")
    ("spanish" "Spanish")
    ("masss" "Massachusetts")
    ("dist" "distance")
    ("rett" "Everett")
    ("everett" "Everett")
    ("honesl" "honestly")
    ("propl" "properly")
    ("compleely" "completely")
    ("strugle" "struggle")
    ("ude" "you would")
    ("asal" "as always")
    ("js" "JavaScript")
    ("javascript" "JavaScript")
    ("editi" "edit it")
    ("ihblat" "I had been looking at the")
    ("ment" "meant")
    ("atempt" "attempt")
    ("atemps" "attempts")
    ("attemps" "attempts")
    ("yeserday" "yesterday")
    ("ihblfa" "I had been looking for a")
    ("underated" "underrated")
    ("intfo" "I need to figure out")
    ("aiwt" "as I write this")
    ("eaiwt" "even as I write this")
    ("imtk" "I am thinking")
    ("dne" "does not exist")
    ("unued" "unused")
    ("actuallly" "actually")
    ("mpv" "MPV")
    ("wh" "will have")
    ("vlc" "VLC")
    ("aorn" "as of right now")
    ("uch" "much")
    ("iflia" "I feel like I am")
    ("abou" "about")
    ("hten" "then")
    ("dgmw" "do not get me wrong")
    ("aowt" "as of writing this")
    ("htmll" "HTML")
    ("vacillitate" "vacillate")
    ("vacillitated" "vacillated")
    ("javas" "JavaScript")
    ("aggree" "agree")
    ("ootbe" "out of the box experience")
    ("irl" "in real life")
    ("attowt" "at the time of writing this")
    ("playist" "playlist")
    ("itycj" "I think you can just")
    ("meida" "media")
    ("iwtbat" "I want to be able to")
    ("autmatically" "automatically")
    ("followd" "followed")
    ("follwd" "followed")
    ("sudirs" "subdirectories")
    ("subdirs" "subdirectories")
    ("renesaince" "renaissance")
    ("iah" "I already have")
    ("poject" "project")
    ("sugest" "suggest")
    ("ains" "as its name suggests")
    ("happs" "happens")
    ("ihthab" "it has to have been")
    ("oof" "of")
    ("keesp" "keeps")
    ("unnec" "unnecessary")
    ("beest" "best")
    ("thos" "those")
    ("autogened" "auto-generated")
    ("conroll" "controll")
    ("conrolling" "controlling")
    ("vcing" "version controlling")
    ("itiw" "I thought it was")
    ("dinw" "did not work")
    ("dnstw" "does not seem to work")
    ("dinstw" "did not seem to work")
    ("acs" "Emacs")
    ("itsa" "it is a")
    ("descriptoin" "description")
    ("descrition" "description")
    ("simplst" "simplest")
    ("mname" "Luis Henriquez-Perez")
    ("memail" "luis@luishp.xyz")
    ("tbf" "to be fair")
    ("wrigint" "writing")
    ("renabling" "re-enabling")
    ("usig" "using")
    ("atleast" "at least")
    ("expansin" "expansion")
    ("functioin" "function")
    ("manualy" "manually")
    ("creted" "created")
    ("ivea" "I have always")
    ("buffs" "buffers")
    ("appropriae" "appropriate")
    ("commes" "comes")
    ("sepecifying" "specifying")
    ("acsts" "acts")
    ("mabye" "maybe")
    ("deled" "deleted")
    ("linsk" "links")
    ("trough" "through")
    ("alt" "at least")
    ("boken" "broken")
    ("chooose" "choose")
    ("symbool" "symbol")
    ("symol" "symbol")
    ("imporant" "important")
    ("imporatnat" "important")
    ("destpit" "despite")
    ("rlize" "realize")
    ("hindsigt" "hindsight")
    ("hvaent" "have not")
    ("tak" "take")
    ("hsa" "has")
    ("csss" "CSS")
    ("whatss" "what is")
    ("anme" "name")
    ("alphal" "alphabetically")
    ("modi" "modification")
    ("pulish" "publish")
    ("garbae" "garbage")
    ("loos" "looks")
    ("icnftlom" "I can not for the life of me")
    ("ihv" "I have")
    ("compltions" "completions")
    ("tihi" "this is how I")
    ("wrods" "words")
    ("whethr" "whether")
    ("eexcited" "excited")
    ("explatives" "expletives")
    ("explative" "expletive")
    ("pineed" "pinned")
    ("ove" "over")
    ("entere" "enter")
    ("templeate" "template")
    ("usingn" "using")
    ("settigns" "settings")
    ("atow" "at time of writing")
    ("sae" "save")
    ("aushc" "such")
    ("ianaf" "I am not a fan")
    ("investigatoin" "investigation")
    ("iwtk" "I want to know")
    ("hnb" "has not been")
    ("solutoin" "solution")
    ("displayd" "displayed")
    ("ansers" "answers")
    ("asterix" "asterisk")
    ("asterixes" "asterisks")
    ("regexpp" "regular expression")
    ("interpretting" "interpreting")
    ("midly" "mildly")
    ("remmember" "remember")
    ("figed" "figured out")
    ("anser" "answer")
    ("fuck" "****")
    ("shit" "****")
    ("figedo" "figured out")
    ("figed" "figured")
    ("ocmpletion" "completion")
    ("achive" "achieve")
    ("completin" "completion")
    ("dabrev" "dabbrev")
    ("additi" "addition")
    ("ocmplexity" "complexity")
    ("lors" "" lorem-ipsum-insert-paragraphs)
    ("lorp" "" lorem-ipsum-insert-paragraphs)
    ("idb" "it would be")
    ("imhth" "I may have to have")
    ("ihd" "I had")
    ("iwn" "it was not")
    ("biwn" "but it was not")
    ("enhancins" "enhancing")
    ("oold" "old")
    ("explicity" "explicitly")
    ("afte" "after")
    ("simplyfy" "simplify")
    ("iin" "in")
    ("ein" "in")
    ("endeard" "endeared")
    ("qite" "quite")
    ("somet" "something")
    ("boh" "both")
    ("looing" "looking")
    ("keypres" "keypress")
    ("menat" "meant")
    ("afit" "at first I thought")
    ("positin" "position")
    ("mappign" "mapping")
    ("sate" "state")
    ("stae" "state")
    ("odnt" "do not")
    ("frnakly" "frankly")
    ("skels" "skeletons")
    ("skel" "skeleton")
    ("idnwtht" "I do not want to have to")
    ("wy" "why")
    ("o" "of")
    ("thik" "think")
    ("happed" "happened")
    ("ihbl" "I had been looking")
    ("bfsr" "but for some reason")
    ("tsnba" "this should not be a")
    ("winwiw" "which is not what I want")
    ("inwiw" "is not what I want")
    ("accepta" "acceptable")
    ("iwi" "I will")
    ("optin" "option")
    ("ibdt" "it boils down to")
    ("idnl" "I do not like")
    ("idnfai" "I did not find anything immediate")
    ("ona" "on a")
    ("idnfa" "I did not find anything")
    ("idnf" "I did not find")
    ("iwto" "it was the only")
    ("icft" "I could find that")
    ("caviat" "caveat")
    ("happenning" "happening")
    ("cmpute" "compute")
    ("aways" "always")
    ("initializaiton" "initialization")
    ("isol" "isolate")
    ("tig" "thing")
    ("tigs" "things")
    ("detial" "detail")
    ("runing" "running")
    ("wonrg" "wrong")
    ("nn" "non-nil")
    ("wit" "with")
    ("durin" "during")
    ("iwlt" "I would like to")
    ("everty" "every")
    ("rmb" "remember")
    ("idnnt" "I do not need to")
    ("ht" "have to")
    ("writng" "writing")
    ("elip" "elisp")
    ("ilil" "I like it less")
    ("ilim" "I like it more")
    ("ili" "I like it")
    ("wats" "what is")
    ("dnk" "did not know")
    ("iws" "I will show")
    ("idnkht" "I did not know how to")
    ("idnk" "I did not know")
    ("esse" "essentially")
    ("kol" "kind of like")
    ("cb" "can be")
    ("icb" "it can be")
    ("complel" "completely")
    ("ihha" "I have had a")
    ("incorp" "incorporate")
    ("modifs" "modifications")
    ("modif" "modification")
    ("wofa" "without further ado")
    ("smm" "so much more")
    ("devs" "developers")
    ("icsw" "I can see why")
    ("inttco" "I need to take care of")
    ("advyce" "advice")
    ("imnk" "I might not know")
    ("respo" "responsible")
    ("ihni" "I have no idea")
    ("ihniw" "I have no idea why")
    ("yik" "yeah I know")
    ("yea" "yeah")
    ("ya" "yeah")
    ("bir" "but I realized")
    ("feeeling" "feling")
    ("feeeling" "feeling")
    ("weree" "we are")
    ("lets" "let us")
    ("tw" "this would")
    ("imag" "imagine")
    ("creatoin" "creation")
    ("iwwt" "I will want to")
    ("dird" "dired")
    ("isic" "I suppose I could")
    ("sring" "string")
    ("chatgpt" "chatGPT")
    ("accordi" "according")
    ("acordi" "according")
    ("acord" "accord")
    ("accor" "according")
    ("timesamp" "timestamp")
    ("ultimatel" "ultimately")
    ("ulti" "ultimate")
    ("faltitt" "for a long time I thought that")
    ("falt" "for a long time")
    ("ustand" "understand")
    ("figo" "figure out")
    ("figur" "figure")
    ("packags" "packages")
    ("ftm" "for that matter")
    ("pic" "picture")
    ("eople" "people")
    ("boilerp" "boilerplate")
    ("riealized" "realized")
    ("adivce" "advice")
    ("afitt" "at first I thought that")
    ("fortunatel" "fortunately")
    ("fortu" "fortunate")
    ("wll" "well")
    ("wort" "wrote")
    ("whoppig" "whopping")
    ("requirem" "requirement")
    ("restartd" "restarted")
    ("meacs" "Emacs")
    ("solutin" "solution")
    ("instict" "instinct")
    ("whenev" "whenever")
    ("wene" "whenever")
    ("cerain" "certain")
    ("archivse" "archives")
    ("pakgs" "packages")
    ("solu" "solution")
    ("tryi" "trying")
    ("vers" "version")
    ("happeni" "happening")
    ("happe" "happen")
    ("evt" "everything")
    ("everythig" "everything")
    ("tna" "to no avail")
    ("ihht" "I have had to")
    ("ntb" "need to be")
    ("tntb" "that need to be")
    ("wanring" "warning")
    ("reproduca" "reproducibility")
    ("xpand" "expand")
    ("managem" "management")
    ("idwtgt" "I do not want to go there")
    ("goig" "going")
    ("idwt" "I do not want to")
    ("ngtdt" "not going to do this")
    ("verson" "version")
    ("ftft" "for the first time")
    ("maye" "maybe")
    ("concats" "concatenates")
    ("becausee" "because")
    ("wi" "which is")
    ("iatt" "in addition to this")
    ("elsip" "elisp")
    ("siu" "should I use")
    ("bottlenek" "bottleneck")
    ("importa" "important")
    ("initi" "initialize")
    ("majaor" "major")
    ("rese" "research")
    ("authro" "author")
    ("annoyi" "annoying")
    ("oepn" "open")
    ("ocnfigg" "configuration")
    ("udring" "during")
    ("vv" "vice versa")
    ("batt" "battery")
    ("uting" "using")
    ("specificatoin" "specification")
    ("mng" "manage")
    ("wdntht" "would not have to")
    ("remvoes" "removes")
    ("shamell" "shamelessly")
    ("shamel" "shameless")
    ("metad" "metadata")
    ("everyhing" "everything")
    ("eacs" "Emacs")
    ("relyig" "relying")
    ("ihnba" "I have not been able to")
    ("oot" "one of the")
    ("oneof" "one of")
    ("emc" "Emacs configuration")
    ("iht" "I have to")
    ("fowtd" "figure out what to do")
    ("figg" "figure")
    ("testring" "testing")
    ("recl" "recently")
    ("emas" "Emacs")
    ("pacmann" "package manager")
    ("poin" "point")
    ("ammbrevs" "abbrevs")
    ("optinally" "optionally")
    ("pagkes" "packages")
    ("recommendd" "recommendation")
    ("recomn" "recommendation")
    ("recom" "recommend")
    ("recomm" "recommend")
    ("icdju" "I could just use")
    ("iwitb" "I want it to be")
    ("iwditb" "I wanted it to be")
    ("syncl" "synchronously")
    ("emacs" "Emacs")
    ("critisized" "criticized")
    ("asynch" "asynchronously")
    ("asyncc" "asynchronously")
    ("insall" "install")
    ("insalls" "installs")
    ("eivl" "evil")
    ("biding" "binding")
    ("abrev" "abbrev")
    ("aform" "aforementioned")
    ("aforemenioned" "aforementioned")
    ("optimi" "optimization")
    ("itsb" "it is because")
    ("susp" "suspect")
    ("ness" "necessary")
    ("hnadle" "handle")
    ("anonl" "anonymous lambda")
    ("toh" "to have")
    ("qute" "quote")
    ("fle" "file")
    ("gc" "garbage collection")
    ("comiler" "compiler")
    ("suceded" "succeeded")
    ("genl" "generally")
    ("nie" "nice")
    ("wud" "would")
    ("preff" "preference")
    ("pref" "preference")
    ("usin" "using")
    ("numberd" "numbered")
    ("measore" "measure")
    ("loadig" "loading")
    ("loding" "loading")
    ("brnach" "branch")
    ("initization" "initialization")
    ("somone" "someone")
    ("rmed" "removed")
    ("investiage" "investigate")
    ("shdntb" "should not be")
    ("preciesely" "precisely")
    ("pretyt" "pretty")
    ("tb" "to be")
    ("aro" "around")
    ("tryig" "trying")
    ("afer" "after")
    ("prety" "pretty")
    ("brnaches" "branches")
    ("quet" "quiet")
    ("quetly" "quietly")
    ("ut" "but")
    ("fies" "files")
    ("definiteively" "definitively")
    ("nad" "and")
    ("elfeeed" "elfeed")
    ("elfed" "elfeed")
    ("destop" "desktop")
    ("rcentf" "recentf")
    ("duplicae" "duplicate")
    ("broser" "browser")
    ("diable" "disable")
    ("colro" "color")
    ("anwer" "answer")
    ("resitered" "registered")
    ("expasions" "expansions")
    ("rgister" "register")
    ("api" "API")
    ("tnail" "thumbnail")
    ("kbdd" "key binding")
    ("emcs" "Emacs")
    ("settingn" "setting")
    ("punctionation" "punctuation")
    ("cliche" "cliché")
    ("naive" "naïve")
    ("resume" "résumé")
    ("cafe" "café")
    ("fiance" "fiancé")
    ("eclair" "éclair")
    ("facade" "façade")
    ("tete" "tête")
    ("voila" "voilà")
    ("gotto" "have got to")
    ("foont" "font")
    ("wen" "when")
    ("htan" "than")
    ("firt" "first")
    ("neds" "ends")
    ("basd" "based")
    ("reff" "reference")
    ("welll" "we will")
    ("dml" "doom-modeline")
    ("pickture" "picture")
    ("bco" "because of")
    ("swithc" "switch")
    ("swith" "switch")
    ("tings" "things")
    ("sshot" "screenshot")
    ("frorm" "from")
    ("deveotes" "devotes")
    ("bein" "being")
    ("idn" "I do not")
    ("ikih" "I know I have")
    ("figing" "figuring out")
    ("figging" "figuring out")
    ("variaous" "various")
    ("wile" "while")
    ("eant" "meant")
    ("levl" "level")
    ("checkig" "checking")
    ("priv" "private")
    ("accout" "account")
    ("hae" "have")
    ("iwwti" "I wonder whether there is")
    ("iww" "I wonder whether")
    ("hd" "harddrive")
    ("hardd" "harddrive")
    ("tere" "there")
    ("cofnigure" "configure")
    ("autom" "automatic")
    ("autol" "automatically")
    ("suer" "user")
    ("modeline" "modeline")
    ("hwen" "when")
    ("imnsw" "I am not sure whether")
    ("sates" "states")
    ("ver" "version")
    ("projet" "project")
    ("projj" "project")
    ("infoo" "information")
    ("extenral" "external")
    ("extenr" "external")
    ("dosnt" "does not")
    ("sligh" "slight")
    ("mls" "mode lines")
    ("autoo" "automatically")
    ("funions" "functions")
    ("evall" "evaluate")
    ("configu" "configuration")
    ("confgi" "config")
    ("hwever" "pertaining")
    ("ertaining" "pertaining")
    ("consideer" "consider")
    ("nece" "necessary")
    ("improvmeent" "improvement")
    ("hink" "think")
    ("mentoned" "mentioned")
    ("whove" "who have")
    ("determening" "determining")
    ("afteir" "after")
    ("compilor" "compiler")
    ("righthand" "right-hand")
    ("lefthand" "left-hand")
    ("lhs" "left-hand side")
    ("rhs" "right-hand side")
    ("tuf" "tough")
    ("decideing" "deciding")
    ("customizeability" "customizability")
    ("reproducability" "reproducibility")
    ("reproduceability" "reproducibility")
    ("alteratives" "alternatives")
    ("takign" "taking")
    ("encript" "encrypt")
    ("encrypton" "encryption")
    ("encripton" "encryption")
    ("encription" "encryption")
    ("nl" "newline")
    ("eno" "enough")
    ("enugh" "enough")
    ("enuf" "enough")
    ("reming" "removing")
    ("sentense" "sentence")
    ("frist" "first")
    ("mv" "move")
    ("retrun" "return")
    ("voer" "over")
    ("iabt" "I am beginning to think that")
    ("tweek" "tweak")
    ("teak" "tweak")
    ("seet" "set")
    ("doen" "done")
    ("av" "available")
    ("mans" "means")
    ("ns" "not sure")
    ("inf" "in fact, ")
    ("wnev" "whenever")
    ("nev" "never")
    ("wenev" "whenever")
    ("emplate" "template")
    ("mult" "multiple")
    ("multipul" "multiple")
    ("har" "character")
    ("defi" "definitely")
    ("woudl" "would")
    ("awk" "awkward")
    ("akw" "awkward")
    ("aiws" "as I was saying")
    ("imns" "I am not sure")
    ("et" "even then")
    ("iiwt" "if I want to")
    ("itisj" "I think I should just")
    ("isj" "I should just")
    ("wereas" "whereas")
    ("conig" "config")
    ("ama" "add more abbrevs")
    ("abbreviaion" "abbreviation")
    ("abbs" "abbrevs")
    ("abb" "abbreviation")
    ("ar" "around")
    ("elm" "emacs-lisp-mode")
    ("soemthing" "something")
    ("smt" "something")
    ("udpate" "update")
    ("escpae" "escape")
    ("exi" "excited")
    ("aling" "align")
    ("setigs" "settings")
    ("setig" "setting")
    ("setin" "setting")
    ("settins" "settings")
    ("setins" "settings")
    ("stuf" "stuff")
    ("dnms" "does not make sense")
    ("str" "string")
    ("isd" "I should")
    ("ish" "I should")
    ("prov" "provide")
    ("lib" "library")
    ("whe" "whether")
    ("gona" "going to")
    ("thig" "thing")
    ("dels" "deletes")
    ("envyronmen" "environment")
    ("directries" "directories")
    ("qt" "qutebrowser")
    ("qtbrowser" "qutebrowser")
    ("redit" "reddit")
    ("insead" "instead")
    ("environement" "environment")
    ("inputing" "inputting")
    ("aot" "as opposed to")
    ("iatb" "I am thinking about")
    ("bigg" "biggest")
    ("consi" "consistent")
    ("supprot" "support")
    ("expressi" "expression")
    ("miniaml" "minimal")
    ("mateiral" "material")
    ("cdnt" "could not")
    ("tsa" "there is any")
    ("spe" "specifically")
    ("speci" "specifically")
    ("exo" "example of")
    ("inadv" "inadvertently")
    ("immediatel" "immediately")
    ("bol" "beginning of the line")
    ("cts" "check to see")
    ("cheks" "checks")
    ("ali" "alias")
    ("unk" "unknown")
    ("y" "by")
    ("tcb" "this could be")
    ("alte" "alternative")
    ("wikip" "wikipedia")
    ("incon" "inconsistent")
    ("defs" "definitions")
    ("dnw" "does not work")
    ("htdw" "has to do with")
    ("espl" "especially")
    ("exc" "except")
    ("fils" "files")
    ("doesnth" "does not have")
    ("fiels" "files")
    ("backw" "backward")
    ("forw" "forward")
    ("acept" "accept")
    ("swpawn" "spawn")
    ("nother" "another")
    ("awesoe" "awesome")
    ("iad" "in addition")
    ("rearange" "rearrange")
    ("bett" "better")
    ("dsn" "does not")
    ("fsr" "for some reason")
    ("propogate" "propagate")
    ("pakcage" "package")
    ("pakcages" "packages")
    ("motn" "more often than not")
    ("itc" "in that case")
    ("probl" "problem")
    ("dered" "considered")))

;; ("fuck" "\\ast\\ast\\ast\\ast" nil :enable-function oo-in-org-mode-p)
;; ("shit" "\\ast\\ast\\ast\\ast" nil :enable-function oo-in-org-mode-p)
;; ("b" "" 'oo-expand-html-bold :enable-function 'oo-in-html-p)
;; ("esrc" "" 'oo-expand-html-elisp-source-block :enable-function 'oo-in-html-p)
;; oo-text-abbrev-table "set" "" #'oo-expand-elisp-setq :enable-function #'oo-in-elisp-code-p)

;; oo-text-abbrev-table "smd" "" #'oo-expand-save-match-data :enable-function #'oo-in-elisp-code-p)
;; oo-text-abbrev-table "se" "" #'oo-expand-save-excursion :enable-function #'oo-in-elisp-code-p)
;; ("wcb" "" #'oo-expand-elisp-with-current-buffer :enable-function #'oo-in-elisp-code-p)
;; ("peerfect" "perfect" nil :enable-function #'oo-in-blog-post-p)
;; ("goten" "gotten" nil :enable-function #'oo-in-blog-post-p)
;; ("wirte" "write" nil :enable-function #'oo-in-blog-post-p)
;; ("userfacing" "user-facing" nil :enable-function #'oo-in-blog-post-p)
;; ("cutom" "custom" nil :enable-function #'oo-in-blog-post-p)
;; ("cutomizing" "customizing" nil :enable-function #'oo-in-blog-post-p)
;; ("alta" "a long time ago" nil :enable-function #'oo-in-blog-post-p)
;; ("wer" "were" nil :enable-function #'oo-in-blog-post-p)
;; ("previx" "prefix" nil :enable-function #'oo-in-blog-post-p)
;; ("iwh" "it would have" nil :enable-function #'oo-in-blog-post-p)
;; ("wda" "would have" nil :enable-function #'oo-in-blog-post-p)
;; ("writting" "writing" nil :enable-function #'oo-in-blog-post-p)
;; ("icf" "I could find" nil :enable-function #'oo-in-blog-post-p)
;; ("cicf" "closest I could find" nil :enable-function #'oo-in-blog-post-p)
;; ("closes" "closest" nil :enable-function #'oo-in-blog-post-p)
;; ("automa" "automatic" nil :enable-function #'oo-in-blog-post-p)
;; ("fftl" "for far too long" nil :enable-function #'oo-in-blog-post-p)
;; ("initializatoin" "initialization" nil :enable-function #'oo-in-blog-post-p)
;; ("alll" "all" nil :enable-function #'oo-in-blog-post-p)
;; ("intitialization" "initialization" nil :enable-function #'oo-in-blog-post-p)
;; ("determiend" "determined" nil :enable-function #'oo-in-blog-post-p)
;; ("bitt" "before-init-time" nil :enable-function #'oo-in-blog-post-p)
;; ("ait" "after-init-time" nil :enable-function #'oo-in-blog-post-p)
;; ("eit" "emacs-init-time" nil :enable-function #'oo-in-blog-post-p)

;; ("elasped" "elapsed" nil :enable-function #'oo-in-elisp-mode-p)
;; ("aih" "after-init-hook" nil :enable-function #'oo-in-elisp-mode-p)
;; ("esh" "emacs-startup-hook" nil :enable-function #'oo-in-elisp-mode-p)
;; ("dvar" "" #'oo-expand-elisp-defvar :enable-function #'oo-in-elisp-code-p)
;; ("funn" "" #'oo-expand-elisp-defun :enable-function #'oo-in-elisp-code-p)
;; ("dfn" "" #'oo-expand-elisp-defun :enable-function #'oo-in-elisp-code-p)

;; ("hvar" "" #'oo-expand-variable-doc-link)
;; ("vlk" "" #'oo-expand-variable-doc-link)
;; ("snapshto" "snapshot" #'oo-expand-callable-doc-link)
;; ("clk" "" #'oo-expand-callable-doc-link :enable-function #'oo-in-blog-post-p)
;; ("flk" "" #'oo-expand-callable-doc-link :enable-function #'oo-in-blog-post-p)
;; ("plk" "" #'oo-expand-package-link :enable-function #'oo-in-elisp-comment-p)
;; ("plk" "" #'oo-expand-org-package-link :enable-function #'oo-in-blog-post-p)
;; ("plink" "" #'oo-expand-org-package-link :enable-function #'oo-in-blog-post-p)
;; ("scowered" "load-path" nil :enable-function #'oo-in-elisp-mode-p)
;; ("lpath" "load-path" nil :enable-function #'oo-in-elisp-mode-p)
;; ("loadpath" "load-path" nil :enable-function #'oo-in-elisp-mode-p)
;; ("gpm" "(goto-char (point-min))" nil :enable-function #'oo-in-elisp-mode-p)
;; ("pm" "(point-min)" nil :enable-function #'oo-in-elisp-mode-p)
;; ("pmin" "(point-min)" nil :enable-function #'oo-in-elisp-mode-p)
;; ("ddir" "default-directory" nil :enable-function #'oo-in-elisp-mode-p)

;; ("clk" "" #'oo-expand-config-link :enable-function #'oo-in-org-mode-p)
;; ("clink" "" #'oo-expand-config-link :enable-function #'oo-in-org-mode-p)
;; ("rnni" "return non-nil if" nil :enable-function #'oo-in-elisp-comment-p)
;; ("rnnw" "return non-nil when" nil :enable-function #'oo-in-elisp-comment-p)
;; ("rtnnw" "return non-nil when" nil :enable-function #'oo-in-elisp-comment-p)
;; ("partial" "apply-partially" nil :enable-function #'oo-in-elisp-mode-p)
;; ("gpmax" "(goto-char (point-max))" nil :enable-function #'oo-in-elisp-mode-p)
;; ("pman" "(point-max)" nil :enable-function #'oo-in-elisp-mode-p)
;; ("pmax" "(point-max)" nil :enable-function #'oo-in-elisp-mode-p)
;; ("pt" "(point)" nil :enable-function #'oo-in-elisp-mode-p)

;; ("tsrc" "#+begin_src text \n#+end_src\n" nil :enable-function #'oo-in-org-mode-p)
;; ("bq" "#+begin_quote \n#+end_quote\n" nil :enable-function #'oo-in-org-mode-p)
;; ("esrc" "#+begin_src emacs-lisp\n#+end_src\n" nil :enable-function #'oo-in-org-mode-p)
;;; provide
(provide '910-text-abbrevs)
;;; 910-text-abbrevs.el ends here
