;;; 910-text-abbrevs.el --- TODO: add commentary -*- lexical-binding: t; -*-
;;
;; Copyright (c) 2024 Free Software Foundation, Inc.
;;
;; Author: Luis Henriquez-Perez <luis@luishp.xyz>
;; Homepage: https://github.com/Luis-Henriquez-Perez/dotfiles/
;;
;; This file is not part of GNU Emacs.
;;
;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License as
;; published by the Free Software Foundation, either version 3 of the
;; License, or (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful, but
;; WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
;; General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program. If not, see <http://www.gnu.org/licenses/>.
;;
;;; Commentary:
;;
;; TODO: add commentary
;;
;;; Code:
(require '050-base)
(require 'abbrev)

(define-abbrev oo-text-abbrev-table "emal" "email" nil)
(define-abbrev oo-text-abbrev-table "stil" "still" nil)
(define-abbrev oo-text-abbrev-table "customizaton" "customization" nil)
(define-abbrev oo-text-abbrev-table "comiled" "compiled" nil)
(define-abbrev oo-text-abbrev-table "imngtha" "I am going to have a" nil)
(define-abbrev oo-text-abbrev-table "progrmatically" "programatically" nil)
(define-abbrev oo-text-abbrev-table "frtm" "furthermore" nil)
(define-abbrev oo-text-abbrev-table "tdwiw" "to do what I want" nil)
(define-abbrev oo-text-abbrev-table "muisc" "music" nil)
(define-abbrev oo-text-abbrev-table "musc" "music" nil)
(define-abbrev oo-text-abbrev-table "picures" "pictures" nil)
(define-abbrev oo-text-abbrev-table "picure" "picture" nil)
(define-abbrev oo-text-abbrev-table "pics" "pictures" nil)
(define-abbrev oo-text-abbrev-table "foms" "forms" nil)
(define-abbrev oo-text-abbrev-table "til" "until" nil)
(define-abbrev oo-text-abbrev-table "craclking" "crackling" nil)
(define-abbrev oo-text-abbrev-table "horu" "hour" nil)
(define-abbrev oo-text-abbrev-table "kep" "keep" nil)
(define-abbrev oo-text-abbrev-table "iimet" "it is much easier to" nil)
(define-abbrev oo-text-abbrev-table "hled" "highlighted" nil)
(define-abbrev oo-text-abbrev-table "tras" "trash" nil)
(define-abbrev oo-text-abbrev-table "scrapt" "scraped" nil)
(define-abbrev oo-text-abbrev-table "sko" "some kind of" nil)
(define-abbrev oo-text-abbrev-table "lm" "let me" nil)
(define-abbrev oo-text-abbrev-table "imc" "in many cases" nil)
(define-abbrev oo-text-abbrev-table "woht" "without having to" nil)
(define-abbrev oo-text-abbrev-table "redef" "re-define" nil)
(define-abbrev oo-text-abbrev-table "redefing" "re-defining" nil)
(define-abbrev oo-text-abbrev-table "invis" "invisible" nil)
(define-abbrev oo-text-abbrev-table "resly" "respectively" nil)
(define-abbrev oo-text-abbrev-table "avod" "avoid" nil)
(define-abbrev oo-text-abbrev-table "agneda" "agenda" nil)
(define-abbrev oo-text-abbrev-table "ater" "after" nil)
(define-abbrev oo-text-abbrev-table "unl" "unless" nil)
(define-abbrev oo-text-abbrev-table "lop" "loop" nil)
(define-abbrev oo-text-abbrev-table "vanila" "vanilla" nil)
(define-abbrev oo-text-abbrev-table "vannilla" "vanilla" nil)
(define-abbrev oo-text-abbrev-table "cimpiled" "compiled" nil)
(define-abbrev oo-text-abbrev-table "cont" "cannot" nil)
(define-abbrev oo-text-abbrev-table "kbinding" "keybinding" nil)
(define-abbrev oo-text-abbrev-table "idnkt" "I did not know that" nil)
(define-abbrev oo-text-abbrev-table "b" "be" nil)
(define-abbrev oo-text-abbrev-table "rm" "remove" nil)
(define-abbrev oo-text-abbrev-table "otherw" "otherwise" nil)
(define-abbrev oo-text-abbrev-table "symb" "symbol" nil)
(define-abbrev oo-text-abbrev-table "atl" "at least" nil)
(define-abbrev oo-text-abbrev-table "normuch" "notmuch" nil)
(define-abbrev oo-text-abbrev-table "smome" "some" nil)
(define-abbrev oo-text-abbrev-table "snaphsot" "snapshot" nil)
(define-abbrev oo-text-abbrev-table "comiled" "compiled" nil)
(define-abbrev oo-text-abbrev-table "trwi" "the reason why I" nil)
(define-abbrev oo-text-abbrev-table "harddrive" "hardrive" nil)
(define-abbrev oo-text-abbrev-table "mself" "my self" nil)
(define-abbrev oo-text-abbrev-table "doit" "do it" nil)
(define-abbrev oo-text-abbrev-table "eare" "are" nil)
(define-abbrev oo-text-abbrev-table "awes" "awesome" nil)
(define-abbrev oo-text-abbrev-table "fav" "favorite" nil)
(define-abbrev oo-text-abbrev-table "metod" "method" nil)
(define-abbrev oo-text-abbrev-table "wpps" "wallpapers" nil)
(define-abbrev oo-text-abbrev-table "wpp" "wallpaper" nil)
(define-abbrev oo-text-abbrev-table "walpaper" "wallpaper" nil)
(define-abbrev oo-text-abbrev-table "walpapers" "wallpapers" nil)
(define-abbrev oo-text-abbrev-table "sfw" "SFW" nil)
(define-abbrev oo-text-abbrev-table "nsfw" "NSFW" nil)
(define-abbrev oo-text-abbrev-table "triend" "tried" nil)
(define-abbrev oo-text-abbrev-table "havnet" "have not" nil)
(define-abbrev oo-text-abbrev-table "dled" "downloaded" nil)
(define-abbrev oo-text-abbrev-table "wallpaer" "wallpaper" nil)
(define-abbrev oo-text-abbrev-table "wallpaers" "wallpapers" nil)
(define-abbrev oo-text-abbrev-table "wek" "week" nil)
(define-abbrev oo-text-abbrev-table "wk" "week" nil)
(define-abbrev oo-text-abbrev-table "ai" "AI" nil)
(define-abbrev oo-text-abbrev-table "itint" "I think I need to" nil)
(define-abbrev oo-text-abbrev-table "sysd" "systemd" nil)
(define-abbrev oo-text-abbrev-table "kebd" "keybinding" nil)
(define-abbrev oo-text-abbrev-table "webscrpa" "webscrape" nil)
(define-abbrev oo-text-abbrev-table "fringnes" "fringes" nil)
(define-abbrev oo-text-abbrev-table "wms" "window managers" nil)
(define-abbrev oo-text-abbrev-table "wm" "window manager" nil)
(define-abbrev oo-text-abbrev-table "dki" "I do not know if" nil)
(define-abbrev oo-text-abbrev-table "websti" "website" nil)
(define-abbrev oo-text-abbrev-table "thest" "test" nil)
(define-abbrev oo-text-abbrev-table "idkwi" "I do not know I" nil)
(define-abbrev oo-text-abbrev-table "dkwi" "I do not know I" nil)
(define-abbrev oo-text-abbrev-table "exe" "executable" nil)
(define-abbrev oo-text-abbrev-table "exable" "executable" nil)
(define-abbrev oo-text-abbrev-table "aproxl" "approximately" nil)
(define-abbrev oo-text-abbrev-table "aprox" "approximate" nil)
(define-abbrev oo-text-abbrev-table "instaled" "installed" nil)
(define-abbrev oo-text-abbrev-table "oses" "OSes" nil)
(define-abbrev oo-text-abbrev-table "wroth" "worth" nil)
(define-abbrev oo-text-abbrev-table "adament" "adamant" nil)
(define-abbrev oo-text-abbrev-table "foh" "figure out how" nil)
(define-abbrev oo-text-abbrev-table "taw" "that would" nil)
(define-abbrev oo-text-abbrev-table "m" "my" nil)
(define-abbrev oo-text-abbrev-table "f" "for" nil)
(define-abbrev oo-text-abbrev-table "doc" "documentation" nil)
(define-abbrev oo-text-abbrev-table "fmc" "for my case" nil)
(define-abbrev oo-text-abbrev-table "profle" "profile" nil)
(define-abbrev oo-text-abbrev-table "iia" "if I am" nil)
(define-abbrev oo-text-abbrev-table "vodi" "void" nil)
(define-abbrev oo-text-abbrev-table "r" "are" nil)
(define-abbrev oo-text-abbrev-table "w" "with" nil)
(define-abbrev oo-text-abbrev-table "deping" "depending" nil)
(define-abbrev oo-text-abbrev-table "hvnt" "have not" nil)
(define-abbrev oo-text-abbrev-table "ihvnt" "I have not" nil)
(define-abbrev oo-text-abbrev-table "amap" "as much as possible" nil)
(define-abbrev oo-text-abbrev-table "thtb" "that had to be" nil)
(define-abbrev oo-text-abbrev-table "wpap" "wallpaper" nil)
(define-abbrev oo-text-abbrev-table "wpapa" "wallpaper" nil)
(define-abbrev oo-text-abbrev-table "mnt" "mount" nil)
(define-abbrev oo-text-abbrev-table "mnted" "mounted" nil)
(define-abbrev oo-text-abbrev-table "rel" "relative" nil)
(define-abbrev oo-text-abbrev-table "hdd" "harddrive" nil)
(define-abbrev oo-text-abbrev-table "rom" "from" nil)
(define-abbrev oo-text-abbrev-table "targ" "target" nil)
(define-abbrev oo-text-abbrev-table "disale" "disable" nil)
(define-abbrev oo-text-abbrev-table "dis" "disable" nil)
(define-abbrev oo-text-abbrev-table "src" "source" nil)
(define-abbrev oo-text-abbrev-table "refingt" "referring to" nil)
(define-abbrev oo-text-abbrev-table "refing" "referring" nil)
(define-abbrev oo-text-abbrev-table "conveneince" "convenience" nil)
(define-abbrev oo-text-abbrev-table "upd" "update" nil)
(define-abbrev oo-text-abbrev-table "ad" "add" nil)
(define-abbrev oo-text-abbrev-table "disal" "disable" nil)
(define-abbrev oo-text-abbrev-table "disb" "disable" nil)
(define-abbrev oo-text-abbrev-table "disa" "disable" nil)
(define-abbrev oo-text-abbrev-table "t" "the" nil)
(define-abbrev oo-text-abbrev-table "n" "and" nil)
(define-abbrev oo-text-abbrev-table "tog" "toggle" nil)
(define-abbrev oo-text-abbrev-table "dbl" "disable" nil)
(define-abbrev oo-text-abbrev-table "db" "database" nil)
(define-abbrev oo-text-abbrev-table "sys" "system" nil)
(define-abbrev oo-text-abbrev-table "pasw" "password" nil)
(define-abbrev oo-text-abbrev-table "vced" "version-controlled" nil)
(define-abbrev oo-text-abbrev-table "hardcode" "hard-code" nil)
(define-abbrev oo-text-abbrev-table "machinge" "machine" nil)
(define-abbrev oo-text-abbrev-table "tdo" "TODO" nil)
(define-abbrev oo-text-abbrev-table "exter" "external" nil)
(define-abbrev oo-text-abbrev-table "ntitai" "now that I think about it" nil)
(define-abbrev oo-text-abbrev-table "proply" "properly" nil)
(define-abbrev oo-text-abbrev-table "succy" "successfully" nil)
(define-abbrev oo-text-abbrev-table "sucy" "successfully" nil)
(define-abbrev oo-text-abbrev-table "vidoes" "videos" nil)
(define-abbrev oo-text-abbrev-table "videoes" "videos" nil)
(define-abbrev oo-text-abbrev-table "usb" "USB" nil)
(define-abbrev oo-text-abbrev-table "mont" "mount" nil)
(define-abbrev oo-text-abbrev-table "moutn" "mount" nil)
(define-abbrev oo-text-abbrev-table "ddots" "https://github.com/Luis-Henriquez-Perez/dotfiles" nil)
(define-abbrev oo-text-abbrev-table "vc" "version-control" nil)
(define-abbrev oo-text-abbrev-table "omo" "on my own" nil)
(define-abbrev oo-text-abbrev-table "sbs" "step by step" nil)
(define-abbrev oo-text-abbrev-table "preseve" "preserve" nil)
(define-abbrev oo-text-abbrev-table "ocmment" "comment" nil)
(define-abbrev oo-text-abbrev-table "misce" "miscellaneous" nil)
(define-abbrev oo-text-abbrev-table "ft" "for the" nil)
(define-abbrev oo-text-abbrev-table "amout" "amount" nil)
(define-abbrev oo-text-abbrev-table "ihnb" "I have not been" nil)
(define-abbrev oo-text-abbrev-table "hb" "has been" nil)
(define-abbrev oo-text-abbrev-table "repoo" "repository" nil)
(define-abbrev oo-text-abbrev-table "brach" "branch" nil)
(define-abbrev oo-text-abbrev-table "tp" "to" nil)
(define-abbrev oo-text-abbrev-table "advics" "advices" nil)
(define-abbrev oo-text-abbrev-table "niet" "convenient" nil)
(define-abbrev oo-text-abbrev-table "iwtd" "I want to do" nil)
(define-abbrev oo-text-abbrev-table "sbm" "should be more" nil)
(define-abbrev oo-text-abbrev-table "whci" "which" nil)
(define-abbrev oo-text-abbrev-table "whcic" "which" nil)
(define-abbrev oo-text-abbrev-table "alting" "alternating" nil)
(define-abbrev oo-text-abbrev-table "alply" "apply" nil)
(define-abbrev oo-text-abbrev-table "fgo" "figure out" nil)
(define-abbrev oo-text-abbrev-table "intfow" "I need to figure out how" nil)
(define-abbrev oo-text-abbrev-table "intfowt" "I need to figure out how to" nil)
(define-abbrev oo-text-abbrev-table "numer" "number" nil)
(define-abbrev oo-text-abbrev-table "individ" "segment" nil)
(define-abbrev oo-text-abbrev-table "sement" "segment" nil)
(define-abbrev oo-text-abbrev-table "sements" "segments" nil)
(define-abbrev oo-text-abbrev-table "buitl" "built" nil)
(define-abbrev oo-text-abbrev-table "nows" "now is" nil)
(define-abbrev oo-text-abbrev-table "nls" "newlines" nil)
(define-abbrev oo-text-abbrev-table "wb" "will be" nil)
(define-abbrev oo-text-abbrev-table "smething" "something" nil)
(define-abbrev oo-text-abbrev-table "osaat" "one step at a time" nil)
(define-abbrev oo-text-abbrev-table "enw" "new" nil)
(define-abbrev oo-text-abbrev-table "positoin" "position" nil)
(define-abbrev oo-text-abbrev-table "iwr" "I would rather" nil)
(define-abbrev oo-text-abbrev-table "pice" "piece" nil)
(define-abbrev oo-text-abbrev-table "loking" "looking" nil)
(define-abbrev oo-text-abbrev-table "pices" "pieces" nil)
(define-abbrev oo-text-abbrev-table "picecs" "pieces" nil)
(define-abbrev oo-text-abbrev-table "exising" "existing" nil)
(define-abbrev oo-text-abbrev-table "capabilties" "capabilities" nil)
(define-abbrev oo-text-abbrev-table "leasure" "leisure" nil)
(define-abbrev oo-text-abbrev-table "improvment" "improvement" nil)
(define-abbrev oo-text-abbrev-table "fillng" "filling" nil)
(define-abbrev oo-text-abbrev-table "exhaused" "exhausted" nil)
(define-abbrev oo-text-abbrev-table "surly" "surprisingly" nil)
(define-abbrev oo-text-abbrev-table "autofilling" "auto-filling" nil)
(define-abbrev oo-text-abbrev-table "autofills" "auto-fills" nil)
(define-abbrev oo-text-abbrev-table "autofill" "auto-fill" nil)
(define-abbrev oo-text-abbrev-table "mto" "more than one" nil)
(define-abbrev oo-text-abbrev-table "perh" "perhaps" nil)
(define-abbrev oo-text-abbrev-table "forme" "for me" nil)
(define-abbrev oo-text-abbrev-table "sepd" "separated" nil)
(define-abbrev oo-text-abbrev-table "seped" "separated" nil)
(define-abbrev oo-text-abbrev-table "otw" "otherwise" nil)
(define-abbrev oo-text-abbrev-table "aggresively" "aggressively" nil)
(define-abbrev oo-text-abbrev-table "pargraphs" "paragraphs" nil)
(define-abbrev oo-text-abbrev-table "inev" "inevitable" nil)
(define-abbrev oo-text-abbrev-table "inevitale" "inevitable" nil)
(define-abbrev oo-text-abbrev-table "relzd" "realized" nil)
(define-abbrev oo-text-abbrev-table "rlzd" "realized" nil)
(define-abbrev oo-text-abbrev-table "rlzed" "realized" nil)
(define-abbrev oo-text-abbrev-table "rlz" "realize" nil)
(define-abbrev oo-text-abbrev-table "para" "paragraph" nil)
(define-abbrev oo-text-abbrev-table "ime" "I mean" nil)
(define-abbrev oo-text-abbrev-table "alrh" "already have" nil)
(define-abbrev oo-text-abbrev-table "perfl" "perfectly" nil)
(define-abbrev oo-text-abbrev-table "thex" "text" nil)
(define-abbrev oo-text-abbrev-table "iss" "is" nil)
(define-abbrev oo-text-abbrev-table "iimportant" "important" nil)
(define-abbrev oo-text-abbrev-table "speace" "space" nil)
(define-abbrev oo-text-abbrev-table "wheele" "wheel" nil)
(define-abbrev oo-text-abbrev-table "whele" "wheel" nil)
(define-abbrev oo-text-abbrev-table "jfgm" "just for good measure" nil)
(define-abbrev oo-text-abbrev-table "whb" "will have been" nil)
(define-abbrev oo-text-abbrev-table "figu" "figure" nil)
(define-abbrev oo-text-abbrev-table "delets" "deletes" nil)
(define-abbrev oo-text-abbrev-table "shndt" "should not" nil)
(define-abbrev oo-text-abbrev-table "itac" "in that case" nil)
(define-abbrev oo-text-abbrev-table "itic" "in this case" nil)
(define-abbrev oo-text-abbrev-table "idhtwa" "I do not have to worry about" nil)
(define-abbrev oo-text-abbrev-table "idhtw" "I do not have to worry" nil)
(define-abbrev oo-text-abbrev-table "nvtl" "nevertheless" nil)
(define-abbrev oo-text-abbrev-table "nethes" "nevertheless" nil)
(define-abbrev oo-text-abbrev-table "nteotw" "not the end of the world" nil)
(define-abbrev oo-text-abbrev-table "swwhi" "so what will happen is" nil)
(define-abbrev oo-text-abbrev-table "coped" "copied" nil)
(define-abbrev oo-text-abbrev-table "biultin" "built-in" nil)
(define-abbrev oo-text-abbrev-table "biult" "built" nil)
(define-abbrev oo-text-abbrev-table "letss" "let us" nil)
(define-abbrev oo-text-abbrev-table "wsp" "whitespace" nil)
(define-abbrev oo-text-abbrev-table "enteirely" "entirely" nil)
(define-abbrev oo-text-abbrev-table "ifl" "I feel like" nil)
(define-abbrev oo-text-abbrev-table "miself" "myself" nil)
(define-abbrev oo-text-abbrev-table "goint" "going to" nil)
(define-abbrev oo-text-abbrev-table "motiva" "motivation" nil)
(define-abbrev oo-text-abbrev-table "edev" "Eldev" nil)
(define-abbrev oo-text-abbrev-table "fro" "from" nil)
(define-abbrev oo-text-abbrev-table "kio" "kind of" nil)
(define-abbrev oo-text-abbrev-table "ynt" "you need to" nil)
(define-abbrev oo-text-abbrev-table "ihstdw" "it has something to do with" nil)
(define-abbrev oo-text-abbrev-table "btti" "but the thing is" nil)
(define-abbrev oo-text-abbrev-table "jtnaf" "just to name a few" nil)
(define-abbrev oo-text-abbrev-table "fie" "file" nil)
(define-abbrev oo-text-abbrev-table "eldev" "Eldev" nil)
(define-abbrev oo-text-abbrev-table "warnis" "warnings" nil)
(define-abbrev oo-text-abbrev-table "warni" "warning" nil)
(define-abbrev oo-text-abbrev-table "wanrings" "warnings" nil)
(define-abbrev oo-text-abbrev-table "trakc" "track" nil)
(define-abbrev oo-text-abbrev-table "trakcs" "tracks" nil)
(define-abbrev oo-text-abbrev-table "spanish" "Spanish" nil)
(define-abbrev oo-text-abbrev-table "masss" "Massachusetts" nil)
(define-abbrev oo-text-abbrev-table "dist" "distance" nil)
(define-abbrev oo-text-abbrev-table "rett" "Everett" nil)
(define-abbrev oo-text-abbrev-table "everett" "Everett" nil)
(define-abbrev oo-text-abbrev-table "honesl" "honestly" nil)
(define-abbrev oo-text-abbrev-table "propl" "properly" nil)
(define-abbrev oo-text-abbrev-table "compleely" "completely" nil)
(define-abbrev oo-text-abbrev-table "strugle" "struggle" nil)
(define-abbrev oo-text-abbrev-table "ude" "you would" nil)
(define-abbrev oo-text-abbrev-table "asal" "as always" nil)
(define-abbrev oo-text-abbrev-table "js" "JavaScript" nil)
(define-abbrev oo-text-abbrev-table "javascript" "JavaScript" nil)
(define-abbrev oo-text-abbrev-table "editi" "edit it" nil)
(define-abbrev oo-text-abbrev-table "ihblat" "I had been looking at the" nil)
(define-abbrev oo-text-abbrev-table "ment" "meant" nil)
(define-abbrev oo-text-abbrev-table "atempt" "attempt" nil)
(define-abbrev oo-text-abbrev-table "atemps" "attempts" nil)
(define-abbrev oo-text-abbrev-table "attemps" "attempts" nil)
(define-abbrev oo-text-abbrev-table "yeserday" "yesterday" nil)
(define-abbrev oo-text-abbrev-table "ihblfa" "I had been looking for a" nil)
(define-abbrev oo-text-abbrev-table "underated" "underrated" nil)
(define-abbrev oo-text-abbrev-table "intfo" "I need to figure out" nil)
(define-abbrev oo-text-abbrev-table "aiwt" "as I write this" nil)
(define-abbrev oo-text-abbrev-table "eaiwt" "even as I write this" nil)
(define-abbrev oo-text-abbrev-table "imtk" "I am thinking" nil)
(define-abbrev oo-text-abbrev-table "dne" "does not exist" nil)
(define-abbrev oo-text-abbrev-table "b" "" 'oo-expand-html-bold :enable-function 'oo-in-html-p)
(define-abbrev oo-text-abbrev-table "esrc" "" 'oo-expand-html-elisp-source-block :enable-function 'oo-in-html-p)
(define-abbrev oo-text-abbrev-table "unued" "unused" nil)
(define-abbrev oo-text-abbrev-table "actuallly" "actually" nil)
(define-abbrev oo-text-abbrev-table "mpv" "MPV" nil)
(define-abbrev oo-text-abbrev-table "wh" "will have" nil)
(define-abbrev oo-text-abbrev-table "vlc" "VLC" nil)
(define-abbrev oo-text-abbrev-table "aorn" "as of right now" nil)
(define-abbrev oo-text-abbrev-table "uch" "much" nil)
(define-abbrev oo-text-abbrev-table "iflia" "I feel like I am" nil)
(define-abbrev oo-text-abbrev-table "abou" "about" nil)
(define-abbrev oo-text-abbrev-table "hten" "then" nil)
(define-abbrev oo-text-abbrev-table "dgmw" "do not get me wrong" nil)
(define-abbrev oo-text-abbrev-table "aowt" "as of writing this" nil)
(define-abbrev oo-text-abbrev-table "htmll" "HTML" nil)
(define-abbrev oo-text-abbrev-table "vacillitate" "vacillate" nil)
(define-abbrev oo-text-abbrev-table "vacillitated" "vacillated" nil)
(define-abbrev oo-text-abbrev-table "javas" "JavaScript" nil)
(define-abbrev oo-text-abbrev-table "aggree" "agree" nil)
(define-abbrev oo-text-abbrev-table "ootbe" "out of the box experience" nil)
(define-abbrev oo-text-abbrev-table "irl" "in real life" nil)
(define-abbrev oo-text-abbrev-table "attowt" "at the time of writing this" nil)
(define-abbrev oo-text-abbrev-table "playist" "playlist" nil)
(define-abbrev oo-text-abbrev-table "itycj" "I think you can just" nil)
(define-abbrev oo-text-abbrev-table "meida" "media" nil)
(define-abbrev oo-text-abbrev-table "iwtbat" "I want to be able to" nil)
(define-abbrev oo-text-abbrev-table "autmatically" "automatically" nil)
(define-abbrev oo-text-abbrev-table "followd" "followed" nil)
(define-abbrev oo-text-abbrev-table "follwd" "followed" nil)
(define-abbrev oo-text-abbrev-table "sudirs" "subdirectories" nil)
(define-abbrev oo-text-abbrev-table "subdirs" "subdirectories" nil)
(define-abbrev oo-text-abbrev-table "renesaince" "renaissance" nil)
(define-abbrev oo-text-abbrev-table "iah" "I already have" nil)
(define-abbrev oo-text-abbrev-table "poject" "project" nil)
(define-abbrev oo-text-abbrev-table "sugest" "suggest" nil)
(define-abbrev oo-text-abbrev-table "ains" "as its name suggests" nil)
(define-abbrev oo-text-abbrev-table "happs" "happens" nil)
(define-abbrev oo-text-abbrev-table "ihthab" "it has to have been" nil)
(define-abbrev oo-text-abbrev-table "oof" "of" nil)
(define-abbrev oo-text-abbrev-table "keesp" "keeps" nil)
(define-abbrev oo-text-abbrev-table "unnec" "unnecessary" nil)
(define-abbrev oo-text-abbrev-table "beest" "best" nil)
(define-abbrev oo-text-abbrev-table "thos" "those" nil)
(define-abbrev oo-text-abbrev-table "autogened" "auto-generated" nil)
(define-abbrev oo-text-abbrev-table "conroll" "controll" nil)
(define-abbrev oo-text-abbrev-table "conrolling" "controlling" nil)
(define-abbrev oo-text-abbrev-table "vcing" "version controlling" nil)
(define-abbrev oo-text-abbrev-table "itiw" "I thought it was" nil)
(define-abbrev oo-text-abbrev-table "dinw" "did not work" nil)
(define-abbrev oo-text-abbrev-table "dnstw" "does not seem to work" nil)
(define-abbrev oo-text-abbrev-table "dinstw" "did not seem to work" nil)
(define-abbrev oo-text-abbrev-table "acs" "Emacs" nil)
(define-abbrev oo-text-abbrev-table "itsa" "it is a" nil)
(define-abbrev oo-text-abbrev-table "descriptoin" "description" nil)
(define-abbrev oo-text-abbrev-table "descrition" "description" nil)
(define-abbrev oo-text-abbrev-table "simplst" "simplest" nil)
(define-abbrev oo-text-abbrev-table "mname" "Luis Henriquez-Perez" nil)
(define-abbrev oo-text-abbrev-table "memail" "luis@luishp.xyz" nil)
(define-abbrev oo-text-abbrev-table "tbf" "to be fair" nil)
(define-abbrev oo-text-abbrev-table "wrigint" "writing" nil)
(define-abbrev oo-text-abbrev-table "renabling" "re-enabling" nil)
(define-abbrev oo-text-abbrev-table "usig" "using" nil)
(define-abbrev oo-text-abbrev-table "atleast" "at least" nil)
(define-abbrev oo-text-abbrev-table "expansin" "expansion" nil)
(define-abbrev oo-text-abbrev-table "functioin" "function" nil)
(define-abbrev oo-text-abbrev-table "manualy" "manually" nil)
(define-abbrev oo-text-abbrev-table "creted" "created" nil)
(define-abbrev oo-text-abbrev-table "ivea" "I have always" nil)
(define-abbrev oo-text-abbrev-table "buffs" "buffers" nil)
(define-abbrev oo-text-abbrev-table "appropriae" "appropriate" nil)
(define-abbrev oo-text-abbrev-table "commes" "comes" nil)
(define-abbrev oo-text-abbrev-table "sepecifying" "specifying" nil)
;; (define-abbrev oo-text-abbrev-table "set" "" #'oo-expand-elisp-setq :enable-function #'oo-in-elisp-code-p)
(define-abbrev oo-text-abbrev-table "acsts" "acts" nil)
(define-abbrev oo-text-abbrev-table "mabye" "maybe" nil)
(define-abbrev oo-text-abbrev-table "deled" "deleted" nil)
(define-abbrev oo-text-abbrev-table "linsk" "links" nil)
(define-abbrev oo-text-abbrev-table "trough" "through" nil)
(define-abbrev oo-text-abbrev-table "alt" "at least" nil)
(define-abbrev oo-text-abbrev-table "boken" "broken" nil)
(define-abbrev oo-text-abbrev-table "chooose" "choose" nil)
(define-abbrev oo-text-abbrev-table "symbool" "symbol" nil)
(define-abbrev oo-text-abbrev-table "symol" "symbol" nil)
(define-abbrev oo-text-abbrev-table "imporant" "important" nil)
(define-abbrev oo-text-abbrev-table "imporatnat" "important" nil)
(define-abbrev oo-text-abbrev-table "msgv" "" 'oo-expand-elisp-message-var :enable-function #'oo-in-elisp-code-p)
(define-abbrev oo-text-abbrev-table "msg" "" 'oo-expand-elisp-message :enable-function #'oo-in-elisp-code-p)
(define-abbrev oo-text-abbrev-table "destpit" "despite" nil)
(define-abbrev oo-text-abbrev-table "rlize" "realize" nil)
(define-abbrev oo-text-abbrev-table "hindsigt" "hindsight" nil)
(define-abbrev oo-text-abbrev-table "hvaent" "have not" nil)
(define-abbrev oo-text-abbrev-table "tak" "take" nil)
(define-abbrev oo-text-abbrev-table "hsa" "has" nil)
(define-abbrev oo-text-abbrev-table "csss" "CSS" nil)
(define-abbrev oo-text-abbrev-table "whatss" "what is" nil)
(define-abbrev oo-text-abbrev-table "anme" "name" nil)
(define-abbrev oo-text-abbrev-table "alphal" "alphabetically" nil)
(define-abbrev oo-text-abbrev-table "modi" "modification" nil)
(define-abbrev oo-text-abbrev-table "pulish" "publish" nil)
(define-abbrev oo-text-abbrev-table "garbae" "garbage" nil)
(define-abbrev oo-text-abbrev-table "loos" "looks" nil)
(define-abbrev oo-text-abbrev-table "icnftlom" "I can not for the life of me" nil)
(define-abbrev oo-text-abbrev-table "ihv" "I have" nil)
(define-abbrev oo-text-abbrev-table "compltions" "completions" nil)
(define-abbrev oo-text-abbrev-table "tihi" "this is how I" nil)
(define-abbrev oo-text-abbrev-table "wrods" "words" nil)
(define-abbrev oo-text-abbrev-table "whethr" "whether" nil)
(define-abbrev oo-text-abbrev-table "eexcited" "excited" nil)
(define-abbrev oo-text-abbrev-table "explatives" "expletives" nil)
(define-abbrev oo-text-abbrev-table "explative" "expletive" nil)
(define-abbrev oo-text-abbrev-table "pineed" "pinned" nil)
(define-abbrev oo-text-abbrev-table "ove" "over" nil)
(define-abbrev oo-text-abbrev-table "entere" "enter" nil)
(define-abbrev oo-text-abbrev-table "templeate" "template" nil)
(define-abbrev oo-text-abbrev-table "usingn" "using" nil)
(define-abbrev oo-text-abbrev-table "settigns" "settings" nil)
(define-abbrev oo-text-abbrev-table "atow" "at time of writing" nil)
(define-abbrev oo-text-abbrev-table "sae" "save" nil)
(define-abbrev oo-text-abbrev-table "aushc" "such" nil)
(define-abbrev oo-text-abbrev-table "ianaf" "I am not a fan" nil)
(define-abbrev oo-text-abbrev-table "investigatoin" "investigation" nil)
(define-abbrev oo-text-abbrev-table "iwtk" "I want to know" nil)
(define-abbrev oo-text-abbrev-table "hnb" "has not been" nil)
(define-abbrev oo-text-abbrev-table "solutoin" "solution" nil)
(define-abbrev oo-text-abbrev-table "displayd" "displayed" nil)
(define-abbrev oo-text-abbrev-table "ansers" "answers" nil)
(define-abbrev oo-text-abbrev-table "asterix" "asterisk" nil)
(define-abbrev oo-text-abbrev-table "asterixes" "asterisks" nil)
(define-abbrev oo-text-abbrev-table "regexpp" "regular expression" nil)
(define-abbrev oo-text-abbrev-table "interpretting" "interpreting" nil)
(define-abbrev oo-text-abbrev-table "midly" "mildly" nil)
(define-abbrev oo-text-abbrev-table "remmember" "remember" nil)
(define-abbrev oo-text-abbrev-table "figed" "figured out" nil)
(define-abbrev oo-text-abbrev-table "anser" "answer" nil)
(define-abbrev oo-text-abbrev-table "fuck" "\\ast\\ast\\ast\\ast" nil :enable-function #'oo-in-org-mode-p)
(define-abbrev oo-text-abbrev-table "shit" "\\ast\\ast\\ast\\ast" nil :enable-function #'oo-in-org-mode-p)
(define-abbrev oo-text-abbrev-table "fuck" "****" nil)
(define-abbrev oo-text-abbrev-table "shit" "****" nil)
(define-abbrev oo-text-abbrev-table "figedo" "figured out" nil)
(define-abbrev oo-text-abbrev-table "figed" "figured" nil)
(define-abbrev oo-text-abbrev-table "ocmpletion" "completion" nil)
(define-abbrev oo-text-abbrev-table "achive" "achieve" nil)
(define-abbrev oo-text-abbrev-table "completin" "completion" nil)
(define-abbrev oo-text-abbrev-table "dabrev" "dabbrev" nil)
(define-abbrev oo-text-abbrev-table "additi" "addition" nil)
(define-abbrev oo-text-abbrev-table "ocmplexity" "complexity" nil)
(define-abbrev oo-text-abbrev-table "dhk" "" #'oo-expand-elisp-defhook :enable-function #'oo-in-elisp-code-p)
(define-abbrev oo-text-abbrev-table "lors" "" #'lorem-ipsum-insert-paragraphs)
(define-abbrev oo-text-abbrev-table "lorp" "" #'lorem-ipsum-insert-paragraphs)
(define-abbrev oo-text-abbrev-table "idb" "it would be" nil)
(define-abbrev oo-text-abbrev-table "imhth" "I may have to have" nil)
(define-abbrev oo-text-abbrev-table "ihd" "I had" nil)
(define-abbrev oo-text-abbrev-table "iwn" "it was not" nil)
(define-abbrev oo-text-abbrev-table "biwn" "but it was not" nil)
(define-abbrev oo-text-abbrev-table "enhancins" "enhancing" nil)
(define-abbrev oo-text-abbrev-table "oold" "old" nil)
(define-abbrev oo-text-abbrev-table "explicity" "explicitly" nil)
(define-abbrev oo-text-abbrev-table "afte" "after" nil)
(define-abbrev oo-text-abbrev-table "simplyfy" "simplify" nil)
(define-abbrev oo-text-abbrev-table "iin" "in" nil)
(define-abbrev oo-text-abbrev-table "ein" "in" nil)
(define-abbrev oo-text-abbrev-table "endeard" "endeared" nil)
(define-abbrev oo-text-abbrev-table "qite" "quite" nil)
(define-abbrev oo-text-abbrev-table "somet" "something" nil)
(define-abbrev oo-text-abbrev-table "boh" "both" nil)
(define-abbrev oo-text-abbrev-table "looing" "looking" nil)
(define-abbrev oo-text-abbrev-table "keypres" "keypress" nil)
(define-abbrev oo-text-abbrev-table "menat" "meant" nil)
(define-abbrev oo-text-abbrev-table "afit" "at first I thought" nil)
(define-abbrev oo-text-abbrev-table "positin" "position" nil)
(define-abbrev oo-text-abbrev-table "mappign" "mapping" nil)
(define-abbrev oo-text-abbrev-table "sate" "state" nil)
(define-abbrev oo-text-abbrev-table "stae" "state" nil)
(define-abbrev oo-text-abbrev-table "odnt" "do not" nil)
(define-abbrev oo-text-abbrev-table "frnakly" "frankly" nil)
(define-abbrev oo-text-abbrev-table "skels" "skeletons" nil)
(define-abbrev oo-text-abbrev-table "skel" "skeleton" nil)
(define-abbrev oo-text-abbrev-table "idnwtht" "I do not want to have to" nil)
(define-abbrev oo-text-abbrev-table "wy" "why" nil)
(define-abbrev oo-text-abbrev-table "o" "of" nil)
(define-abbrev oo-text-abbrev-table "thik" "think" nil)
(define-abbrev oo-text-abbrev-table "happed" "happened" nil)
(define-abbrev oo-text-abbrev-table "ihbl" "I had been looking" nil)
(define-abbrev oo-text-abbrev-table "bfsr" "but for some reason" nil)
(define-abbrev oo-text-abbrev-table "tsnba" "this should not be a" nil)
(define-abbrev oo-text-abbrev-table "winwiw" "which is not what I want" nil)
(define-abbrev oo-text-abbrev-table "inwiw" "is not what I want" nil)
(define-abbrev oo-text-abbrev-table "accepta" "acceptable" nil)
(define-abbrev oo-text-abbrev-table "iwi" "I will" nil)
(define-abbrev oo-text-abbrev-table "optin" "option" nil)
(define-abbrev oo-text-abbrev-table "ibdt" "it boils down to" nil)
(define-abbrev oo-text-abbrev-table "idnl" "I do not like" nil)
(define-abbrev oo-text-abbrev-table "idnfai" "I did not find anything immediate" nil)
(define-abbrev oo-text-abbrev-table "ona" "on a" nil)
(define-abbrev oo-text-abbrev-table "idnfa" "I did not find anything" nil)
(define-abbrev oo-text-abbrev-table "idnf" "I did not find" nil)
(define-abbrev oo-text-abbrev-table "iwto" "it was the only" nil)
(define-abbrev oo-text-abbrev-table "icft" "I could find that" nil)
(define-abbrev oo-text-abbrev-table "caviat" "caveat" nil)
;; (define-abbrev oo-text-abbrev-table "smd" "" #'oo-expand-save-match-data :enable-function #'oo-in-elisp-code-p)
;; (define-abbrev oo-text-abbrev-table "se" "" #'oo-expand-save-excursion :enable-function #'oo-in-elisp-code-p)
(define-abbrev oo-text-abbrev-table "wcb" "" #'oo-expand-elisp-with-current-buffer :enable-function #'oo-in-elisp-code-p)
(define-abbrev oo-text-abbrev-table "peerfect" "perfect" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "goten" "gotten" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "wirte" "write" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "userfacing" "user-facing" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "cutom" "custom" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "cutomizing" "customizing" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "alta" "a long time ago" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "wer" "were" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "previx" "prefix" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "iwh" "it would have" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "wda" "would have" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "writting" "writing" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "icf" "I could find" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "cicf" "closest I could find" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "closes" "closest" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "automa" "automatic" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "fftl" "for far too long" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "initializatoin" "initialization" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "alll" "all" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "intitialization" "initialization" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "determiend" "determined" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "bitt" "before-init-time" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "ait" "after-init-time" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "eit" "emacs-init-time" nil :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "happenning" "happening" nil)
(define-abbrev oo-text-abbrev-table "cmpute" "compute" nil)
(define-abbrev oo-text-abbrev-table "aways" "always" nil)
(define-abbrev oo-text-abbrev-table "initializaiton" "initialization" nil)
(define-abbrev oo-text-abbrev-table "isol" "isolate" nil)
(define-abbrev oo-text-abbrev-table "tig" "thing" nil)
(define-abbrev oo-text-abbrev-table "tigs" "things" nil)
(define-abbrev oo-text-abbrev-table "detial" "detail" nil)
(define-abbrev oo-text-abbrev-table "runing" "running" nil)
(define-abbrev oo-text-abbrev-table "wonrg" "wrong" nil)
(define-abbrev oo-text-abbrev-table "elasped" "elapsed" nil :enable-function #'oo-in-elisp-mode-p)
(define-abbrev oo-text-abbrev-table "aih" "after-init-hook" nil :enable-function #'oo-in-elisp-mode-p)
(define-abbrev oo-text-abbrev-table "esh" "emacs-startup-hook" nil :enable-function #'oo-in-elisp-mode-p)
(define-abbrev oo-text-abbrev-table "dvar" "" #'oo-expand-elisp-defvar :enable-function #'oo-in-elisp-code-p)
(define-abbrev oo-text-abbrev-table "funn" "" #'oo-expand-elisp-defun :enable-function #'oo-in-elisp-code-p)
(define-abbrev oo-text-abbrev-table "dfn" "" #'oo-expand-elisp-defun :enable-function #'oo-in-elisp-code-p)
(define-abbrev oo-text-abbrev-table "nn" "non-nil" nil)
(define-abbrev oo-text-abbrev-table "wit" "with" nil)
(define-abbrev oo-text-abbrev-table "hvar" "" #'oo-expand-variable-doc-link)
(define-abbrev oo-text-abbrev-table "vlk" "" #'oo-expand-variable-doc-link)
(define-abbrev oo-text-abbrev-table "snapshto" "snapshot" #'oo-expand-callable-doc-link)
(define-abbrev oo-text-abbrev-table "clk" "" #'oo-expand-callable-doc-link :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "flk" "" #'oo-expand-callable-doc-link :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "plk" "" #'oo-expand-package-link :enable-function #'oo-in-elisp-comment-p)
(define-abbrev oo-text-abbrev-table "plk" "" #'oo-expand-org-package-link :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "plink" "" #'oo-expand-org-package-link :enable-function #'oo-in-blog-post-p)
(define-abbrev oo-text-abbrev-table "durin" "during" nil)
(define-abbrev oo-text-abbrev-table "iwlt" "I would like to" nil)
(define-abbrev oo-text-abbrev-table "everty" "every" nil)
(define-abbrev oo-text-abbrev-table "rmb" "remember" nil)
(define-abbrev oo-text-abbrev-table "idnnt" "I do not need to" nil)
(define-abbrev oo-text-abbrev-table "ht" "have to" nil)
(define-abbrev oo-text-abbrev-table "scowered" "load-path" nil :enable-function #'oo-in-elisp-mode-p)
(define-abbrev oo-text-abbrev-table "lpath" "load-path" nil :enable-function #'oo-in-elisp-mode-p)
(define-abbrev oo-text-abbrev-table "loadpath" "load-path" nil :enable-function #'oo-in-elisp-mode-p)
(define-abbrev oo-text-abbrev-table "writng" "writing" nil)
(define-abbrev oo-text-abbrev-table "elip" "elisp" nil)
(define-abbrev oo-text-abbrev-table "gpm" "(goto-char (point-min))" nil :enable-function #'oo-in-elisp-mode-p)
(define-abbrev oo-text-abbrev-table "pm" "(point-min)" nil :enable-function #'oo-in-elisp-mode-p)
(define-abbrev oo-text-abbrev-table "pmin" "(point-min)" nil :enable-function #'oo-in-elisp-mode-p)
(define-abbrev oo-text-abbrev-table "ddir" "default-directory" nil :enable-function #'oo-in-elisp-mode-p)
(define-abbrev oo-text-abbrev-table "ilil" "I like it less" nil)
(define-abbrev oo-text-abbrev-table "ilim" "I like it more" nil)
(define-abbrev oo-text-abbrev-table "ili" "I like it" nil)
(define-abbrev oo-text-abbrev-table "wats" "what is" nil)
(define-abbrev oo-text-abbrev-table "clk" "" #'oo-expand-config-link :enable-function #'oo-in-org-mode-p)
(define-abbrev oo-text-abbrev-table "clink" "" #'oo-expand-config-link :enable-function #'oo-in-org-mode-p)
(define-abbrev oo-text-abbrev-table "rnni" "return non-nil if" nil :enable-function #'oo-in-elisp-comment-p)
(define-abbrev oo-text-abbrev-table "rnnw" "return non-nil when" nil :enable-function #'oo-in-elisp-comment-p)
(define-abbrev oo-text-abbrev-table "rtnnw" "return non-nil when" nil :enable-function #'oo-in-elisp-comment-p)
(define-abbrev oo-text-abbrev-table "partial" "apply-partially" nil :enable-function #'oo-in-elisp-mode-p)
(define-abbrev oo-text-abbrev-table "gpmax" "(goto-char (point-max))" nil :enable-function #'oo-in-elisp-mode-p)
(define-abbrev oo-text-abbrev-table "pman" "(point-max)" nil :enable-function #'oo-in-elisp-mode-p)
(define-abbrev oo-text-abbrev-table "pmax" "(point-max)" nil :enable-function #'oo-in-elisp-mode-p)
(define-abbrev oo-text-abbrev-table "pt" "(point)" nil :enable-function #'oo-in-elisp-mode-p)
(define-abbrev oo-text-abbrev-table "dnk" "did not know" nil)
(define-abbrev oo-text-abbrev-table "iws" "I will show" nil)
(define-abbrev oo-text-abbrev-table "idnkht" "I did not know how to" nil)
(define-abbrev oo-text-abbrev-table "idnk" "I did not know" nil)
(define-abbrev oo-text-abbrev-table "esse" "essentially" nil)
(define-abbrev oo-text-abbrev-table "kol" "kind of like" nil)
(define-abbrev oo-text-abbrev-table "cb" "can be" nil)
(define-abbrev oo-text-abbrev-table "icb" "it can be" nil)
(define-abbrev oo-text-abbrev-table "complel" "completely" nil)
(define-abbrev oo-text-abbrev-table "ihha" "I have had a" nil)
(define-abbrev oo-text-abbrev-table "incorp" "incorporate" nil)
(define-abbrev oo-text-abbrev-table "modifs" "modifications" nil)
(define-abbrev oo-text-abbrev-table "modif" "modification" nil)
(define-abbrev oo-text-abbrev-table "wofa" "without further ado" nil)
(define-abbrev oo-text-abbrev-table "smm" "so much more" nil)
(define-abbrev oo-text-abbrev-table "devs" "developers" nil)
(define-abbrev oo-text-abbrev-table "icsw" "I can see why" nil)
(define-abbrev oo-text-abbrev-table "inttco" "I need to take care of" nil)
(define-abbrev oo-text-abbrev-table "advyce" "advice" nil)
(define-abbrev oo-text-abbrev-table "imnk" "I might not know" nil)
(define-abbrev oo-text-abbrev-table "respo" "responsible" nil)
(define-abbrev oo-text-abbrev-table "ihni" "I have no idea" nil)
(define-abbrev oo-text-abbrev-table "ihniw" "I have no idea why" nil)
(define-abbrev oo-text-abbrev-table "yik" "yeah I know" nil)
(define-abbrev oo-text-abbrev-table "yea" "yeah" nil)
(define-abbrev oo-text-abbrev-table "ya" "yeah" nil)
(define-abbrev oo-text-abbrev-table "bir" "but I realized" nil)
(define-abbrev oo-text-abbrev-table "feeeling" "feling" nil)
(define-abbrev oo-text-abbrev-table "feeeling" "feeling" nil)
(define-abbrev oo-text-abbrev-table "weree" "we are" nil)
(define-abbrev oo-text-abbrev-table "lets" "let us" nil)
(define-abbrev oo-text-abbrev-table "tw" "this would" nil)
(define-abbrev oo-text-abbrev-table "imag" "imagine" nil)
(define-abbrev oo-text-abbrev-table "creatoin" "creation" nil)
(define-abbrev oo-text-abbrev-table "iwwt" "I will want to" nil)
(define-abbrev oo-text-abbrev-table "dird" "dired" nil)
(define-abbrev oo-text-abbrev-table "isic" "I suppose I could" nil)
(define-abbrev oo-text-abbrev-table "sring" "string" nil)
(define-abbrev oo-text-abbrev-table "chatgpt" "chatGPT" nil)
(define-abbrev oo-text-abbrev-table "accordi" "according" nil)
(define-abbrev oo-text-abbrev-table "acordi" "according" nil)
(define-abbrev oo-text-abbrev-table "acord" "accord" nil)
(define-abbrev oo-text-abbrev-table "accor" "according" nil)
(define-abbrev oo-text-abbrev-table "timesamp" "timestamp" nil)
(define-abbrev oo-text-abbrev-table "ultimatel" "ultimately" nil)
(define-abbrev oo-text-abbrev-table "ulti" "ultimate" nil)
(define-abbrev oo-text-abbrev-table "faltitt" "for a long time I thought that" nil)
(define-abbrev oo-text-abbrev-table "falt" "for a long time" nil)
(define-abbrev oo-text-abbrev-table "ustand" "understand" nil)
(define-abbrev oo-text-abbrev-table "figo" "figure out" nil)
(define-abbrev oo-text-abbrev-table "figur" "figure" nil)
(define-abbrev oo-text-abbrev-table "packags" "packages" nil)
(define-abbrev oo-text-abbrev-table "ftm" "for that matter" nil)
(define-abbrev oo-text-abbrev-table "pic" "picture" nil)
(define-abbrev oo-text-abbrev-table "eople" "people" nil)
(define-abbrev oo-text-abbrev-table "boilerp" "boilerplate" nil)
(define-abbrev oo-text-abbrev-table "riealized" "realized" nil)
(define-abbrev oo-text-abbrev-table "adivce" "advice" nil)
(define-abbrev oo-text-abbrev-table "afitt" "at first I thought that" nil)
(define-abbrev oo-text-abbrev-table "fortunatel" "fortunately" nil)
(define-abbrev oo-text-abbrev-table "fortu" "fortunate" nil)
(define-abbrev oo-text-abbrev-table "wll" "well" nil)
(define-abbrev oo-text-abbrev-table "wort" "wrote" nil)
(define-abbrev oo-text-abbrev-table "whoppig" "whopping" nil)
(define-abbrev oo-text-abbrev-table "requirem" "requirement" nil)
(define-abbrev oo-text-abbrev-table "restartd" "restarted" nil)
(define-abbrev oo-text-abbrev-table "meacs" "Emacs" nil)
(define-abbrev oo-text-abbrev-table "solutin" "solution" nil)
(define-abbrev oo-text-abbrev-table "instict" "instinct" nil)
(define-abbrev oo-text-abbrev-table "whenev" "whenever" nil)
(define-abbrev oo-text-abbrev-table "wene" "whenever" nil)
(define-abbrev oo-text-abbrev-table "cerain" "certain" nil)
(define-abbrev oo-text-abbrev-table "archivse" "archives" nil)
(define-abbrev oo-text-abbrev-table "pakgs" "packages" nil)
(define-abbrev oo-text-abbrev-table "solu" "solution" nil)
(define-abbrev oo-text-abbrev-table "tryi" "trying" nil)
(define-abbrev oo-text-abbrev-table "vers" "version" nil)
(define-abbrev oo-text-abbrev-table "happeni" "happening" nil)
(define-abbrev oo-text-abbrev-table "happe" "happen" nil)
(define-abbrev oo-text-abbrev-table "tsrc" "#+begin_src text \n#+end_src\n" nil :enable-function #'oo-in-org-mode-p)
(define-abbrev oo-text-abbrev-table "bq" "#+begin_quote \n#+end_quote\n" nil :enable-function #'oo-in-org-mode-p)
(define-abbrev oo-text-abbrev-table "esrc" "#+begin_src emacs-lisp\n#+end_src\n" nil :enable-function #'oo-in-org-mode-p)
(define-abbrev oo-text-abbrev-table "evt" "everything" nil)
(define-abbrev oo-text-abbrev-table "everythig" "everything" nil)
(define-abbrev oo-text-abbrev-table "tna" "to no avail" nil)
(define-abbrev oo-text-abbrev-table "ihht" "I have had to" nil)
(define-abbrev oo-text-abbrev-table "ntb" "need to be" nil)
(define-abbrev oo-text-abbrev-table "tntb" "that need to be" nil)
(define-abbrev oo-text-abbrev-table "wanring" "warning" nil)
(define-abbrev oo-text-abbrev-table "reproduca" "reproducibility" nil)
(define-abbrev oo-text-abbrev-table "xpand" "expand" nil)
(define-abbrev oo-text-abbrev-table "managem" "management" nil)
(define-abbrev oo-text-abbrev-table "idwtgt" "I do not want to go there" nil)
(define-abbrev oo-text-abbrev-table "goig" "going" nil)
(define-abbrev oo-text-abbrev-table "idwt" "I do not want to" nil)
(define-abbrev oo-text-abbrev-table "ngtdt" "not going to do this" nil)
(define-abbrev oo-text-abbrev-table "verson" "version" nil)
(define-abbrev oo-text-abbrev-table "ftft" "for the first time" nil)
(define-abbrev oo-text-abbrev-table "maye" "maybe" nil)
(define-abbrev oo-text-abbrev-table "concats" "concatenates" nil)
(define-abbrev oo-text-abbrev-table "becausee" "because" nil)
(define-abbrev oo-text-abbrev-table "wi" "which is" nil)
(define-abbrev oo-text-abbrev-table "iatt" "in addition to this" nil)
(define-abbrev oo-text-abbrev-table "elsip" "elisp" nil)
(define-abbrev oo-text-abbrev-table "siu" "should I use" nil)
(define-abbrev oo-text-abbrev-table "bottlenek" "bottleneck" nil)
(define-abbrev oo-text-abbrev-table "importa" "important" nil)
(define-abbrev oo-text-abbrev-table "initi" "initialize" nil)
(define-abbrev oo-text-abbrev-table "majaor" "major" nil)
(define-abbrev oo-text-abbrev-table "rese" "research" nil)
(define-abbrev oo-text-abbrev-table "authro" "author" nil)
(define-abbrev oo-text-abbrev-table "annoyi" "annoying" nil)
(define-abbrev oo-text-abbrev-table "oepn" "open" nil)
(define-abbrev oo-text-abbrev-table "ocnfigg" "configuration" nil)
(define-abbrev oo-text-abbrev-table "udring" "during" nil)
(define-abbrev oo-text-abbrev-table "vv" "vice versa" nil)
(define-abbrev oo-text-abbrev-table "batt" "battery" nil)
(define-abbrev oo-text-abbrev-table "uting" "using" nil)
(define-abbrev oo-text-abbrev-table "specificatoin" "specification" nil)
(define-abbrev oo-text-abbrev-table "mng" "manage" nil)
(define-abbrev oo-text-abbrev-table "wdntht" "would not have to" nil)
(define-abbrev oo-text-abbrev-table "remvoes" "removes" nil)
(define-abbrev oo-text-abbrev-table "shamell" "shamelessly" nil)
(define-abbrev oo-text-abbrev-table "shamel" "shameless" nil)
(define-abbrev oo-text-abbrev-table "metad" "metadata" nil)
(define-abbrev oo-text-abbrev-table "everyhing" "everything" nil)
(define-abbrev oo-text-abbrev-table "eacs" "Emacs" nil)
(define-abbrev oo-text-abbrev-table "relyig" "relying" nil)
(define-abbrev oo-text-abbrev-table "ihnba" "I have not been able to" nil)
(define-abbrev oo-text-abbrev-table "oot" "one of the" nil)
(define-abbrev oo-text-abbrev-table "oneof" "one of" nil)
(define-abbrev oo-text-abbrev-table "emc" "Emacs configuration" nil)
(define-abbrev oo-text-abbrev-table "iht" "I have to" nil)
(define-abbrev oo-text-abbrev-table "fowtd" "figure out what to do" nil)
(define-abbrev oo-text-abbrev-table "figg" "figure" nil)
(define-abbrev oo-text-abbrev-table "testring" "testing" nil)
(define-abbrev oo-text-abbrev-table "recl" "recently" nil)
(define-abbrev oo-text-abbrev-table "emas" "Emacs" nil)
(define-abbrev oo-text-abbrev-table "pacmann" "package manager" nil)
(define-abbrev oo-text-abbrev-table "poin" "point" nil)
(define-abbrev oo-text-abbrev-table "ammbrevs" "abbrevs" nil)
(define-abbrev oo-text-abbrev-table "optinally" "optionally" nil)
(define-abbrev oo-text-abbrev-table "pagkes" "packages" nil)
(define-abbrev oo-text-abbrev-table "recommendd" "recommendation" nil)
(define-abbrev oo-text-abbrev-table "recomn" "recommendation" nil)
(define-abbrev oo-text-abbrev-table "recom" "recommend" nil)
(define-abbrev oo-text-abbrev-table "recomm" "recommend" nil)
(define-abbrev oo-text-abbrev-table "icdju" "I could just use" nil)
(define-abbrev oo-text-abbrev-table "iwitb" "I want it to be" nil)
(define-abbrev oo-text-abbrev-table "iwditb" "I wanted it to be" nil)
(define-abbrev oo-text-abbrev-table "syncl" "synchronously" nil)
(define-abbrev oo-text-abbrev-table "emacs" "Emacs" nil)
(define-abbrev oo-text-abbrev-table "critisized" "criticized" nil)
(define-abbrev oo-text-abbrev-table "asynch" "asynchronously" nil)
(define-abbrev oo-text-abbrev-table "asyncc" "asynchronously" nil)
(define-abbrev oo-text-abbrev-table "insall" "install" nil)
(define-abbrev oo-text-abbrev-table "insalls" "installs" nil)
(define-abbrev oo-text-abbrev-table "eivl" "evil" nil)
(define-abbrev oo-text-abbrev-table "biding" "binding" nil)
(define-abbrev oo-text-abbrev-table "abrev" "abbrev" nil)
(define-abbrev oo-text-abbrev-table "aform" "aforementioned" nil)
(define-abbrev oo-text-abbrev-table "aforemenioned" "aforementioned" nil)
(define-abbrev oo-text-abbrev-table "optimi" "optimization" nil)
(define-abbrev oo-text-abbrev-table "itsb" "it is because" nil)
(define-abbrev oo-text-abbrev-table "susp" "suspect" nil)
(define-abbrev oo-text-abbrev-table "ness" "necessary" nil)
(define-abbrev oo-text-abbrev-table "hnadle" "handle" nil)
(define-abbrev oo-text-abbrev-table "anonl" "anonymous lambda" nil)
(define-abbrev oo-text-abbrev-table "toh" "to have" nil)
(define-abbrev oo-text-abbrev-table "qute" "quote" nil)
(define-abbrev oo-text-abbrev-table "fle" "file" nil)
(define-abbrev oo-text-abbrev-table "gc" "garbage collection" nil)
(define-abbrev oo-text-abbrev-table "comiler" "compiler" nil)
(define-abbrev oo-text-abbrev-table "suceded" "succeeded" nil)
(define-abbrev oo-text-abbrev-table "genl" "generally" nil)
(define-abbrev oo-text-abbrev-table "nie" "nice" nil)
(define-abbrev oo-text-abbrev-table "wud" "would" nil)
(define-abbrev oo-text-abbrev-table "preff" "preference" nil)
(define-abbrev oo-text-abbrev-table "pref" "preference" nil)
(define-abbrev oo-text-abbrev-table "usin" "using" nil)
(define-abbrev oo-text-abbrev-table "numberd" "numbered" nil)
(define-abbrev oo-text-abbrev-table "measore" "measure" nil)
(define-abbrev oo-text-abbrev-table "loadig" "loading" nil)
(define-abbrev oo-text-abbrev-table "loding" "loading" nil)
(define-abbrev oo-text-abbrev-table "brnach" "branch" nil)
(define-abbrev oo-text-abbrev-table "initization" "initialization" nil)
(define-abbrev oo-text-abbrev-table "somone" "someone" nil)
(define-abbrev oo-text-abbrev-table "rmed" "removed" nil)
(define-abbrev oo-text-abbrev-table "investiage" "investigate" nil)
(define-abbrev oo-text-abbrev-table "shdntb" "should not be" nil)
(define-abbrev oo-text-abbrev-table "preciesely" "precisely" nil)
(define-abbrev oo-text-abbrev-table "pretyt" "pretty" nil)
(define-abbrev oo-text-abbrev-table "tb" "to be" nil)
(define-abbrev oo-text-abbrev-table "aro" "around" nil)
(define-abbrev oo-text-abbrev-table "tryig" "trying" nil)
(define-abbrev oo-text-abbrev-table "afer" "after" nil)
(define-abbrev oo-text-abbrev-table "prety" "pretty" nil)
(define-abbrev oo-text-abbrev-table "brnaches" "branches" nil)
(define-abbrev oo-text-abbrev-table "quet" "quiet" nil)
(define-abbrev oo-text-abbrev-table "quetly" "quietly" nil)
(define-abbrev oo-text-abbrev-table "ut" "but" nil)
(define-abbrev oo-text-abbrev-table "fies" "files" nil)
(define-abbrev oo-text-abbrev-table "definiteively" "definitively" nil)
(define-abbrev oo-text-abbrev-table "nad" "and" nil)
(define-abbrev oo-text-abbrev-table "elfeeed" "elfeed" nil)
(define-abbrev oo-text-abbrev-table "elfed" "elfeed" nil)
(define-abbrev oo-text-abbrev-table "destop" "desktop" nil)
(define-abbrev oo-text-abbrev-table "rcentf" "recentf" nil)
(define-abbrev oo-text-abbrev-table "duplicae" "duplicate" nil)
(define-abbrev oo-text-abbrev-table "broser" "browser" nil)
(define-abbrev oo-text-abbrev-table "diable" "disable" nil)
(define-abbrev oo-text-abbrev-table "colro" "color" nil)
(define-abbrev oo-text-abbrev-table "anwer" "answer" nil)
(define-abbrev oo-text-abbrev-table "resitered" "registered" nil)
(define-abbrev oo-text-abbrev-table "expasions" "expansions" nil)
(define-abbrev oo-text-abbrev-table "rgister" "register" nil)
(define-abbrev oo-text-abbrev-table "api" "API" nil)
(define-abbrev oo-text-abbrev-table "tnail" "thumbnail" nil)
(define-abbrev oo-text-abbrev-table "kbdd" "key binding" nil)
(define-abbrev oo-text-abbrev-table "emcs" "Emacs" nil)
(define-abbrev oo-text-abbrev-table "settingn" "setting" nil)
(define-abbrev oo-text-abbrev-table "punctionation" "punctuation" nil)
(define-abbrev oo-text-abbrev-table "cliche" "cliché" nil)
(define-abbrev oo-text-abbrev-table "naive" "naïve" nil)
(define-abbrev oo-text-abbrev-table "resume" "résumé" nil)
(define-abbrev oo-text-abbrev-table "cafe" "café" nil)
(define-abbrev oo-text-abbrev-table "fiance" "fiancé" nil)
(define-abbrev oo-text-abbrev-table "eclair" "éclair" nil)
(define-abbrev oo-text-abbrev-table "facade" "façade" nil)
(define-abbrev oo-text-abbrev-table "tete" "tête" nil)
(define-abbrev oo-text-abbrev-table "voila" "voilà" nil)
(define-abbrev oo-text-abbrev-table "gotto" "have got to" nil)
(define-abbrev oo-text-abbrev-table "foont" "font" nil)
(define-abbrev oo-text-abbrev-table "wen" "when" nil)
(define-abbrev oo-text-abbrev-table "htan" "than" nil)
(define-abbrev oo-text-abbrev-table "firt" "first" nil)
(define-abbrev oo-text-abbrev-table "neds" "ends" nil)
(define-abbrev oo-text-abbrev-table "basd" "based" nil)
(define-abbrev oo-text-abbrev-table "reff" "reference" nil)
(define-abbrev oo-text-abbrev-table "welll" "we will" nil)
(define-abbrev oo-text-abbrev-table "dml" "doom-modeline" nil)
(define-abbrev oo-text-abbrev-table "pickture" "picture" nil)
(define-abbrev oo-text-abbrev-table "bco" "because of" nil)
(define-abbrev oo-text-abbrev-table "swithc" "switch" nil)
(define-abbrev oo-text-abbrev-table "swith" "switch" nil)
(define-abbrev oo-text-abbrev-table "tings" "things" nil)
(define-abbrev oo-text-abbrev-table "sshot" "screenshot" nil)
(define-abbrev oo-text-abbrev-table "frorm" "from" nil)
(define-abbrev oo-text-abbrev-table "deveotes" "devotes" nil)
(define-abbrev oo-text-abbrev-table "bein" "being" nil)
(define-abbrev oo-text-abbrev-table "idn" "I do not" nil)
(define-abbrev oo-text-abbrev-table "ikih" "I know I have" nil)
(define-abbrev oo-text-abbrev-table "figing" "figuring out" nil)
(define-abbrev oo-text-abbrev-table "figging" "figuring out" nil)
(define-abbrev oo-text-abbrev-table "variaous" "various" nil)
(define-abbrev oo-text-abbrev-table "wile" "while" nil)
(define-abbrev oo-text-abbrev-table "eant" "meant" nil)
(define-abbrev oo-text-abbrev-table "levl" "level" nil)
(define-abbrev oo-text-abbrev-table "checkig" "checking" nil)
(define-abbrev oo-text-abbrev-table "priv" "private" nil)
(define-abbrev oo-text-abbrev-table "accout" "account" nil)
(define-abbrev oo-text-abbrev-table "hae" "have" nil)
(define-abbrev oo-text-abbrev-table "iwwti" "I wonder whether there is" nil)
(define-abbrev oo-text-abbrev-table "iww" "I wonder whether" nil)
(define-abbrev oo-text-abbrev-table "hd" "harddrive" nil)
(define-abbrev oo-text-abbrev-table "hardd" "harddrive" nil)
(define-abbrev oo-text-abbrev-table "tere" "there" nil)
(define-abbrev oo-text-abbrev-table "cofnigure" "configure" nil)
(define-abbrev oo-text-abbrev-table "autom" "automatic" nil)
(define-abbrev oo-text-abbrev-table "autol" "automatically" nil)
(define-abbrev oo-text-abbrev-table "suer" "user" nil)
(define-abbrev oo-text-abbrev-table "modeline" "modeline" nil)
(define-abbrev oo-text-abbrev-table "hwen" "when" nil)
(define-abbrev oo-text-abbrev-table "imnsw" "I am not sure whether" nil)
(define-abbrev oo-text-abbrev-table "sates" "states" nil)
(define-abbrev oo-text-abbrev-table "ver" "version" nil)
(define-abbrev oo-text-abbrev-table "projet" "project" nil)
(define-abbrev oo-text-abbrev-table "projj" "project" nil)
(define-abbrev oo-text-abbrev-table "infoo" "information" nil)
(define-abbrev oo-text-abbrev-table "extenral" "external" nil)
(define-abbrev oo-text-abbrev-table "extenr" "external" nil)
(define-abbrev oo-text-abbrev-table "dosnt" "does not" nil)
(define-abbrev oo-text-abbrev-table "sligh" "slight" nil)
(define-abbrev oo-text-abbrev-table "mls" "mode lines" nil)
(define-abbrev oo-text-abbrev-table "autoo" "automatically" nil)
(define-abbrev oo-text-abbrev-table "funions" "functions" nil)
(define-abbrev oo-text-abbrev-table "evall" "evaluate" nil)
(define-abbrev oo-text-abbrev-table "configu" "configuration" nil)
(define-abbrev oo-text-abbrev-table "confgi" "config" nil)
(define-abbrev oo-text-abbrev-table "hwever" "pertaining" nil)
(define-abbrev oo-text-abbrev-table "ertaining" "pertaining" nil)
(define-abbrev oo-text-abbrev-table "consideer" "consider" nil)
(define-abbrev oo-text-abbrev-table "nece" "necessary" nil)
(define-abbrev oo-text-abbrev-table "improvmeent" "improvement" nil)
(define-abbrev oo-text-abbrev-table "hink" "think" nil)
(define-abbrev oo-text-abbrev-table "mentoned" "mentioned" nil)
(define-abbrev oo-text-abbrev-table "whove" "who have" nil)
(define-abbrev oo-text-abbrev-table "determening" "determining" nil)
(define-abbrev oo-text-abbrev-table "afteir" "after" nil)
(define-abbrev oo-text-abbrev-table "compilor" "compiler" nil)
(define-abbrev oo-text-abbrev-table "righthand" "right-hand" nil)
(define-abbrev oo-text-abbrev-table "lefthand" "left-hand" nil)
(define-abbrev oo-text-abbrev-table "lhs" "left-hand side" nil)
(define-abbrev oo-text-abbrev-table "rhs" "right-hand side" nil)
(define-abbrev oo-text-abbrev-table "tuf" "tough" nil)
(define-abbrev oo-text-abbrev-table "decideing" "deciding" nil)
(define-abbrev oo-text-abbrev-table "customizeability" "customizability" nil)
(define-abbrev oo-text-abbrev-table "reproducability" "reproducibility" nil)
(define-abbrev oo-text-abbrev-table "reproduceability" "reproducibility" nil)
(define-abbrev oo-text-abbrev-table "alteratives" "alternatives" nil)
(define-abbrev oo-text-abbrev-table "takign" "taking" nil)
(define-abbrev oo-text-abbrev-table "encript" "encrypt" nil)
(define-abbrev oo-text-abbrev-table "encrypton" "encryption" nil)
(define-abbrev oo-text-abbrev-table "encripton" "encryption" nil)
(define-abbrev oo-text-abbrev-table "encription" "encryption" nil)
(define-abbrev oo-text-abbrev-table "nl" "newline" nil)
(define-abbrev oo-text-abbrev-table "eno" "enough" nil)
(define-abbrev oo-text-abbrev-table "enugh" "enough" nil)
(define-abbrev oo-text-abbrev-table "enuf" "enough" nil)
(define-abbrev oo-text-abbrev-table "reming" "removing" nil)
(define-abbrev oo-text-abbrev-table "sentense" "sentence" nil)
(define-abbrev oo-text-abbrev-table "frist" "first" nil)
(define-abbrev oo-text-abbrev-table "mv" "move" nil)
(define-abbrev oo-text-abbrev-table "retrun" "return" nil)
(define-abbrev oo-text-abbrev-table "voer" "over" nil)
(define-abbrev oo-text-abbrev-table "iabt" "I am beginning to think that" nil)
(define-abbrev oo-text-abbrev-table "tweek" "tweak" nil)
(define-abbrev oo-text-abbrev-table "teak" "tweak" nil)
(define-abbrev oo-text-abbrev-table "seet" "set" nil)
(define-abbrev oo-text-abbrev-table "doen" "done" nil)
(define-abbrev oo-text-abbrev-table "av" "available" nil)
(define-abbrev oo-text-abbrev-table "mans" "means" nil)
(define-abbrev oo-text-abbrev-table "ns" "not sure" nil)
(define-abbrev oo-text-abbrev-table "inf" "in fact, " nil)
(define-abbrev oo-text-abbrev-table "wnev" "whenever" nil)
(define-abbrev oo-text-abbrev-table "nev" "never" nil)
(define-abbrev oo-text-abbrev-table "wenev" "whenever" nil)
(define-abbrev oo-text-abbrev-table "emplate" "template" nil)
(define-abbrev oo-text-abbrev-table "mult" "multiple" nil)
(define-abbrev oo-text-abbrev-table "multipul" "multiple" nil)
(define-abbrev oo-text-abbrev-table "har" "character" nil)
(define-abbrev oo-text-abbrev-table "defi" "definitely" nil)
(define-abbrev oo-text-abbrev-table "woudl" "would" nil)
(define-abbrev oo-text-abbrev-table "awk" "awkward" nil)
(define-abbrev oo-text-abbrev-table "akw" "awkward" nil)
(define-abbrev oo-text-abbrev-table "aiws" "as I was saying" nil)
(define-abbrev oo-text-abbrev-table "imns" "I am not sure" nil)
(define-abbrev oo-text-abbrev-table "et" "even then" nil)
(define-abbrev oo-text-abbrev-table "iiwt" "if I want to" nil)
(define-abbrev oo-text-abbrev-table "itisj" "I think I should just" nil)
(define-abbrev oo-text-abbrev-table "isj" "I should just" nil)
(define-abbrev oo-text-abbrev-table "wereas" "whereas" nil)
(define-abbrev oo-text-abbrev-table "conig" "config" nil)
(define-abbrev oo-text-abbrev-table "ama" "add more abbrevs" nil)
(define-abbrev oo-text-abbrev-table "abbreviaion" "abbreviation" nil)
(define-abbrev oo-text-abbrev-table "abbs" "abbrevs" nil)
(define-abbrev oo-text-abbrev-table "abb" "abbreviation" nil)
(define-abbrev oo-text-abbrev-table "ar" "around" nil)
(define-abbrev oo-text-abbrev-table "elm" "emacs-lisp-mode" nil)
(define-abbrev oo-text-abbrev-table "soemthing" "something" nil)
(define-abbrev oo-text-abbrev-table "smt" "something" nil)
(define-abbrev oo-text-abbrev-table "udpate" "update" nil)
(define-abbrev oo-text-abbrev-table "escpae" "escape" nil)
(define-abbrev oo-text-abbrev-table "exi" "excited" nil)
(define-abbrev oo-text-abbrev-table "aling" "align" nil)
(define-abbrev oo-text-abbrev-table "setigs" "settings" nil)
(define-abbrev oo-text-abbrev-table "setig" "setting" nil)
(define-abbrev oo-text-abbrev-table "setin" "setting" nil)
(define-abbrev oo-text-abbrev-table "settins" "settings" nil)
(define-abbrev oo-text-abbrev-table "setins" "settings" nil)
(define-abbrev oo-text-abbrev-table "stuf" "stuff" nil)
(define-abbrev oo-text-abbrev-table "dnms" "does not make sense" nil)
(define-abbrev oo-text-abbrev-table "str" "string" nil)
(define-abbrev oo-text-abbrev-table "isd" "I should" nil)
(define-abbrev oo-text-abbrev-table "ish" "I should" nil)
(define-abbrev oo-text-abbrev-table "prov" "provide" nil)
(define-abbrev oo-text-abbrev-table "lib" "library" nil)
(define-abbrev oo-text-abbrev-table "whe" "whether" nil)
(define-abbrev oo-text-abbrev-table "gona" "going to" nil)
(define-abbrev oo-text-abbrev-table "thig" "thing" nil)
(define-abbrev oo-text-abbrev-table "dels" "deletes" nil)
(define-abbrev oo-text-abbrev-table "envyronmen" "environment" nil)
(define-abbrev oo-text-abbrev-table "directries" "directories" nil)
(define-abbrev oo-text-abbrev-table "qt" "qutebrowser" nil)
(define-abbrev oo-text-abbrev-table "qtbrowser" "qutebrowser" nil)
(define-abbrev oo-text-abbrev-table "redit" "reddit" nil)
(define-abbrev oo-text-abbrev-table "insead" "instead" nil)
(define-abbrev oo-text-abbrev-table "environement" "environment" nil)
(define-abbrev oo-text-abbrev-table "inputing" "inputting" nil)
(define-abbrev oo-text-abbrev-table "aot" "as opposed to" nil)
(define-abbrev oo-text-abbrev-table "iatb" "I am thinking about" nil)
(define-abbrev oo-text-abbrev-table "bigg" "biggest" nil)
(define-abbrev oo-text-abbrev-table "consi" "consistent" nil)
(define-abbrev oo-text-abbrev-table "supprot" "support" nil)
(define-abbrev oo-text-abbrev-table "expressi" "expression" nil)
(define-abbrev oo-text-abbrev-table "miniaml" "minimal" nil)
(define-abbrev oo-text-abbrev-table "mateiral" "material" nil)
(define-abbrev oo-text-abbrev-table "cdnt" "could not" nil)
(define-abbrev oo-text-abbrev-table "tsa" "there is any" nil)
(define-abbrev oo-text-abbrev-table "spe" "specifically" nil)
(define-abbrev oo-text-abbrev-table "speci" "specifically" nil)
(define-abbrev oo-text-abbrev-table "exo" "example of" nil)
(define-abbrev oo-text-abbrev-table "inadv" "inadvertently" nil)
(define-abbrev oo-text-abbrev-table "immediatel" "immediately" nil)
(define-abbrev oo-text-abbrev-table "bol" "beginning of the line" nil)
(define-abbrev oo-text-abbrev-table "cts" "check to see" nil)
(define-abbrev oo-text-abbrev-table "cheks" "checks" nil)
(define-abbrev oo-text-abbrev-table "ali" "alias" nil)
(define-abbrev oo-text-abbrev-table "unk" "unknown" nil)
(define-abbrev oo-text-abbrev-table "y" "by" nil)
(define-abbrev oo-text-abbrev-table "tcb" "this could be" nil)
(define-abbrev oo-text-abbrev-table "alte" "alternative" nil)
(define-abbrev oo-text-abbrev-table "wikip" "wikipedia" nil)
(define-abbrev oo-text-abbrev-table "incon" "inconsistent" nil)
(define-abbrev oo-text-abbrev-table "defs" "definitions" nil)
(define-abbrev oo-text-abbrev-table "dnw" "does not work" nil)
(define-abbrev oo-text-abbrev-table "htdw" "has to do with" nil)
(define-abbrev oo-text-abbrev-table "espl" "especially" nil)
(define-abbrev oo-text-abbrev-table "exc" "except" nil)
(define-abbrev oo-text-abbrev-table "fils" "files" nil)
(define-abbrev oo-text-abbrev-table "doesnth" "does not have" nil)
(define-abbrev oo-text-abbrev-table "fiels" "files" nil)
(define-abbrev oo-text-abbrev-table "backw" "backward" nil)
(define-abbrev oo-text-abbrev-table "forw" "forward" nil)
(define-abbrev oo-text-abbrev-table "acept" "accept" nil)
(define-abbrev oo-text-abbrev-table "swpawn" "spawn" nil)
(define-abbrev oo-text-abbrev-table "nother" "another" nil)
(define-abbrev oo-text-abbrev-table "awesoe" "awesome" nil)
(define-abbrev oo-text-abbrev-table "iad" "in addition" nil)
(define-abbrev oo-text-abbrev-table "rearange" "rearrange" nil)
(define-abbrev oo-text-abbrev-table "bett" "better" nil)
(define-abbrev oo-text-abbrev-table "dsn" "does not" nil)
(define-abbrev oo-text-abbrev-table "fsr" "for some reason" nil)
(define-abbrev oo-text-abbrev-table "propogate" "propagate" nil)
(define-abbrev oo-text-abbrev-table "pakcage" "package" nil)
(define-abbrev oo-text-abbrev-table "pakcages" "packages" nil)
(define-abbrev oo-text-abbrev-table "motn" "more often than not" nil)
(define-abbrev oo-text-abbrev-table "itc" "in that case" nil)
(define-abbrev oo-text-abbrev-table "probl" "problem" nil)
(define-abbrev oo-text-abbrev-table "dered" "considered" nil)
;;; provide
(provide '910-text-abbrevs)
;;; 910-text-abbrevs.el ends here
