;;; 911-text-abbrevs.el --- TODO: add commentary -*- lexical-binding: t; -*-
;;
;; Copyright (c) 2024 Free Software Foundation, Inc.
;;
;; Author: Luis Henriquez-Perez <luis@luishp.xyz>
;; Homepage: https://github.com/Luis-Henriquez-Perez/dotfiles/
;;
;; This file is not part of GNU Emacs.
;;
;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License as
;; published by the Free Software Foundation, either version 3 of the
;; License, or (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful, but
;; WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
;; General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program. If not, see <http://www.gnu.org/licenses/>.
;;
;;; Commentary:
;;
;; TODO: add commentary
;;
;;; Code:
(require '050-base)
(require 'abbrev)

(define-abbrev-table 'oo-text-abbrev-table
  '(("theone" "the one")
    ("iwc" "in which case")
    ("ben" "been")
    ("praticular" "particular")
    ("faw" "for a while")
    ("highl" "highlight")
    ("whi" "while")
    ("eh" "the")
    ("appa" "apparent")
    ("yr" "year")
    ("xp" "experience")
    ("implem" "implementation")
    ("itme" "item")
    ("io" "instead of")
    ("menaul" "manual")
    ("entr" "entry")
    ("das" "days")
    ("teime" "time")
    ("wast" "waste")
    ("taks" "tasks")
    ("imple" "implement")
    ("impltt" "implementation")
    ("divied" "divided")
    ("idkw" "I do not know what")
    ("ambig" "ambiguous")
    ("hsi" "his")
    ("stats" "statistics")
    ("defalt" "default")
    ("inter" "interesting")
    ("idnt" "I do not")
    ("david" "David")
    ("workflwo" "workflow")
    ("amnt" "amount")
    ("gtd" "GTD")
    ("whatd" "what would")
    ("watd" "what would")
    ("aot" "any of these")
    ("imn" "I am not")
    ("honl" "honestly")
    ("signi" "signify")
    ("deadlne" "deadline")
    ("aranged" "arranged")
    ("bs" "bullshit")
    ("alr" "already")
    ("exaustion" "exhaustion")
    ("thare" "that are")
    ("cmp" "compare")
    ("tf" "therefore")
    ("dren" "children")
    ("aee" "all else equal")
    ("keyw" "keyword")
    ("deln" "deletion")
    ("wndow" "window")
    ("idnht" "I did not have to")
    ("win" "window")
    ("anyt" "anything")
    ("hls" "headlines")
    ("hgs" "headings")
    ("hg" "heading")
    ("hl" "headline")
    ("ahs" "has")
    ("iwb" "it would be")
    ("sba" "should be a")
    ("sb" "should be")
    ("iwrh" "I would rather have")
    ("iwd" "I would")
    ("iw" "I was")
    ("consisten" "consistent")
    ("alphz" "alphabetize")
    ("menti" "mention")
    ("creeate" "create")
    ("nvm" "nevermind")
    ("ve" "very")
    ("higs" "highest")
    ("overr" "override")
    ("creaed" "created")
    ("strat" "strategy")
    ("adi" "aid")
    ("deadlie" "deadline")
    ("comm" "comment")
    ("comms" "comments")
    ("akwardly" "awkwardly")
    ("displaed" "displayed")
    ("crual" "crucial")
    ("chilren" "children")
    ("ia" "I am")
    ("twt" "those were the")
    ("oom" "one or more")
    ("wnht" "would not have to")
    ("wdnt" "would not")
    ("itmes" "items")
    ("ocntrol" "control")
    ("thoro" "thorough")
    ("itt" "I thought that")
    ("prio" "priority")
    ("genda" "agenda")
    ("bottomost" "bottommost")
    ("behav" "behavior")
    ("thnk" "think")
    ("digesteable" "digestible")
    ("subtaks" "subtasks")
    ("themselvs" "themselves")
    ("tasts" "tasks")
    ("todos" "TODOs")
    ("todo" "TODO")
    ("gs" "generally speaking")
    ("aka" "also known as")
    ("convet" "convenient")
    ("inevl" "inevitably")
    ("woth" "worth")
    ("hasnt" "has not")
    ("arbil" "arbitrarily")
    ("vari" "various")
    ("keywrods" "keywords")
    ("acountable" "accountable")
    ("propspect" "prospect")
    ("aagm" "at any given moment")
    ("odl" "old")
    ("headliens" "headlines")
    ("props" "properties")
    ("headli" "headline")
    ("hli" "headline")
    ("fnd" "find")
    ("diffi" "difficult")
    ("thigs" "things")
    ("idds" "IDs")
    ("someting" "something")
    ("parti" "particular")
    ("sh" "should have")
    ("desb" "describe")
    ("efficl" "efficiently")
    ("rath" "rather")
    ("experd" "experienced")
    ("exper" "experience")
    ("hol" "honestly")
    ("hon" "honest")
    ("ofo" "off of")
    ("juust" "just")
    ("atst" "at the same time")
    ("abbrevx" "abbrevs")
    ("oos" "out of scope")
    ("ano" "another")
    ("woud" "would")
    ("hty" "they")
    ("theve" "they have")
    ("theyve" "they have")
    ("lok" "look")
    ("implemed" "implemented")
    ("evals" "evaluates")
    ("ih" "I have")
    ("implementd" "implemented")
    ("esear" "easier")
    ("ezer" "easier")
    ("ezr" "easier")
    ("persp" "perspective")
    ("seve" "several")
    ("sence" "sense")
    ("reffed" "referenced")
    ("menual" "manual")
    ("pakckage" "package")
    ("relize" "realize")
    ("relized" "realized")
    ("templat" "template")
    ("templ" "template")
    ("unfort" "unfortunately")
    ("floabn" "for lack of a better name")
    ("thots" "thoughts")
    ("mb" "maybe")
    ("ikt" "I know that")
    ("decis" "decision")
    ("atp" "at that point")
    ("somethign" "something")
    ("evalate" "evaluate")
    ("forst" "first")
    ("itk" "I think")
    ("loc" "location")
    ("al" "at least")
    ("tresti" "intresting")
    ("ntax" "syntax")
    ("intres" "interest")
    ("taged" "tagged")
    ("remed" "removed")
    ("neces" "necessary")
    ("nec" "necessary")
    ("kws" "keywords")
    ("kw" "keyword")
    ("mulitple" "multiple")
    ("iiee" "It is easy enough")
    ("mab" "maybe")
    ("automl" "automatically")
    ("auotml" "automatically")
    ("enalbed" "enabled")
    ("unples" "unpleasant")
    ("hk" "hook")
    ("toda" "today")
    ("aloading" "autoloading")
    ("shoud" "should")
    ("dong" "doing")
    ("wordd" "word")
    ("loadded" "loaded")
    ("img" "image")
    ("pupular" "popular")
    ("strait" "straight")
    ("srait" "straight")
    ("stait" "straight")
    ("staight" "straight")
    ("staightfforward" "straightforward")
    ("staightf" "staightforward")
    ("straightfforward" "straightforward")
    ("straightf" "staightforward")
    ("descrip" "description")
    ("ifle" "file")
    ("prefxi" "prefix")
    ("reedame" "README")
    ("reeame" "README")
    ("reame" "README")
    ("nuo" "number of")
    ("noo" "number of")
    ("iftt" "I feel that there")
    ("ift" "I feel that")
    ("ihaft" "I have a feeling that")
    ("dnnt" "do not need to")
    ("aw" "as well")
    ("iaww" "I am wondering whether")
    ("authr" "author")
    ("alis" "alias")
    ("tij" "this is just")
    ("bookmakr" "bookmark")
    ("nonlive" "non-live")
    ("asso" "associate")
    ("assod" "associated")
    ("bufs" "buffers")
    ("bifn" "but if not")
    ("ifn" "if not")
    ("makr" "mark")
    ("bufferes" "buffers")
    ("advan" "advantage")
    ("bi" "built-in")
    ("intli" "I need to look into")
    ("buf" "buffer")
    ("iti" "it is")
    ("isb" "it should be")
    ("workspac" "workspace")
    ("succintly" "succinctly")
    ("bos" "beginning of a sentence")
    ("siha" "should I have a")
    ("renable" "re-enable")
    ("reenable" "re-enable")
    ("gener" "general")
    ("visi" "visible")
    ("condi" "condition")
    ("qol" "quality of life")
    ("asumes" "assumes")
    ("uf" "of")
    ("alw" "always")
    ("sorta" "sort of")
    ("smaple" "sample")
    ("spefic" "specific")
    ("specifi" "specific")
    ("cre" "create")
    ("ww" "wanted")
    ("fgc" "foreground color")
    ("bgc" "background color")
    ("fireground" "foreground")
    ("fgs" "foregrounds")
    ("fg" "foreground")
    ("bgs" "backgrounds")
    ("lized" "realized")
    ("isnbt" "it should not be the")
    ("isnb" "it should not be")
    ("bg" "background")
    ("rigght" "right")
    ("prot" "protesilaos")
    ("prots" "protesilaos's")
    ("momnb" "may or may not be")
    ("ivht" "I have had the")
    ("ivh" "I have had")
    ("libs" "libraries")
                                        ;that wether is actually a word meaning "a castrated male sheep or goat"
                                        ;I do not expect to be using this word at all. I expect 99% of the tim nil :enable-function oo-enable-text-abbrev-pe
                                        ;when I use it I will actually mean whether nil :enable-function oo-enable-text-abbrev-p.
    ("wether" "whether")
    ("effici" "efficient")
    ("situ" "situation")
    ("ihh" "I have had")
    ("reme" "remember")
    ("remem" "remember")
    ("hile" "while")
    ("menas" "means")
    ("equv" "equivalent")
    ("importnat" "important")
    ("attentin" "attention")
    ("execessivly" "excessively")
    ("bultin" "built-in")
    ("exampl" "example")
    ("alre" "already")
    ("wrot" "wrote")
    ("wrte" "wrote")
    ("soemties" "sometimes")
    ("upate" "update")
    ("itd" "it would")
    ("enginnering" "engineering")
    ("lang" "language")
    ("langs" "languages")
    ("dspite" "despite")
    ("diespite" "despite")
    ("aboive" "above")
    ("chaning" "changing")
    ("os" "operating system")
    ("potenl" "potentially")
    ("dependant" "dependent")
    ("wever" "wherever")
    ("loadng" "loading")
    ("soruc" "source")
    ("writi" "writing")
    ("msgs" "messages")
    ("anym" "anymore")
    ("anymo" "anymore")
    ("alwas" "always")
    ("remov" "remove")
    ("iddnt" "did not")
    ("expressoins" "expressions")
    ("regexes" "regular expressions")
    ("semed" "seemed")
    ("capture" "capture")
    ("messag" "message")
    ("rignt" "right")
    ("crating" "creating")
    ("preciese" "precise")
    ("narrowng" "narrowing")
    ("temped" "tempted")
    ("headlne" "headline")
    ("versoin" "version")
    ("talkinb" "talking")
    ("mentin" "mention")
    ("shod" "should")
    ("availa" "available")
    ("wiw" "What is worse")
    ("varients" "variants")
    ("updae" "update")
    ("enabe" "enable")
    ("commen" "common")
    ("simples" "simplest")
    ("thereofre" "therefore")
    ("ecape" "escape")
    ("coud" "could")
    ("replacment" "replacement")
    ("applic" "application")
    ("lsip" "lisp")
    ("txt" "text")
    ("impo" "important")
    ("vry" "every")
    ("defini" "definition")
    ("bindngs" "bindings")
    ("regexps" "regular expression")
    ("alty" "Alternatively")
    ("albeti" "albeit")
    ("bookmarkd" "bookmarked")
    ("whatev" "whatever")
    ("simplyfing" "simplifying")
    ("satisfiying" "satisfying")
    ("chara" "character")
    ("interediary" "intermediary")
    ("agan" "again")
    ("spefically" "specifically")
    ("certa" "certain")
    ("godod" "good")
    ("wlel" "well")
    ("temporl" "temporarily")
    ("proba" "probably")
    ("prob" "problem")
    ("bookms" "bookmarks")
    ("anythig" "anything")
    ("boookmark" "bookmark")
    ("sess" "session")
    ("bookmaks" "bookmarks")
    ("supp" "support")
    ("betw" "between")
    ("tat" "that")
    ("arbi" "arbitrary")
    ("regiser" "register")
    ("afaict" "as far as I can tell")
    ("writig" "writing")
    ("thme" "them")
    ("nesly" "necessarily")
    ("enof" "enough")
    ("andto" "and to")
    ("mins" "minutes")
    ("happengin" "happening")
    ("tme" "time")
    ("sente" "sentence")
    ("begi" "beginning")
    ("aroudn" "around")
    ("xpansion" "expansion")
    ("nt" "not")
    ("entier" "entire")
    ("unfor" "unfortunately")
    ("applicatioin" "application")
    ("dirs" "directories")
    ("avg" "average")
    ("aleady" "already")
    ("happ" "happy")
    ("capitalizatoin" "capitalization")
    ("anem" "name")
    ("contrl" "control")
    ("jumpt" "jump to")
    ("thatt" "that")
    ("lcoation" "location")
    ("settingns" "settings")
    ("recom" "recommended")
    ("unwiedly" "unwieldy")
    ("bufer" "buffer")
    ("takin" "taking")
    ("thatd" "that would")
    ("delimeter" "delimiter")
    ("defualt" "default")
    ("creae" "create")
    ("reqs" "requirements")
    ("mabe" "maybe")
    ("ti" "it")
    ("bufers" "buffers")
    ("bookmakrs" "bookmarks")
    ("ais" "as it stands,")
    ("ais" "as it stands")
    ("frmae" "frame")
    ("somehwo" "somehow")
    ("wa" "what")
    ("advisig" "advising")
    ("inadvertedly" "inadvertently")
    ("aamof" "as a matter of fact")
    ("eamcs" "Emacs")
    ("oep" "open")
    ("tendencis" "tendencies")
    ("magitcal" "magical")
    ("perosnally" "personally")
    ("successfullyy" "successfully")
    ("thatss" "that is")
    ("nwo" "now")
    ("determne" "determine")
    ("abbreviatons" "abbreviations")
    ("norml" "normal")
    ("inappripriate" "inappropriate")
    ("enalbe" "enable")
    ("realestate" "real-estate.")
    ("scrreen" "screen")
    ("prop" "property")
    ("rfine" "refine")
    ("previosu" "previous")
    ("ther" "there")
    ("rote" "wrote")
    ("partl" "partly")
    ("ro" "or")
    ("abbrrevs" "abbrevs")
    ("sev" "several")
    ("procise" "precise")
    ("whenn" "when")
    ("rounda" "roundabout")
    ("lisence" "license")
    ("liscence" "license")
    ("generatioin" "generation")
    ("divishion" "division")
    ("simialr" "similar")
    ("cmnt" "comment")
    ("whites" "whitespace")
    ("dup" "duplicate")
    ("dupli" "duplicate")
    ("commentar" "commentary")
    ("ppress" "press")
    ("keybs" "keybindings")
    ("reqed" "required")
    ("examinging" "examining")
    ("functinos" "functions")
    ("iuwt" "if you want to")
    ("teating" "treating")
    ("abbort" "abort")
    ("essntially" "essentially")
    ("functoins" "functions")
    ("loeaded" "loaded")
    ("appropr" "appropriate")
    ("pt" "point")
    ("befo" "before")
    ("ottomh" "off the top of my head")
    ("anon" "anonymous")
    ("gening" "generating")
    ("aoy" "as of yet")
    ("sillence" "silence")
    ("updadte" "update")
    ("rnadom" "random")
    ("deps" "dependencies")
    ("req" "require")
    ("reqm" "requirement")
    ("udate" "update")
    ("cnfig" "configuration")
    ("orners" "corners")
    ("sometiems" "sometimes")
    ("abstractioins" "abstractions")
    ("capt" "captain")
    ("loadingn" "loading")
    ("shoudnt" "should not")
    ("actu" "actually")
    ("lke" "like")
    ("tother" "together")
    ("usng" "using")
    ("advoid" "avoid")
    ("bytecomp" "byte-compilation")
    ("dupl" "duplicate")
    ("err" "error")
    ("repeateadly" "repeatedly")
    ("wtim" "with this in mind")
    ("dingly" "accordingly")
    ("ued" "used")
    ("consice" "concise")
    ("doenst" "does not")
    ("descr" "description")
    ("vai" "via")
    ("laoded" "loaded")
    ("mprove" "improve")
    ("errs" "errors")
    ("vals" "values")
    ("env" "environment")
    ("fomr" "form")
    ("upadte" "update")
    ("deling" "deleting")
    ("inst" "instead")
    ("abrevs" "abbrevs")
    ("cpies" "copies")
    ("memor" "memory")
    ("mch" "much")
    ("durat" "duration")
    ("buidls" "builds")
    ("asb" "as specified by")
    ("defering" "deferring")
    ("temr" "term")
    ("exs" "examples")
    ("suport" "support")
    ("oftne" "often")
    ("packae" "package")
    ("cmnts" "comments")
    ("lata" "later")
    ("ifo" "in favor of")
    ("thes" "these")
    ("prelim" "preliminary")
    ("buff" "buffer")
    ("raied" "raised")
    ("cmt" "comment")
    ("rased" "raised")
    ("boudn" "bound")
    ("commnt" "comment")
    ("commendt" "comment")
    ("hnl" "honestly")
    ("textobj" "text-object")
    ("kbds" "keybindings")
    ("canceled" "cancelled")
    ("ins" "insert")
    ("bds" "bindings")
    ("bd" "binding")
    ("kbd" "keybinding")
    ("cmds" "commands")
    ("cmd" "command")
    ("ae" "are")
    ("gral" "general")
    ("progrress" "progress")
    ("perf" "perfect")
    ("separ" "separate")
    ("mgs" "message")
    ("wrld" "world")
    ("wich" "which")
    ("msg" "message")
    ("mesage" "message")
    ("sems" "seems")
    ("rem" "remove")
    ("bod" "body")
    ("defing" "defining")
    ("awkard" "akward")
    ("recos" "recommends")
    ("binds" "bindings")
    ("nd" "and")
    ("approp" "appropriate")
    ("aprop" "appropriate")
    ("lexi" "lexicographically")
    ("econfig" "Emacs configuration")
    ("consec" "consecutive")
    ("conseq" "consequence")
    ("paces" "spaces")
    ("beh" "behavior")
    ("comnt" "comment")
    ("keybind" "keybinding")
    ("kbind" "keybinding")
    ("keybinds" "keybindings")
    ("kbinds" "keybindings")
    ("bcomp" "byte-compilation")
    ("unness" "unnecessary")
    ("coment" "comment")
    ("fror" "for")
    ("stup" "setup")
    ("inclinaition" "inclination")
    ("tring" "trying")
    ("wanna" "want to")
    ("effor" "effort")
    ("undef" "undefined")
    ("sym" "symbol")
    ("wre" "were")
    ("ws" "was")
    ("probs" "problems")
    ("syms" "symbols")
    ("tbs" "that being said")
    ("evalu" "evaluation")
    ("oside" "outside")
    ("bside" "beside")
    ("sumes" "assumes")
    ("evaling" "evaluating")
    ("res" "result")
    ("srcc" "source")
    ("sytle" "style")
    ("elt" "element")
    ("elts" "elements")
    ("gens" "generates")
    ("understandibly" "understandably")
    ("subborn" "stubborn")
    ("dever" "developer")
    ("devv" "development")
    ("mgiht" "might")
    ("despa" "desparate")
    ("progg" "programming")
    ("ttit" "the thing is that")
    ("tti" "the thing is")
    ("paht" "path")
    ("val" "value")
    ("optioinal" "optional")
    ("homogenous" "homogeneous")
    ("awa" "as well as")
    ("simul" "simultaneously")
    ("simultanouesly" "simultaneously")
    ("struct" "structure")
    ("structs" "structures")
    ("acces" "access")
    ("comm" "common")
    ("corr" "corresponding")
    ("expr" "expression")
    ("builtin" "built-in")
    ("elems" "elements")
    ("elem" "element")
    ("nones" "nonessential")
    ("abt" "about")
    ("yt" "youtube")
    ("iadt" "in addition to this")
    ("tldr" "TLDR")
    ("mo" "more")
    ("opt" "option")
    ("thro" "through")
    ("alowed" "allowed")
    ("allowd" "allowed")
    ("pefect" "perfect")
    ("negy" "negatively")
    ("neg" "negative")
    ("eff" "effect")
    ("weras" "whereas")
    ("fol" "following")
    ("foll" "following")
    ("ooh" "out of hand")
    ("combi" "combination")
    ("ingen" "in general")
    ("gened" "generated")
    ("aload" "autoload")
    ("amt" "amount")
    ("amoutn" "amount")
    ("lvl" "level")
    ("cd" "could")
    ("cud" "could")
    ("infor" "information")
    ("isn" "is not")
    ("thhe" "the")
    ("ques" "question")
    ("arg" "argument")
    ("equiv" "equivalent")
    ("mmend" "recommend")
    ("del" "delete")
    ("desc" "description")
    ("hes" "he is")
    ("impressoin" "impression")
    ("wsa" "was")
    ("var" "variable")
    ("vars" "variables")
    ("macroexp" "macro expansion")
    ("coments" "comments")
    ("unes" "unnecessary")
    ("uness" "unnecessary")
    ("dk" "do not know")
    ("emacss" "Emacs's")
    ("ess" "essentially")
    ("sist" "consistent")
    ("initing" "initializing")
    ("fnames" "filenames")
    ("misc" "miscellaneous")
    ("imml" "immediately")
    ("imm" "immediate")
    ("evv" "everything")
    ("abut" "about")
    ("movo" "moreover")
    ("dandylion" "dandelion")
    ("dandylions" "dandelions")
    ("bev" "bird's-eye view")
    ("thot" "thought")
    ("tmmw" "to make matters worse")
    ("freq" "frequency")
    ("pertubed" "perturbed")
    ("si" "is")
    ("vs" "versus")
    ("mor" "more")
    ("configing" "configuring")
    ("aume" "as you might expect")
    ("ayme" "as you might expect")
    ("tss" "timestamps")
    ("ts" "timestamp")
    ("obj" "object")
    ("oop" "object-oriented-programming")
    ("ood" "object-oriented-design")
    ("hwat" "what")
    ("sep" "separate")
    ("utube" "youtube")
    ("hav" "have")
    ("ootq" "out of the question")
    ("tte" "to this end")
    ("wasnt" "was not")
    ("ult" "ultimate")
    ("ultl" "ultimately")
    ("aia" "all in all")
    ("soly" "solely")
    ("idnwt" "I do not want to")
    ("coll" "collection")
    ("hadnt" "had not")
    ("suces" "success")
    ("sucess" "success")
    ("accros" "across")
    ("resonable" "reasonable")
    ("sec" "second")
    ("secs" "seconds")
    ("reco" "recommended")
    ("sth" "something")
    ("ath" "anything")
    ("corsor" "cursor")
    ("sdb" "should not be")
    ("rihgt" "right")
    ("shdnt" "should not")
    ("aycs" "as you can see")
    ("twisi" "the way I see it")
    ("fnr" "for no reason")
    ("mk" "make")
    ("prases" "phrases")
    ("thse" "these")
    ("english" "English")
    ("nuf" "enough")
    ("idek" "I did not even know")
    ("cur" "current")
    ("curr" "current")
    ("onl" "only")
    ("uve" "you have")
    ("revaled" "re-evaluated")
    ("idid" "I did")
    ("tres" "interesting")
    ("ml" "mode line")
                                        ;"definitely")
    ("docc" "documentation")
    ("nfo" "information")
    ("correclty" "correctly")
    ("coudl" "could")
    ("oofone" "O(1)")
    ("iml" "immediately")
    ("theyre" "they are")
    ("punc" "punctuation")
    ("dling" "downloading")
    ("ez" "easy")
    ("fol" "follow")
    ("popl" "populate")
    ("als" "autoloads")
    ("alo" "autoload")
    ("ootw" "out of the way")
    ("gen" "generate")
    ("aloads" "autoloads")
    ("alods" "autoloads")
    ("dls" "downloads")
    ("lize" "realize")
    ("hwo" "how")
    ("tbe" "to be exact")
    ("chars" "characters")
    ("heres" "here is")
    ("hesi" "hesitant")
    ("ex" "example")
    ("xample" "example")
    ("cna" "can")
    ("ord" "order")
    ("cate" "category")
    ("nyt" "anything")
    ("mena" "mean")
    ("doin" "doing")
    ("na" "an")
    ("somethig" "something")
    ("iac" "in any case")
    ("di" "do it")
    ("intro" "introduction")
    ("tha" "that")
    ("char" "character")
    ("wt" "want to")
    ("hava" "have a")
    ("deflt" "default")
    ("fname" "filename")
    ("ta" "that")
    ("itl" "it will")
    ("itll" "it will")
    ("mott" "most of the time")
    ("sd" "should")
    ("shd" "should")
    ("eelm" "emacs-lisp-mode")
    ("eemacs" "Emacs")
    ("alot" "a lot")
    ("moro" "moreover")
    ("orig" "original")
    ("iat" "in addition to")
    ("elispp" "emacs-lisp")
    ("idl" "I would like")
                                        ;is actually a word, but I use it so infrequently and I use the phrase. Nil :enable-function oo-enable-text-abbrev-pI
                                        ;so frequently that it is worth having it be an abbrev for I nil :enable-function oo-enable-text-abbrev-p.
    ("prec" "precedence")
    ("wdimbt" "what do I mean by this")
    ("wdim" "what do I mean")
    ("awn" "also worth noting")
    ("int" "I need to")
    ("wch" "which")
    ("ch" "which")
    ("igts" "I have got to say")
    ("ihtbs" "it has to be said")
    ("wd" "would")
    ("freql" "frequently")
    ("ifreql" "infrequently")
    ("infreql" "infrequently")
    ("id" "I would")
    ("wan" "want")
    ("idht" "I do not have to")
    ("hvae" "have")
    ("cann" "cannot")
    ("icj" "I can just")
    ("ic" "I can")
    ("ure" "you are")
    ("lhp" "Luis Henriquez-Perez")
    ("noly" "not only")
    ("specy" "specifically")
    ("rl" "really")
    ("argss" "arguments")
    ("ppl" "people")
    ("urself" "yourself")
    ("ab" "about")
    ("ret" "return")
    ("tn" "then")
    ("blv" "believe")
    ("nto" "not")
    ("mone" "money")
    ("hve" "have")
    ("swich" "switch")
    ("actuall" "actually")
    ("evalt" "evaluate")
    ("asap" "A.S.A.P.")
    ("econf" "emacs configuration")
    ("alth" "although")
    ("esp" "especially")
                                        ;clashes with the word "ill" but I barely use that word. In the rar nil :enable-function oo-enable-text-abbrev-pe
                                        ;where I do need to use it I will unexpand it nil :enable-function oo-enable-text-abbrev-p.
    ("ill" "I will")
                                        ;is a common abbrev for "by the way" but I feel like I do not really us nil :enable-function oo-enable-text-abbrev-pe
                                        ;phrase unless I am texting nil :enable-function oo-enable-text-abbrev-p.
    ("imd" "immediately")
    ("exand" "expand")
    ("ppet" "snippet")
    ("tse" "these")
    ("usu" "usually")
    ("iprac" "in practice")
    ("efy" "efficiency")
    ("evr" "everything")
    ("sen" "seen")
    ("wat" "what")
    ("dfl" "default")
    ("dflt" "default")
    ("difr" "differ")
    ("btw" "between")
    ("dif" "different")
    ("diff" "different")
    ("htat" "that")
    ("rnt" "are not")
    ("arent" "are not")
    ("tt" "the")
    ("len" "length")
    ("bf" "before")
    ("aft" "after")
    ("af" "at first")
    ("oft" "often")
    ("dsnt" "does not")
    ("ihdbtk" "I had been thinking")
    ("ihdb" "I had been")
    ("ihb" "I have been")
    ("ihbtk" "I have been thinking")
    ("ihbtkt" "I have been thinking that")
    ("ihbtkti" "I have been thinking that I")
    ("ihbtka" "I have been thinking about")
    ("comptia" "CompTIA")
    ("gt" "get")
    ("wev" "whatever")
    ("jbos" "jobs")
    ("theyll" "they will")
    ("prevl" "previously")
    ("prev" "previous")
    ("ivs" "I have seen")
    ("rxp" "regular expression")
    ("rx" "regular expression")
    ("dl" "download")
    ("vcc" "version control")
    ("wil" "will")
    ("shiftk" "SHIFT")
    ("nots" "number of times")
    ("num" "number")
    ("lins" "lines")
    ;; I thought that this could be a bad abbrev because it is too much line. Nil :enable-function oo-enable-text-abbrev-pa
    ;; spelling mistake of =the=, but then I thought if I do misspell "the" it I nil :enable-function oo-enable-text-abbrev-ps
    ;; very unlikely I will do so by pressing =t= again nil :enable-function oo-enable-text-abbrev-p.
    ("tht" "thought")
    ("i" "I")
    ("luis" "Luis")
    ;; This will not work because ";" is not a work constituent. I need to us nil :enable-function oo-enable-text-abbrev-pe
    ;; `aas' for this or come up with some other solution nil :enable-function oo-enable-text-abbrev-p.
    ;; (";;" ".")
    ;; TODO: move to spell-fixing abbrev nil :enable-function oo-enable-text-abbrev-p.
    ("ivb" "I have been")
    ("werent" "were not")
    ("rly" "really")
    ("aagp" "at any given point")
    ("begn" "beginning")
    ("idnt" "I do not think")
    ("idt" "I do not think")
    ("ting" "thing")
    ("ned" "need")
    ("dir" "directory")
    ("ull" "you will")
    ("spst" "supposed")
    ("hv" "have")
    ("desiding" "deciding")
    ("pkgs" "packages")
    ("pkg" "package")
    ("ftmp" "for the most part")
    ("readme" "README")
    ("sdnt" "should not")
    ("cme" "come")
    ("imed" "immediately")
    ("cesly" "successfully")
    ("owoto" "one way or the other")
    ("configs" "configurations")
    ("espace" "escape")
    ("ijwi" "I just want it")
    ("ijw" "I just want")
    ("idw" "I do not want")
    ("ij" "I just")
    ("unesy" "unnecessarily")
    ("nes" "necessary")
    ("bec" "because")
    ("aswer" "answer")
    ("dlk" "do not like")
    ("tho" "though")
    ("idkw" "I do not know why")
    ("damw" "do not ask me why")
    ("idlk" "I do not like")
    ("ilk" "I like")
    ("auly" "automatically")
    ("dsl" "Domain-Specific-Language")
    ("fn" "function")
    ("fns" "functions")
    ("ig" "instagram")
    ("econf" "Emacs configuration")
    ("kbdm" "keyboard macro")
    ("kbdms" "keyboard macros")
    ("msw" "Microsoft Windows")
    ("imho" "in my humble opinion")
    ("imo" "in my opinion")
    ("fyi" "for your information")
    ("lmk" "let me know")
    ("afaik" "as far as I know")
    ("idk" "I do not know")
    ("gonna" "going to")
    ("otc" "on the contrary")
    ("st" "sometimes")
    ("tbh" "to be honest")
    ("qwerty" "QWERTY")
    ("ngl" "not going to lie")
    ("tfb" "to be frank")
    ("ndo" "window")
    ("tis" "its")
    ("amly" "automatically")
    ("rn" "right now")
    ("bly" "probably")
    ("lk" "like")
    ;; I want the word =config= to stay the same too much for this to be useful nil :enable-function oo-enable-text-abbrev-p.
    ;; Right now it is frankly more of an impediment for me than something that nil :enable-function oo-enable-text-abbrev-pt
    ;; helps me nil :enable-function oo-enable-text-abbrev-p.
    ("questioin" "question")
    ("ur" "your")
    ("wiht" "with")
    ("ith" "with")
    ("abilit" "ability")
    ("ko" "K.O.")
    ("dat" "that")
    ("incc" "increase")
    ("incs" "increase")
    ("decs" "deccrease")
    ;; TODO: Add a condition preventng it from expanding if I am writing a file path nil :enable-function oo-enable-text-abbrev-p.
    ("econfigg" "Emacs configuration")
    ("configg" "configuration")
    ("obvl" "obviously")
    ("obv" "obvious")
    ("appr" "appropriate")
    ("ofc" "of course")
    ("ok" "O.K.")
    ("iis" "it is")
    ("bc" "because")
    ("iow" "in other words")
    ("uun" "up until now")
    ("exwm" "EXWM")
    ("fe" "for example")
    ("evaled" "evaluated")
    ("imma" "I am going to")
    ;; From https://sachachua.com/blog/2015/01/developing-emacs-micro-habits-text-automation nil :enable-function oo-enable-text-abbrev-p/
    ("iwt" "I want to")
    ("hw" "however")
    ("ths" "this")
    ("otoh" "on the one hand")
    ("otth" "on the other hand")
    ("kinda" "kind of")
    ("ohter" "other")
    ("fi" "for instance")
    ("youve" "you have")
    ("youd" "you would")
    ("il" "I will")
    ("theres" "there is")
    ("itss" "it is")
    ("im" "I am")
    ("illl" "I will")
    ("cant" "cannot")
    ("idd" "ID")
    ("dont" "do not")
    ("wontt" "will not")
    ("doesnt" "does not")
    ;; Not sure I actually want this abbrev because =wont= is actually a word nil :enable-function oo-enable-text-abbrev-p.
    ("ine" "one")
    ("mispelling" "misspelling")
    ("ry" "very")
    ("wont" "will not")
    ("thats" "that is")
    ("u" "you")
    ("ul" "you will")
    ("dnt" "don't")
    ("wo" "without")
    ("ive" "I have")
    ("ik" "I know")
    ("plx" "complex")
    ("ribe" "describe")
    ("iff" "if and only if")
    ("addd" "additionally")
    ("weve" "we have")
    ("whats" "what is")
    ("havent" "have not")
    ("didnt" "did not")
    ("shouldnt" "should not")
    ("isnt" "is not")
    ("fo" "of")
    ("ud" "you would")
    ("fwis" "from what I see")
    ("fwiu" "from what I understand")
    ("youre" "you are")
    ("wouldnt" "would not")
    ("woudnt" "would not")
    ("coudnt" "could not")
    ("couldnt" "could not")
    ;; These abbrevs are focused on spelling mistakes.
    ;; Here I focus on fixing unambiguous spelling mistakes.
    ("onw" "own")
    ("frst" "first")
    ("edting" "editing")
    ("alread" "already")
    ("htats" "that is")
    ("whehther" "whether")
    ("somehting" "something")
    ("hte" "the")
    ("te" "the")
    ("th" "to have")
    ("ot" "to")
    ("wnat" "want")
    ("stoped" "stopped")
    ("capfs" "completion-at-point-functions")
    ("suprise" "surprise")
    ("functoin" "function")
    ("refect" "reflect")
    ("dint" "did not")
    ("orignal" "original")
    ("eachother" "each other")
    ("dn" "do not")))
;;; provide
(provide '911-text-abbrevs)
;;; 911-text-abbrevs.el ends here
