;;; 911-text-abbrevs.el --- TODO: add commentary -*- lexical-binding: t; -*-
;;
;; Copyright (c) 2024 Free Software Foundation, Inc.
;;
;; Author: Luis Henriquez-Perez <luis@luishp.xyz>
;; Homepage: https://github.com/Luis-Henriquez-Perez/dotfiles/
;;
;; This file is not part of GNU Emacs.
;;
;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License as
;; published by the Free Software Foundation, either version 3 of the
;; License, or (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful, but
;; WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
;; General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program. If not, see <http://www.gnu.org/licenses/>.
;;
;;; Commentary:
;;
;; TODO: add commentary
;;
;;; Code:
(require '050-base)
(require 'abbrev)

(define-abbrev oo-text-abbrev-table "theone" "the one")
(define-abbrev oo-text-abbrev-table "iwc" "in which case")
(define-abbrev oo-text-abbrev-table "ben" "been")
(define-abbrev oo-text-abbrev-table "praticular" "particular")
(define-abbrev oo-text-abbrev-table "faw" "for a while")
(define-abbrev oo-text-abbrev-table "highl" "highlight")
(define-abbrev oo-text-abbrev-table "whi" "while")
(define-abbrev oo-text-abbrev-table "eh" "the")
(define-abbrev oo-text-abbrev-table "appa" "apparent")
(define-abbrev oo-text-abbrev-table "yr" "year")
(define-abbrev oo-text-abbrev-table "xp" "experience")
(define-abbrev oo-text-abbrev-table "implem" "implementation")
(define-abbrev oo-text-abbrev-table "itme" "item")
(define-abbrev oo-text-abbrev-table "io" "instead of")
(define-abbrev oo-text-abbrev-table "menaul" "manual")
(define-abbrev oo-text-abbrev-table "entr" "entry")
(define-abbrev oo-text-abbrev-table "das" "days")
(define-abbrev oo-text-abbrev-table "teime" "time")
(define-abbrev oo-text-abbrev-table "wast" "waste")
(define-abbrev oo-text-abbrev-table "taks" "tasks")
(define-abbrev oo-text-abbrev-table "imple" "implement")
(define-abbrev oo-text-abbrev-table "impltt" "implementation")
(define-abbrev oo-text-abbrev-table "divied" "divided")
(define-abbrev oo-text-abbrev-table "idkw" "I do not know what")
(define-abbrev oo-text-abbrev-table "ambig" "ambiguous")
(define-abbrev oo-text-abbrev-table "hsi" "his")
(define-abbrev oo-text-abbrev-table "stats" "statistics")
(define-abbrev oo-text-abbrev-table "defalt" "default")
(define-abbrev oo-text-abbrev-table "inter" "interesting")
(define-abbrev oo-text-abbrev-table "idnt" "I do not")
(define-abbrev oo-text-abbrev-table "david" "David")
(define-abbrev oo-text-abbrev-table "workflwo" "workflow")
(define-abbrev oo-text-abbrev-table "amnt" "amount")
(define-abbrev oo-text-abbrev-table "gtd" "GTD")
(define-abbrev oo-text-abbrev-table "whatd" "what would")
(define-abbrev oo-text-abbrev-table "watd" "what would")
(define-abbrev oo-text-abbrev-table "aot" "any of these")
(define-abbrev oo-text-abbrev-table "imn" "I am not")
(define-abbrev oo-text-abbrev-table "honl" "honestly")
(define-abbrev oo-text-abbrev-table "signi" "signify")
(define-abbrev oo-text-abbrev-table "deadlne" "deadline")
(define-abbrev oo-text-abbrev-table "aranged" "arranged")
(define-abbrev oo-text-abbrev-table "bs" "bullshit")
(define-abbrev oo-text-abbrev-table "alr" "already")
(define-abbrev oo-text-abbrev-table "exaustion" "exhaustion")
(define-abbrev oo-text-abbrev-table "thare" "that are")
(define-abbrev oo-text-abbrev-table "cmp" "compare")
(define-abbrev oo-text-abbrev-table "tf" "therefore")
(define-abbrev oo-text-abbrev-table "dren" "children")
(define-abbrev oo-text-abbrev-table "aee" "all else equal")
(define-abbrev oo-text-abbrev-table "keyw" "keyword")
(define-abbrev oo-text-abbrev-table "deln" "deletion")
(define-abbrev oo-text-abbrev-table "wndow" "window")
(define-abbrev oo-text-abbrev-table "idnht" "I did not have to")
(define-abbrev oo-text-abbrev-table "win" "window")
(define-abbrev oo-text-abbrev-table "anyt" "anything")
(define-abbrev oo-text-abbrev-table "hls" "headlines")
(define-abbrev oo-text-abbrev-table "hgs" "headings")
(define-abbrev oo-text-abbrev-table "hg" "heading")
(define-abbrev oo-text-abbrev-table "hl" "headline")
(define-abbrev oo-text-abbrev-table "ahs" "has")
(define-abbrev oo-text-abbrev-table "iwb" "it would be")
(define-abbrev oo-text-abbrev-table "sba" "should be a")
(define-abbrev oo-text-abbrev-table "sb" "should be")
(define-abbrev oo-text-abbrev-table "iwrh" "I would rather have")
(define-abbrev oo-text-abbrev-table "iwd" "I would")
(define-abbrev oo-text-abbrev-table "iw" "I was")
(define-abbrev oo-text-abbrev-table "consisten" "consistent")
(define-abbrev oo-text-abbrev-table "alphz" "alphabetize")
(define-abbrev oo-text-abbrev-table "menti" "mention")
(define-abbrev oo-text-abbrev-table "creeate" "create")
(define-abbrev oo-text-abbrev-table "nvm" "nevermind")
(define-abbrev oo-text-abbrev-table "ve" "very")
(define-abbrev oo-text-abbrev-table "higs" "highest")
(define-abbrev oo-text-abbrev-table "overr" "override")
(define-abbrev oo-text-abbrev-table "creaed" "created")
(define-abbrev oo-text-abbrev-table "strat" "strategy")
(define-abbrev oo-text-abbrev-table "adi" "aid")
(define-abbrev oo-text-abbrev-table "deadlie" "deadline")
(define-abbrev oo-text-abbrev-table "comm" "comment")
(define-abbrev oo-text-abbrev-table "comms" "comments")
(define-abbrev oo-text-abbrev-table "akwardly" "awkwardly")
(define-abbrev oo-text-abbrev-table "displaed" "displayed")
(define-abbrev oo-text-abbrev-table "crual" "crucial")
(define-abbrev oo-text-abbrev-table "chilren" "children")
(define-abbrev oo-text-abbrev-table "ia" "I am")
(define-abbrev oo-text-abbrev-table "twt" "those were the")
(define-abbrev oo-text-abbrev-table "oom" "one or more")
(define-abbrev oo-text-abbrev-table "wnht" "would not have to")
(define-abbrev oo-text-abbrev-table "wdnt" "would not")
(define-abbrev oo-text-abbrev-table "itmes" "items")
(define-abbrev oo-text-abbrev-table "ocntrol" "control")
(define-abbrev oo-text-abbrev-table "thoro" "thorough")
(define-abbrev oo-text-abbrev-table "itt" "I thought that")
(define-abbrev oo-text-abbrev-table "prio" "priority")
(define-abbrev oo-text-abbrev-table "genda" "agenda")
(define-abbrev oo-text-abbrev-table "bottomost" "bottommost")
(define-abbrev oo-text-abbrev-table "behav" "behavior")
(define-abbrev oo-text-abbrev-table "thnk" "think")
(define-abbrev oo-text-abbrev-table "digesteable" "digestible")
(define-abbrev oo-text-abbrev-table "subtaks" "subtasks")
(define-abbrev oo-text-abbrev-table "themselvs" "themselves")
(define-abbrev oo-text-abbrev-table "tasts" "tasks")
(define-abbrev oo-text-abbrev-table "todos" "TODOs")
(define-abbrev oo-text-abbrev-table "todo" "TODO")
(define-abbrev oo-text-abbrev-table "gs" "generally speaking")
(define-abbrev oo-text-abbrev-table "aka" "also known as")
(define-abbrev oo-text-abbrev-table "convet" "convenient")
(define-abbrev oo-text-abbrev-table "inevl" "inevitably")
(define-abbrev oo-text-abbrev-table "woth" "worth")
(define-abbrev oo-text-abbrev-table "hasnt" "has not")
(define-abbrev oo-text-abbrev-table "arbil" "arbitrarily")
(define-abbrev oo-text-abbrev-table "vari" "various")
(define-abbrev oo-text-abbrev-table "keywrods" "keywords")
(define-abbrev oo-text-abbrev-table "acountable" "accountable")
(define-abbrev oo-text-abbrev-table "propspect" "prospect")
(define-abbrev oo-text-abbrev-table "aagm" "at any given moment")
(define-abbrev oo-text-abbrev-table "odl" "old")
(define-abbrev oo-text-abbrev-table "headliens" "headlines")
(define-abbrev oo-text-abbrev-table "props" "properties")
(define-abbrev oo-text-abbrev-table "headli" "headline")
(define-abbrev oo-text-abbrev-table "hli" "headline")
(define-abbrev oo-text-abbrev-table "fnd" "find")
(define-abbrev oo-text-abbrev-table "diffi" "difficult")
(define-abbrev oo-text-abbrev-table "thigs" "things")
(define-abbrev oo-text-abbrev-table "idds" "IDs")
(define-abbrev oo-text-abbrev-table "someting" "something")
(define-abbrev oo-text-abbrev-table "parti" "particular")
(define-abbrev oo-text-abbrev-table "sh" "should have")
(define-abbrev oo-text-abbrev-table "desb" "describe")
(define-abbrev oo-text-abbrev-table "efficl" "efficiently")
(define-abbrev oo-text-abbrev-table "rath" "rather")
(define-abbrev oo-text-abbrev-table "experd" "experienced")
(define-abbrev oo-text-abbrev-table "exper" "experience")
(define-abbrev oo-text-abbrev-table "hol" "honestly")
(define-abbrev oo-text-abbrev-table "hon" "honest")
(define-abbrev oo-text-abbrev-table "ofo" "off of")
(define-abbrev oo-text-abbrev-table "juust" "just")
(define-abbrev oo-text-abbrev-table "atst" "at the same time")
(define-abbrev oo-text-abbrev-table "abbrevx" "abbrevs")
(define-abbrev oo-text-abbrev-table "oos" "out of scope")
(define-abbrev oo-text-abbrev-table "ano" "another")
(define-abbrev oo-text-abbrev-table "woud" "would")
(define-abbrev oo-text-abbrev-table "hty" "they")
(define-abbrev oo-text-abbrev-table "theve" "they have")
(define-abbrev oo-text-abbrev-table "theyve" "they have")
(define-abbrev oo-text-abbrev-table "lok" "look")
(define-abbrev oo-text-abbrev-table "implemed" "implemented")
(define-abbrev oo-text-abbrev-table "evals" "evaluates")
(define-abbrev oo-text-abbrev-table "ih" "I have")
(define-abbrev oo-text-abbrev-table "implementd" "implemented")
(define-abbrev oo-text-abbrev-table "esear" "easier")
(define-abbrev oo-text-abbrev-table "ezer" "easier")
(define-abbrev oo-text-abbrev-table "ezr" "easier")
(define-abbrev oo-text-abbrev-table "persp" "perspective")
(define-abbrev oo-text-abbrev-table "seve" "several")
(define-abbrev oo-text-abbrev-table "sence" "sense")
(define-abbrev oo-text-abbrev-table "reffed" "referenced")
(define-abbrev oo-text-abbrev-table "menual" "manual")
(define-abbrev oo-text-abbrev-table "pakckage" "package")
(define-abbrev oo-text-abbrev-table "relize" "realize")
(define-abbrev oo-text-abbrev-table "relized" "realized")
(define-abbrev oo-text-abbrev-table "templat" "template")
(define-abbrev oo-text-abbrev-table "templ" "template")
(define-abbrev oo-text-abbrev-table "unfort" "unfortunately")
(define-abbrev oo-text-abbrev-table "floabn" "for lack of a better name")
(define-abbrev oo-text-abbrev-table "thots" "thoughts")
(define-abbrev oo-text-abbrev-table "mb" "maybe")
(define-abbrev oo-text-abbrev-table "ikt" "I know that")
(define-abbrev oo-text-abbrev-table "decis" "decision")
(define-abbrev oo-text-abbrev-table "atp" "at that point")
(define-abbrev oo-text-abbrev-table "somethign" "something")
(define-abbrev oo-text-abbrev-table "evalate" "evaluate")
(define-abbrev oo-text-abbrev-table "forst" "first")
(define-abbrev oo-text-abbrev-table "itk" "I think")
(define-abbrev oo-text-abbrev-table "loc" "location")
(define-abbrev oo-text-abbrev-table "al" "at least")
(define-abbrev oo-text-abbrev-table "tresti" "intresting")
(define-abbrev oo-text-abbrev-table "ntax" "syntax")
(define-abbrev oo-text-abbrev-table "intres" "interest")
(define-abbrev oo-text-abbrev-table "taged" "tagged")
(define-abbrev oo-text-abbrev-table "remed" "removed")
(define-abbrev oo-text-abbrev-table "neces" "necessary")
(define-abbrev oo-text-abbrev-table "nec" "necessary")
(define-abbrev oo-text-abbrev-table "kws" "keywords")
(define-abbrev oo-text-abbrev-table "kw" "keyword")
(define-abbrev oo-text-abbrev-table "mulitple" "multiple")
(define-abbrev oo-text-abbrev-table "iiee" "It is easy enough")
(define-abbrev oo-text-abbrev-table "mab" "maybe")
(define-abbrev oo-text-abbrev-table "automl" "automatically")
(define-abbrev oo-text-abbrev-table "auotml" "automatically")
(define-abbrev oo-text-abbrev-table "enalbed" "enabled")
(define-abbrev oo-text-abbrev-table "unples" "unpleasant")
(define-abbrev oo-text-abbrev-table "hk" "hook")
(define-abbrev oo-text-abbrev-table "toda" "today")
(define-abbrev oo-text-abbrev-table "aloading" "autoloading")
(define-abbrev oo-text-abbrev-table "shoud" "should")
(define-abbrev oo-text-abbrev-table "dong" "doing")
(define-abbrev oo-text-abbrev-table "wordd" "word")
(define-abbrev oo-text-abbrev-table "loadded" "loaded")
(define-abbrev oo-text-abbrev-table "img" "image")
(define-abbrev oo-text-abbrev-table "pupular" "popular")
(define-abbrev oo-text-abbrev-table "strait" "straight")
(define-abbrev oo-text-abbrev-table "srait" "straight")
(define-abbrev oo-text-abbrev-table "stait" "straight")
(define-abbrev oo-text-abbrev-table "staight" "straight")
(define-abbrev oo-text-abbrev-table "staightfforward" "straightforward")
(define-abbrev oo-text-abbrev-table "staightf" "staightforward")
(define-abbrev oo-text-abbrev-table "straightfforward" "straightforward")
(define-abbrev oo-text-abbrev-table "straightf" "staightforward")
(define-abbrev oo-text-abbrev-table "descrip" "description")
(define-abbrev oo-text-abbrev-table "ifle" "file")
(define-abbrev oo-text-abbrev-table "prefxi" "prefix")
(define-abbrev oo-text-abbrev-table "reedame" "README")
(define-abbrev oo-text-abbrev-table "reeame" "README")
(define-abbrev oo-text-abbrev-table "reame" "README")
(define-abbrev oo-text-abbrev-table "nuo" "number of")
(define-abbrev oo-text-abbrev-table "noo" "number of")
(define-abbrev oo-text-abbrev-table "iftt" "I feel that there")
(define-abbrev oo-text-abbrev-table "ift" "I feel that")
(define-abbrev oo-text-abbrev-table "ihaft" "I have a feeling that")
(define-abbrev oo-text-abbrev-table "dnnt" "do not need to")
(define-abbrev oo-text-abbrev-table "aw" "as well")
(define-abbrev oo-text-abbrev-table "iaww" "I am wondering whether")
(define-abbrev oo-text-abbrev-table "authr" "author")
(define-abbrev oo-text-abbrev-table "alis" "alias")
(define-abbrev oo-text-abbrev-table "tij" "this is just")
(define-abbrev oo-text-abbrev-table "bookmakr" "bookmark")
(define-abbrev oo-text-abbrev-table "nonlive" "non-live")
(define-abbrev oo-text-abbrev-table "asso" "associate")
(define-abbrev oo-text-abbrev-table "assod" "associated")
(define-abbrev oo-text-abbrev-table "bufs" "buffers")
(define-abbrev oo-text-abbrev-table "bifn" "but if not")
(define-abbrev oo-text-abbrev-table "ifn" "if not")
(define-abbrev oo-text-abbrev-table "makr" "mark")
(define-abbrev oo-text-abbrev-table "bufferes" "buffers")
(define-abbrev oo-text-abbrev-table "advan" "advantage")
(define-abbrev oo-text-abbrev-table "bi" "built-in")
(define-abbrev oo-text-abbrev-table "intli" "I need to look into")
(define-abbrev oo-text-abbrev-table "buf" "buffer")
(define-abbrev oo-text-abbrev-table "iti" "it is")
(define-abbrev oo-text-abbrev-table "isb" "it should be")
(define-abbrev oo-text-abbrev-table "workspac" "workspace")
(define-abbrev oo-text-abbrev-table "succintly" "succinctly")
(define-abbrev oo-text-abbrev-table "bos" "beginning of a sentence")
(define-abbrev oo-text-abbrev-table "siha" "should I have a")
(define-abbrev oo-text-abbrev-table "renable" "re-enable")
(define-abbrev oo-text-abbrev-table "reenable" "re-enable")
(define-abbrev oo-text-abbrev-table "gener" "general")
(define-abbrev oo-text-abbrev-table "visi" "visible")
(define-abbrev oo-text-abbrev-table "condi" "condition")
(define-abbrev oo-text-abbrev-table "qol" "quality of life")
(define-abbrev oo-text-abbrev-table "asumes" "assumes")
(define-abbrev oo-text-abbrev-table "uf" "of")
(define-abbrev oo-text-abbrev-table "alw" "always")
(define-abbrev oo-text-abbrev-table "sorta" "sort of")
(define-abbrev oo-text-abbrev-table "smaple" "sample")
(define-abbrev oo-text-abbrev-table "spefic" "specific")
(define-abbrev oo-text-abbrev-table "specifi" "specific")
(define-abbrev oo-text-abbrev-table "cre" "create")
(define-abbrev oo-text-abbrev-table "ww" "wanted")
(define-abbrev oo-text-abbrev-table "fgc" "foreground color")
(define-abbrev oo-text-abbrev-table "bgc" "background color")
(define-abbrev oo-text-abbrev-table "fireground" "foreground")
(define-abbrev oo-text-abbrev-table "fgs" "foregrounds")
(define-abbrev oo-text-abbrev-table "fg" "foreground")
(define-abbrev oo-text-abbrev-table "bgs" "backgrounds")
(define-abbrev oo-text-abbrev-table "lized" "realized")
(define-abbrev oo-text-abbrev-table "isnbt" "it should not be the")
(define-abbrev oo-text-abbrev-table "isnb" "it should not be")
(define-abbrev oo-text-abbrev-table "bg" "background")
(define-abbrev oo-text-abbrev-table "rigght" "right")
(define-abbrev oo-text-abbrev-table "prot" "protesilaos")
(define-abbrev oo-text-abbrev-table "prots" "protesilaos's")
(define-abbrev oo-text-abbrev-table "momnb" "may or may not be")
(define-abbrev oo-text-abbrev-table "ivht" "I have had the")
(define-abbrev oo-text-abbrev-table "ivh" "I have had")
(define-abbrev oo-text-abbrev-table "libs" "libraries")
;; Note that wether is actually a word meaning "a castrated male sheep or goat"
;; but I do not expect to be using this word at all. I expect 99% of the tim nil :enable-function oo-enable-text-abbrev-pe
;; that when I use it I will actually mean whether nil :enable-function oo-enable-text-abbrev-p.
(define-abbrev oo-text-abbrev-table "wether" "whether")
(define-abbrev oo-text-abbrev-table "effici" "efficient")
(define-abbrev oo-text-abbrev-table "situ" "situation")
(define-abbrev oo-text-abbrev-table "ihh" "I have had")
(define-abbrev oo-text-abbrev-table "reme" "remember")
(define-abbrev oo-text-abbrev-table "remem" "remember")
(define-abbrev oo-text-abbrev-table "hile" "while")
(define-abbrev oo-text-abbrev-table "menas" "means")
(define-abbrev oo-text-abbrev-table "equv" "equivalent")
(define-abbrev oo-text-abbrev-table "importnat" "important")
(define-abbrev oo-text-abbrev-table "attentin" "attention")
(define-abbrev oo-text-abbrev-table "execessivly" "excessively")
(define-abbrev oo-text-abbrev-table "bultin" "built-in")
(define-abbrev oo-text-abbrev-table "exampl" "example")
(define-abbrev oo-text-abbrev-table "alre" "already")
(define-abbrev oo-text-abbrev-table "wrot" "wrote")
(define-abbrev oo-text-abbrev-table "wrte" "wrote")
(define-abbrev oo-text-abbrev-table "soemties" "sometimes")
(define-abbrev oo-text-abbrev-table "upate" "update")
(define-abbrev oo-text-abbrev-table "itd" "it would")
(define-abbrev oo-text-abbrev-table "enginnering" "engineering")
(define-abbrev oo-text-abbrev-table "lang" "language")
(define-abbrev oo-text-abbrev-table "langs" "languages")
(define-abbrev oo-text-abbrev-table "dspite" "despite")
(define-abbrev oo-text-abbrev-table "diespite" "despite")
(define-abbrev oo-text-abbrev-table "aboive" "above")
(define-abbrev oo-text-abbrev-table "chaning" "changing")
(define-abbrev oo-text-abbrev-table "os" "operating system")
(define-abbrev oo-text-abbrev-table "potenl" "potentially")
(define-abbrev oo-text-abbrev-table "dependant" "dependent")
(define-abbrev oo-text-abbrev-table "wever" "wherever")
(define-abbrev oo-text-abbrev-table "loadng" "loading")
(define-abbrev oo-text-abbrev-table "soruc" "source")
(define-abbrev oo-text-abbrev-table "writi" "writing")
(define-abbrev oo-text-abbrev-table "msgs" "messages")
(define-abbrev oo-text-abbrev-table "anym" "anymore")
(define-abbrev oo-text-abbrev-table "anymo" "anymore")
(define-abbrev oo-text-abbrev-table "alwas" "always")
(define-abbrev oo-text-abbrev-table "remov" "remove")
(define-abbrev oo-text-abbrev-table "iddnt" "did not")
(define-abbrev oo-text-abbrev-table "expressoins" "expressions")
(define-abbrev oo-text-abbrev-table "regexes" "regular expressions")
(define-abbrev oo-text-abbrev-table "semed" "seemed")
(define-abbrev oo-text-abbrev-table "capture" "capture")
(define-abbrev oo-text-abbrev-table "messag" "message")
(define-abbrev oo-text-abbrev-table "rignt" "right")
(define-abbrev oo-text-abbrev-table "crating" "creating")
(define-abbrev oo-text-abbrev-table "preciese" "precise")
(define-abbrev oo-text-abbrev-table "narrowng" "narrowing")
(define-abbrev oo-text-abbrev-table "temped" "tempted")
(define-abbrev oo-text-abbrev-table "headlne" "headline")
(define-abbrev oo-text-abbrev-table "versoin" "version")
(define-abbrev oo-text-abbrev-table "talkinb" "talking")
(define-abbrev oo-text-abbrev-table "mentin" "mention")
(define-abbrev oo-text-abbrev-table "shod" "should")
(define-abbrev oo-text-abbrev-table "availa" "available")
(define-abbrev oo-text-abbrev-table "wiw" "What is worse")
(define-abbrev oo-text-abbrev-table "varients" "variants")
(define-abbrev oo-text-abbrev-table "updae" "update")
(define-abbrev oo-text-abbrev-table "enabe" "enable")
(define-abbrev oo-text-abbrev-table "commen" "common")
(define-abbrev oo-text-abbrev-table "simples" "simplest")
(define-abbrev oo-text-abbrev-table "thereofre" "therefore")
(define-abbrev oo-text-abbrev-table "ecape" "escape")
(define-abbrev oo-text-abbrev-table "coud" "could")
(define-abbrev oo-text-abbrev-table "replacment" "replacement")
(define-abbrev oo-text-abbrev-table "applic" "application")
(define-abbrev oo-text-abbrev-table "lsip" "lisp")
(define-abbrev oo-text-abbrev-table "txt" "text")
(define-abbrev oo-text-abbrev-table "impo" "important")
(define-abbrev oo-text-abbrev-table "vry" "every")
(define-abbrev oo-text-abbrev-table "defini" "definition")
(define-abbrev oo-text-abbrev-table "bindngs" "bindings")
(define-abbrev oo-text-abbrev-table "regexps" "regular expression")
(define-abbrev oo-text-abbrev-table "alty" "Alternatively")
(define-abbrev oo-text-abbrev-table "albeti" "albeit")
(define-abbrev oo-text-abbrev-table "bookmarkd" "bookmarked")
(define-abbrev oo-text-abbrev-table "whatev" "whatever")
(define-abbrev oo-text-abbrev-table "simplyfing" "simplifying")
(define-abbrev oo-text-abbrev-table "satisfiying" "satisfying")
(define-abbrev oo-text-abbrev-table "chara" "character")
(define-abbrev oo-text-abbrev-table "interediary" "intermediary")
(define-abbrev oo-text-abbrev-table "agan" "again")
(define-abbrev oo-text-abbrev-table "spefically" "specifically")
(define-abbrev oo-text-abbrev-table "certa" "certain")
(define-abbrev oo-text-abbrev-table "godod" "good")
(define-abbrev oo-text-abbrev-table "wlel" "well")
(define-abbrev oo-text-abbrev-table "temporl" "temporarily")
(define-abbrev oo-text-abbrev-table "proba" "probably")
(define-abbrev oo-text-abbrev-table "prob" "problem")
(define-abbrev oo-text-abbrev-table "bookms" "bookmarks")
(define-abbrev oo-text-abbrev-table "anythig" "anything")
(define-abbrev oo-text-abbrev-table "boookmark" "bookmark")
(define-abbrev oo-text-abbrev-table "sess" "session")
(define-abbrev oo-text-abbrev-table "bookmaks" "bookmarks")
(define-abbrev oo-text-abbrev-table "supp" "support")
(define-abbrev oo-text-abbrev-table "betw" "between")
(define-abbrev oo-text-abbrev-table "tat" "that")
(define-abbrev oo-text-abbrev-table "arbi" "arbitrary")
(define-abbrev oo-text-abbrev-table "regiser" "register")
(define-abbrev oo-text-abbrev-table "afaict" "as far as I can tell")
(define-abbrev oo-text-abbrev-table "writig" "writing")
(define-abbrev oo-text-abbrev-table "thme" "them")
(define-abbrev oo-text-abbrev-table "nesly" "necessarily")
(define-abbrev oo-text-abbrev-table "enof" "enough")
(define-abbrev oo-text-abbrev-table "andto" "and to")
(define-abbrev oo-text-abbrev-table "mins" "minutes")
(define-abbrev oo-text-abbrev-table "happengin" "happening")
(define-abbrev oo-text-abbrev-table "tme" "time")
(define-abbrev oo-text-abbrev-table "sente" "sentence")
(define-abbrev oo-text-abbrev-table "begi" "beginning")
(define-abbrev oo-text-abbrev-table "aroudn" "around")
(define-abbrev oo-text-abbrev-table "xpansion" "expansion")
(define-abbrev oo-text-abbrev-table "nt" "not")
(define-abbrev oo-text-abbrev-table "entier" "entire")
(define-abbrev oo-text-abbrev-table "unfor" "unfortunately")
(define-abbrev oo-text-abbrev-table "applicatioin" "application")
(define-abbrev oo-text-abbrev-table "dirs" "directories")
(define-abbrev oo-text-abbrev-table "avg" "average")
(define-abbrev oo-text-abbrev-table "aleady" "already")
(define-abbrev oo-text-abbrev-table "happ" "happy")
(define-abbrev oo-text-abbrev-table "capitalizatoin" "capitalization")
(define-abbrev oo-text-abbrev-table "anem" "name")
(define-abbrev oo-text-abbrev-table "contrl" "control")
(define-abbrev oo-text-abbrev-table "jumpt" "jump to")
(define-abbrev oo-text-abbrev-table "thatt" "that")
(define-abbrev oo-text-abbrev-table "lcoation" "location")
(define-abbrev oo-text-abbrev-table "settingns" "settings")
(define-abbrev oo-text-abbrev-table "recom" "recommended")
(define-abbrev oo-text-abbrev-table "unwiedly" "unwieldy")
(define-abbrev oo-text-abbrev-table "bufer" "buffer")
(define-abbrev oo-text-abbrev-table "takin" "taking")
(define-abbrev oo-text-abbrev-table "thatd" "that would")
(define-abbrev oo-text-abbrev-table "delimeter" "delimiter")
(define-abbrev oo-text-abbrev-table "defualt" "default")
(define-abbrev oo-text-abbrev-table "creae" "create")
(define-abbrev oo-text-abbrev-table "reqs" "requirements")
(define-abbrev oo-text-abbrev-table "mabe" "maybe")
(define-abbrev oo-text-abbrev-table "ti" "it")
(define-abbrev oo-text-abbrev-table "bufers" "buffers")
(define-abbrev oo-text-abbrev-table "bookmakrs" "bookmarks")
(define-abbrev oo-text-abbrev-table "ais" "as it stands,")
(define-abbrev oo-text-abbrev-table "ais" "as it stands")
(define-abbrev oo-text-abbrev-table "frmae" "frame")
(define-abbrev oo-text-abbrev-table "somehwo" "somehow")
(define-abbrev oo-text-abbrev-table "wa" "what")
(define-abbrev oo-text-abbrev-table "advisig" "advising")
(define-abbrev oo-text-abbrev-table "inadvertedly" "inadvertently")
(define-abbrev oo-text-abbrev-table "aamof" "as a matter of fact")
(define-abbrev oo-text-abbrev-table "eamcs" "Emacs")
(define-abbrev oo-text-abbrev-table "oep" "open")
(define-abbrev oo-text-abbrev-table "tendencis" "tendencies")
(define-abbrev oo-text-abbrev-table "magitcal" "magical")
(define-abbrev oo-text-abbrev-table "perosnally" "personally")
(define-abbrev oo-text-abbrev-table "successfullyy" "successfully")
(define-abbrev oo-text-abbrev-table "thatss" "that is")
(define-abbrev oo-text-abbrev-table "nwo" "now")
(define-abbrev oo-text-abbrev-table "determne" "determine")
(define-abbrev oo-text-abbrev-table "abbreviatons" "abbreviations")
(define-abbrev oo-text-abbrev-table "norml" "normal")
(define-abbrev oo-text-abbrev-table "inappripriate" "inappropriate")
(define-abbrev oo-text-abbrev-table "enalbe" "enable")
(define-abbrev oo-text-abbrev-table "realestate" "real-estate.")
(define-abbrev oo-text-abbrev-table "scrreen" "screen")
(define-abbrev oo-text-abbrev-table "prop" "property")
(define-abbrev oo-text-abbrev-table "rfine" "refine")
(define-abbrev oo-text-abbrev-table "previosu" "previous")
(define-abbrev oo-text-abbrev-table "ther" "there")
(define-abbrev oo-text-abbrev-table "rote" "wrote")
(define-abbrev oo-text-abbrev-table "partl" "partly")
(define-abbrev oo-text-abbrev-table "ro" "or")
(define-abbrev oo-text-abbrev-table "abbrrevs" "abbrevs")
(define-abbrev oo-text-abbrev-table "sev" "several")
(define-abbrev oo-text-abbrev-table "procise" "precise")
(define-abbrev oo-text-abbrev-table "whenn" "when")
(define-abbrev oo-text-abbrev-table "rounda" "roundabout")
(define-abbrev oo-text-abbrev-table "lisence" "license")
(define-abbrev oo-text-abbrev-table "liscence" "license")
(define-abbrev oo-text-abbrev-table "generatioin" "generation")
(define-abbrev oo-text-abbrev-table "divishion" "division")
(define-abbrev oo-text-abbrev-table "simialr" "similar")
(define-abbrev oo-text-abbrev-table "cmnt" "comment")
(define-abbrev oo-text-abbrev-table "whites" "whitespace")
(define-abbrev oo-text-abbrev-table "dup" "duplicate")
(define-abbrev oo-text-abbrev-table "dupli" "duplicate")
(define-abbrev oo-text-abbrev-table "commentar" "commentary")
(define-abbrev oo-text-abbrev-table "ppress" "press")
(define-abbrev oo-text-abbrev-table "keybs" "keybindings")
(define-abbrev oo-text-abbrev-table "reqed" "required")
(define-abbrev oo-text-abbrev-table "examinging" "examining")
(define-abbrev oo-text-abbrev-table "functinos" "functions")
(define-abbrev oo-text-abbrev-table "iuwt" "if you want to")
(define-abbrev oo-text-abbrev-table "teating" "treating")
(define-abbrev oo-text-abbrev-table "abbort" "abort")
(define-abbrev oo-text-abbrev-table "essntially" "essentially")
(define-abbrev oo-text-abbrev-table "functoins" "functions")
(define-abbrev oo-text-abbrev-table "loeaded" "loaded")
(define-abbrev oo-text-abbrev-table "appropr" "appropriate")
(define-abbrev oo-text-abbrev-table "pt" "point")
(define-abbrev oo-text-abbrev-table "befo" "before")
(define-abbrev oo-text-abbrev-table "ottomh" "off the top of my head")
(define-abbrev oo-text-abbrev-table "anon" "anonymous")
(define-abbrev oo-text-abbrev-table "gening" "generating")
(define-abbrev oo-text-abbrev-table "aoy" "as of yet")
(define-abbrev oo-text-abbrev-table "sillence" "silence")
(define-abbrev oo-text-abbrev-table "updadte" "update")
(define-abbrev oo-text-abbrev-table "rnadom" "random")
(define-abbrev oo-text-abbrev-table "deps" "dependencies")
(define-abbrev oo-text-abbrev-table "req" "require")
(define-abbrev oo-text-abbrev-table "reqm" "requirement")
(define-abbrev oo-text-abbrev-table "udate" "update")
(define-abbrev oo-text-abbrev-table "cnfig" "configuration")
(define-abbrev oo-text-abbrev-table "orners" "corners")
(define-abbrev oo-text-abbrev-table "sometiems" "sometimes")
(define-abbrev oo-text-abbrev-table "abstractioins" "abstractions")
(define-abbrev oo-text-abbrev-table "capt" "captain")
(define-abbrev oo-text-abbrev-table "loadingn" "loading")
(define-abbrev oo-text-abbrev-table "shoudnt" "should not")
(define-abbrev oo-text-abbrev-table "actu" "actually")
(define-abbrev oo-text-abbrev-table "lke" "like")
(define-abbrev oo-text-abbrev-table "tother" "together")
(define-abbrev oo-text-abbrev-table "usng" "using")
(define-abbrev oo-text-abbrev-table "advoid" "avoid")
(define-abbrev oo-text-abbrev-table "bytecomp" "byte-compilation")
(define-abbrev oo-text-abbrev-table "dupl" "duplicate")
(define-abbrev oo-text-abbrev-table "err" "error")
(define-abbrev oo-text-abbrev-table "repeateadly" "repeatedly")
(define-abbrev oo-text-abbrev-table "wtim" "with this in mind")
(define-abbrev oo-text-abbrev-table "dingly" "accordingly")
(define-abbrev oo-text-abbrev-table "ued" "used")
(define-abbrev oo-text-abbrev-table "consice" "concise")
(define-abbrev oo-text-abbrev-table "doenst" "does not")
(define-abbrev oo-text-abbrev-table "descr" "description")
(define-abbrev oo-text-abbrev-table "vai" "via")
(define-abbrev oo-text-abbrev-table "laoded" "loaded")
(define-abbrev oo-text-abbrev-table "mprove" "improve")
(define-abbrev oo-text-abbrev-table "errs" "errors")
(define-abbrev oo-text-abbrev-table "vals" "values")
(define-abbrev oo-text-abbrev-table "env" "environment")
(define-abbrev oo-text-abbrev-table "fomr" "form")
(define-abbrev oo-text-abbrev-table "upadte" "update")
(define-abbrev oo-text-abbrev-table "deling" "deleting")
(define-abbrev oo-text-abbrev-table "inst" "instead")
(define-abbrev oo-text-abbrev-table "abrevs" "abbrevs")
(define-abbrev oo-text-abbrev-table "cpies" "copies")
(define-abbrev oo-text-abbrev-table "memor" "memory")
(define-abbrev oo-text-abbrev-table "mch" "much")
(define-abbrev oo-text-abbrev-table "durat" "duration")
(define-abbrev oo-text-abbrev-table "buidls" "builds")
(define-abbrev oo-text-abbrev-table "asb" "as specified by")
(define-abbrev oo-text-abbrev-table "defering" "deferring")
(define-abbrev oo-text-abbrev-table "temr" "term")
(define-abbrev oo-text-abbrev-table "exs" "examples")
(define-abbrev oo-text-abbrev-table "suport" "support")
(define-abbrev oo-text-abbrev-table "oftne" "often")
(define-abbrev oo-text-abbrev-table "packae" "package")
(define-abbrev oo-text-abbrev-table "cmnts" "comments")
(define-abbrev oo-text-abbrev-table "lata" "later")
(define-abbrev oo-text-abbrev-table "ifo" "in favor of")
(define-abbrev oo-text-abbrev-table "thes" "these")
(define-abbrev oo-text-abbrev-table "prelim" "preliminary")
(define-abbrev oo-text-abbrev-table "buff" "buffer")
(define-abbrev oo-text-abbrev-table "raied" "raised")
(define-abbrev oo-text-abbrev-table "cmt" "comment")
(define-abbrev oo-text-abbrev-table "rased" "raised")
(define-abbrev oo-text-abbrev-table "boudn" "bound")
(define-abbrev oo-text-abbrev-table "commnt" "comment")
(define-abbrev oo-text-abbrev-table "commendt" "comment")
(define-abbrev oo-text-abbrev-table "hnl" "honestly")
(define-abbrev oo-text-abbrev-table "textobj" "text-object")
(define-abbrev oo-text-abbrev-table "kbds" "keybindings")
(define-abbrev oo-text-abbrev-table "canceled" "cancelled")
(define-abbrev oo-text-abbrev-table "ins" "insert")
(define-abbrev oo-text-abbrev-table "bds" "bindings")
(define-abbrev oo-text-abbrev-table "bd" "binding")
(define-abbrev oo-text-abbrev-table "kbd" "keybinding")
(define-abbrev oo-text-abbrev-table "cmds" "commands")
(define-abbrev oo-text-abbrev-table "cmd" "command")
(define-abbrev oo-text-abbrev-table "ae" "are")
(define-abbrev oo-text-abbrev-table "gral" "general")
(define-abbrev oo-text-abbrev-table "progrress" "progress")
(define-abbrev oo-text-abbrev-table "perf" "perfect")
(define-abbrev oo-text-abbrev-table "separ" "separate")
(define-abbrev oo-text-abbrev-table "mgs" "message")
(define-abbrev oo-text-abbrev-table "wrld" "world")
(define-abbrev oo-text-abbrev-table "wich" "which")
(define-abbrev oo-text-abbrev-table "msg" "message")
(define-abbrev oo-text-abbrev-table "mesage" "message")
(define-abbrev oo-text-abbrev-table "sems" "seems")
(define-abbrev oo-text-abbrev-table "rem" "remove")
(define-abbrev oo-text-abbrev-table "bod" "body")
(define-abbrev oo-text-abbrev-table "defing" "defining")
(define-abbrev oo-text-abbrev-table "awkard" "akward")
(define-abbrev oo-text-abbrev-table "recos" "recommends")
(define-abbrev oo-text-abbrev-table "binds" "bindings")
(define-abbrev oo-text-abbrev-table "nd" "and")
(define-abbrev oo-text-abbrev-table "approp" "appropriate")
(define-abbrev oo-text-abbrev-table "aprop" "appropriate")
(define-abbrev oo-text-abbrev-table "lexi" "lexicographically")
(define-abbrev oo-text-abbrev-table "econfig" "Emacs configuration")
(define-abbrev oo-text-abbrev-table "consec" "consecutive")
(define-abbrev oo-text-abbrev-table "conseq" "consequence")
(define-abbrev oo-text-abbrev-table "paces" "spaces")
(define-abbrev oo-text-abbrev-table "beh" "behavior")
(define-abbrev oo-text-abbrev-table "comnt" "comment")
(define-abbrev oo-text-abbrev-table "keybind" "keybinding")
(define-abbrev oo-text-abbrev-table "kbind" "keybinding")
(define-abbrev oo-text-abbrev-table "keybinds" "keybindings")
(define-abbrev oo-text-abbrev-table "kbinds" "keybindings")
(define-abbrev oo-text-abbrev-table "bcomp" "byte-compilation")
(define-abbrev oo-text-abbrev-table "unness" "unnecessary")
(define-abbrev oo-text-abbrev-table "coment" "comment")
(define-abbrev oo-text-abbrev-table "fror" "for")
(define-abbrev oo-text-abbrev-table "stup" "setup")
(define-abbrev oo-text-abbrev-table "inclinaition" "inclination")
(define-abbrev oo-text-abbrev-table "tring" "trying")
(define-abbrev oo-text-abbrev-table "wanna" "want to")
(define-abbrev oo-text-abbrev-table "effor" "effort")
(define-abbrev oo-text-abbrev-table "undef" "undefined")
(define-abbrev oo-text-abbrev-table "sym" "symbol")
(define-abbrev oo-text-abbrev-table "wre" "were")
(define-abbrev oo-text-abbrev-table "ws" "was")
(define-abbrev oo-text-abbrev-table "probs" "problems")
(define-abbrev oo-text-abbrev-table "syms" "symbols")
(define-abbrev oo-text-abbrev-table "tbs" "that being said")
(define-abbrev oo-text-abbrev-table "evalu" "evaluation")
(define-abbrev oo-text-abbrev-table "oside" "outside")
(define-abbrev oo-text-abbrev-table "bside" "beside")
(define-abbrev oo-text-abbrev-table "sumes" "assumes")
(define-abbrev oo-text-abbrev-table "evaling" "evaluating")
(define-abbrev oo-text-abbrev-table "res" "result")
(define-abbrev oo-text-abbrev-table "srcc" "source")
(define-abbrev oo-text-abbrev-table "sytle" "style")
(define-abbrev oo-text-abbrev-table "elt" "element")
(define-abbrev oo-text-abbrev-table "elts" "elements")
(define-abbrev oo-text-abbrev-table "gens" "generates")
(define-abbrev oo-text-abbrev-table "understandibly" "understandably")
(define-abbrev oo-text-abbrev-table "subborn" "stubborn")
(define-abbrev oo-text-abbrev-table "dever" "developer")
(define-abbrev oo-text-abbrev-table "devv" "development")
(define-abbrev oo-text-abbrev-table "mgiht" "might")
(define-abbrev oo-text-abbrev-table "despa" "desparate")
(define-abbrev oo-text-abbrev-table "progg" "programming")
(define-abbrev oo-text-abbrev-table "ttit" "the thing is that")
(define-abbrev oo-text-abbrev-table "tti" "the thing is")
(define-abbrev oo-text-abbrev-table "paht" "path")
(define-abbrev oo-text-abbrev-table "val" "value")
(define-abbrev oo-text-abbrev-table "optioinal" "optional")
(define-abbrev oo-text-abbrev-table "homogenous" "homogeneous")
(define-abbrev oo-text-abbrev-table "awa" "as well as")
(define-abbrev oo-text-abbrev-table "simul" "simultaneously")
(define-abbrev oo-text-abbrev-table "simultanouesly" "simultaneously")
(define-abbrev oo-text-abbrev-table "struct" "structure")
(define-abbrev oo-text-abbrev-table "structs" "structures")
(define-abbrev oo-text-abbrev-table "acces" "access")
(define-abbrev oo-text-abbrev-table "comm" "common")
(define-abbrev oo-text-abbrev-table "corr" "corresponding")
(define-abbrev oo-text-abbrev-table "expr" "expression")
(define-abbrev oo-text-abbrev-table "builtin" "built-in")
(define-abbrev oo-text-abbrev-table "elems" "elements")
(define-abbrev oo-text-abbrev-table "elem" "element")
(define-abbrev oo-text-abbrev-table "nones" "nonessential")
(define-abbrev oo-text-abbrev-table "abt" "about")
(define-abbrev oo-text-abbrev-table "yt" "youtube")
(define-abbrev oo-text-abbrev-table "iadt" "in addition to this")
(define-abbrev oo-text-abbrev-table "tldr" "TLDR")
(define-abbrev oo-text-abbrev-table "mo" "more")
(define-abbrev oo-text-abbrev-table "opt" "option")
(define-abbrev oo-text-abbrev-table "thro" "through")
(define-abbrev oo-text-abbrev-table "alowed" "allowed")
(define-abbrev oo-text-abbrev-table "allowd" "allowed")
(define-abbrev oo-text-abbrev-table "pefect" "perfect")
(define-abbrev oo-text-abbrev-table "negy" "negatively")
(define-abbrev oo-text-abbrev-table "neg" "negative")
(define-abbrev oo-text-abbrev-table "eff" "effect")
(define-abbrev oo-text-abbrev-table "weras" "whereas")
(define-abbrev oo-text-abbrev-table "fol" "following")
(define-abbrev oo-text-abbrev-table "foll" "following")
(define-abbrev oo-text-abbrev-table "ooh" "out of hand")
(define-abbrev oo-text-abbrev-table "combi" "combination")
(define-abbrev oo-text-abbrev-table "ingen" "in general")
(define-abbrev oo-text-abbrev-table "gened" "generated")
(define-abbrev oo-text-abbrev-table "aload" "autoload")
(define-abbrev oo-text-abbrev-table "amt" "amount")
(define-abbrev oo-text-abbrev-table "amoutn" "amount")
(define-abbrev oo-text-abbrev-table "lvl" "level")
(define-abbrev oo-text-abbrev-table "cd" "could")
(define-abbrev oo-text-abbrev-table "cud" "could")
(define-abbrev oo-text-abbrev-table "infor" "information")
(define-abbrev oo-text-abbrev-table "isn" "is not")
(define-abbrev oo-text-abbrev-table "thhe" "the")
(define-abbrev oo-text-abbrev-table "ques" "question")
(define-abbrev oo-text-abbrev-table "arg" "argument")
(define-abbrev oo-text-abbrev-table "equiv" "equivalent")
(define-abbrev oo-text-abbrev-table "mmend" "recommend")
(define-abbrev oo-text-abbrev-table "del" "delete")
(define-abbrev oo-text-abbrev-table "desc" "description")
(define-abbrev oo-text-abbrev-table "hes" "he is")
(define-abbrev oo-text-abbrev-table "impressoin" "impression")
(define-abbrev oo-text-abbrev-table "wsa" "was")
(define-abbrev oo-text-abbrev-table "var" "variable")
(define-abbrev oo-text-abbrev-table "vars" "variables")
(define-abbrev oo-text-abbrev-table "macroexp" "macro expansion")
(define-abbrev oo-text-abbrev-table "coments" "comments")
(define-abbrev oo-text-abbrev-table "unes" "unnecessary")
(define-abbrev oo-text-abbrev-table "uness" "unnecessary")
(define-abbrev oo-text-abbrev-table "dk" "do not know")
(define-abbrev oo-text-abbrev-table "emacss" "Emacs's")
(define-abbrev oo-text-abbrev-table "ess" "essentially")
(define-abbrev oo-text-abbrev-table "sist" "consistent")
(define-abbrev oo-text-abbrev-table "initing" "initializing")
(define-abbrev oo-text-abbrev-table "fnames" "filenames")
(define-abbrev oo-text-abbrev-table "misc" "miscellaneous")
(define-abbrev oo-text-abbrev-table "imml" "immediately")
(define-abbrev oo-text-abbrev-table "imm" "immediate")
(define-abbrev oo-text-abbrev-table "evv" "everything")
(define-abbrev oo-text-abbrev-table "abut" "about")
(define-abbrev oo-text-abbrev-table "movo" "moreover")
(define-abbrev oo-text-abbrev-table "dandylion" "dandelion")
(define-abbrev oo-text-abbrev-table "dandylions" "dandelions")
(define-abbrev oo-text-abbrev-table "bev" "bird's-eye view")
(define-abbrev oo-text-abbrev-table "thot" "thought")
(define-abbrev oo-text-abbrev-table "tmmw" "to make matters worse")
(define-abbrev oo-text-abbrev-table "freq" "frequency")
(define-abbrev oo-text-abbrev-table "pertubed" "perturbed")
(define-abbrev oo-text-abbrev-table "si" "is")
(define-abbrev oo-text-abbrev-table "vs" "versus")
(define-abbrev oo-text-abbrev-table "mor" "more")
(define-abbrev oo-text-abbrev-table "configing" "configuring")
(define-abbrev oo-text-abbrev-table "aume" "as you might expect")
(define-abbrev oo-text-abbrev-table "ayme" "as you might expect")
(define-abbrev oo-text-abbrev-table "tss" "timestamps")
(define-abbrev oo-text-abbrev-table "ts" "timestamp")
(define-abbrev oo-text-abbrev-table "obj" "object")
(define-abbrev oo-text-abbrev-table "oop" "object-oriented-programming")
(define-abbrev oo-text-abbrev-table "ood" "object-oriented-design")
(define-abbrev oo-text-abbrev-table "hwat" "what")
(define-abbrev oo-text-abbrev-table "sep" "separate")
(define-abbrev oo-text-abbrev-table "utube" "youtube")
(define-abbrev oo-text-abbrev-table "hav" "have")
(define-abbrev oo-text-abbrev-table "ootq" "out of the question")
(define-abbrev oo-text-abbrev-table "tte" "to this end")
(define-abbrev oo-text-abbrev-table "wasnt" "was not")
(define-abbrev oo-text-abbrev-table "ult" "ultimate")
(define-abbrev oo-text-abbrev-table "ultl" "ultimately")
(define-abbrev oo-text-abbrev-table "aia" "all in all")
(define-abbrev oo-text-abbrev-table "soly" "solely")
(define-abbrev oo-text-abbrev-table "idnwt" "I do not want to")
(define-abbrev oo-text-abbrev-table "coll" "collection")
(define-abbrev oo-text-abbrev-table "hadnt" "had not")
(define-abbrev oo-text-abbrev-table "suces" "success")
(define-abbrev oo-text-abbrev-table "sucess" "success")
(define-abbrev oo-text-abbrev-table "accros" "across")
(define-abbrev oo-text-abbrev-table "resonable" "reasonable")
(define-abbrev oo-text-abbrev-table "sec" "second")
(define-abbrev oo-text-abbrev-table "secs" "seconds")
(define-abbrev oo-text-abbrev-table "reco" "recommended")
(define-abbrev oo-text-abbrev-table "sth" "something")
(define-abbrev oo-text-abbrev-table "ath" "anything")
(define-abbrev oo-text-abbrev-table "corsor" "cursor")
(define-abbrev oo-text-abbrev-table "sdb" "should not be")
(define-abbrev oo-text-abbrev-table "rihgt" "right")
(define-abbrev oo-text-abbrev-table "shdnt" "should not")
(define-abbrev oo-text-abbrev-table "aycs" "as you can see")
(define-abbrev oo-text-abbrev-table "twisi" "the way I see it")
(define-abbrev oo-text-abbrev-table "fnr" "for no reason")
(define-abbrev oo-text-abbrev-table "mk" "make")
(define-abbrev oo-text-abbrev-table "prases" "phrases")
(define-abbrev oo-text-abbrev-table "thse" "these")
(define-abbrev oo-text-abbrev-table "english" "English")
(define-abbrev oo-text-abbrev-table "nuf" "enough")
(define-abbrev oo-text-abbrev-table "idek" "I did not even know")
(define-abbrev oo-text-abbrev-table "cur" "current")
(define-abbrev oo-text-abbrev-table "curr" "current")
(define-abbrev oo-text-abbrev-table "onl" "only")
(define-abbrev oo-text-abbrev-table "uve" "you have")
(define-abbrev oo-text-abbrev-table "revaled" "re-evaluated")
(define-abbrev oo-text-abbrev-table "idid" "I did")
(define-abbrev oo-text-abbrev-table "tres" "interesting")
(define-abbrev oo-text-abbrev-table "ml" "mode line")
;; ("def" "definitely")
(define-abbrev oo-text-abbrev-table "docc" "documentation")
(define-abbrev oo-text-abbrev-table "nfo" "information")
(define-abbrev oo-text-abbrev-table "correclty" "correctly")
(define-abbrev oo-text-abbrev-table "coudl" "could")
(define-abbrev oo-text-abbrev-table "oofone" "O(1)")
(define-abbrev oo-text-abbrev-table "iml" "immediately")
(define-abbrev oo-text-abbrev-table "theyre" "they are")
(define-abbrev oo-text-abbrev-table "punc" "punctuation")
(define-abbrev oo-text-abbrev-table "dling" "downloading")
(define-abbrev oo-text-abbrev-table "ez" "easy")
(define-abbrev oo-text-abbrev-table "fol" "follow")
(define-abbrev oo-text-abbrev-table "popl" "populate")
(define-abbrev oo-text-abbrev-table "als" "autoloads")
(define-abbrev oo-text-abbrev-table "alo" "autoload")
(define-abbrev oo-text-abbrev-table "ootw" "out of the way")
(define-abbrev oo-text-abbrev-table "gen" "generate")
(define-abbrev oo-text-abbrev-table "aloads" "autoloads")
(define-abbrev oo-text-abbrev-table "alods" "autoloads")
(define-abbrev oo-text-abbrev-table "dls" "downloads")
(define-abbrev oo-text-abbrev-table "lize" "realize")
(define-abbrev oo-text-abbrev-table "hwo" "how")
(define-abbrev oo-text-abbrev-table "tbe" "to be exact")
(define-abbrev oo-text-abbrev-table "chars" "characters")
(define-abbrev oo-text-abbrev-table "heres" "here is")
(define-abbrev oo-text-abbrev-table "hesi" "hesitant")
(define-abbrev oo-text-abbrev-table "ex" "example")
(define-abbrev oo-text-abbrev-table "xample" "example")
(define-abbrev oo-text-abbrev-table "cna" "can")
(define-abbrev oo-text-abbrev-table "ord" "order")
(define-abbrev oo-text-abbrev-table "cate" "category")
(define-abbrev oo-text-abbrev-table "nyt" "anything")
(define-abbrev oo-text-abbrev-table "mena" "mean")
(define-abbrev oo-text-abbrev-table "doin" "doing")
(define-abbrev oo-text-abbrev-table "na" "an")
(define-abbrev oo-text-abbrev-table "somethig" "something")
(define-abbrev oo-text-abbrev-table "iac" "in any case")
(define-abbrev oo-text-abbrev-table "di" "do it")
(define-abbrev oo-text-abbrev-table "intro" "introduction")
(define-abbrev oo-text-abbrev-table "tha" "that")
(define-abbrev oo-text-abbrev-table "char" "character")
(define-abbrev oo-text-abbrev-table "wt" "want to")
(define-abbrev oo-text-abbrev-table "hava" "have a")
(define-abbrev oo-text-abbrev-table "deflt" "default")
(define-abbrev oo-text-abbrev-table "fname" "filename")
(define-abbrev oo-text-abbrev-table "ta" "that")
(define-abbrev oo-text-abbrev-table "itl" "it will")
(define-abbrev oo-text-abbrev-table "itll" "it will")
(define-abbrev oo-text-abbrev-table "mott" "most of the time")
(define-abbrev oo-text-abbrev-table "sd" "should")
(define-abbrev oo-text-abbrev-table "shd" "should")
(define-abbrev oo-text-abbrev-table "eelm" "emacs-lisp-mode")
(define-abbrev oo-text-abbrev-table "eemacs" "Emacs")
(define-abbrev oo-text-abbrev-table "alot" "a lot")
(define-abbrev oo-text-abbrev-table "moro" "moreover")
(define-abbrev oo-text-abbrev-table "orig" "original")
(define-abbrev oo-text-abbrev-table "iat" "in addition to")
(define-abbrev oo-text-abbrev-table "elispp" "emacs-lisp")
(define-abbrev oo-text-abbrev-table "idl" "I would like")
;; "id" is actually a word, but I use it so infrequently and I use the phrase. Nil :enable-function oo-enable-text-abbrev-pI
;; would so frequently that it is worth having it be an abbrev for I nil :enable-function oo-enable-text-abbrev-p.
(define-abbrev oo-text-abbrev-table "prec" "precedence")
(define-abbrev oo-text-abbrev-table "wdimbt" "what do I mean by this")
(define-abbrev oo-text-abbrev-table "wdim" "what do I mean")
(define-abbrev oo-text-abbrev-table "awn" "also worth noting")
(define-abbrev oo-text-abbrev-table "int" "I need to")
(define-abbrev oo-text-abbrev-table "wch" "which")
(define-abbrev oo-text-abbrev-table "ch" "which")
(define-abbrev oo-text-abbrev-table "igts" "I have got to say")
(define-abbrev oo-text-abbrev-table "ihtbs" "it has to be said")
(define-abbrev oo-text-abbrev-table "wd" "would")
(define-abbrev oo-text-abbrev-table "freql" "frequently")
(define-abbrev oo-text-abbrev-table "ifreql" "infrequently")
(define-abbrev oo-text-abbrev-table "infreql" "infrequently")
(define-abbrev oo-text-abbrev-table "id" "I would")
(define-abbrev oo-text-abbrev-table "wan" "want")
(define-abbrev oo-text-abbrev-table "idht" "I do not have to")
(define-abbrev oo-text-abbrev-table "hvae" "have")
(define-abbrev oo-text-abbrev-table "cann" "cannot")
(define-abbrev oo-text-abbrev-table "icj" "I can just")
(define-abbrev oo-text-abbrev-table "ic" "I can")
(define-abbrev oo-text-abbrev-table "ure" "you are")
(define-abbrev oo-text-abbrev-table "lhp" "Luis Henriquez-Perez")
(define-abbrev oo-text-abbrev-table "noly" "not only")
(define-abbrev oo-text-abbrev-table "specy" "specifically")
(define-abbrev oo-text-abbrev-table "rl" "really")
(define-abbrev oo-text-abbrev-table "argss" "arguments")
(define-abbrev oo-text-abbrev-table "ppl" "people")
(define-abbrev oo-text-abbrev-table "urself" "yourself")
(define-abbrev oo-text-abbrev-table "ab" "about")
(define-abbrev oo-text-abbrev-table "ret" "return")
(define-abbrev oo-text-abbrev-table "tn" "then")
(define-abbrev oo-text-abbrev-table "blv" "believe")
(define-abbrev oo-text-abbrev-table "nto" "not")
(define-abbrev oo-text-abbrev-table "mone" "money")
(define-abbrev oo-text-abbrev-table "hve" "have")
(define-abbrev oo-text-abbrev-table "swich" "switch")
(define-abbrev oo-text-abbrev-table "actuall" "actually")
(define-abbrev oo-text-abbrev-table "evalt" "evaluate")
(define-abbrev oo-text-abbrev-table "asap" "A.S.A.P.")
(define-abbrev oo-text-abbrev-table "econf" "emacs configuration")
(define-abbrev oo-text-abbrev-table "alth" "although")
(define-abbrev oo-text-abbrev-table "esp" "especially")
;; This clashes with the word "ill" but I barely use that word. In the rar nil :enable-function oo-enable-text-abbrev-pe
;; event where I do need to use it I will unexpand it nil :enable-function oo-enable-text-abbrev-p.
(define-abbrev oo-text-abbrev-table "ill" "I will")
;; This is a common abbrev for "by the way" but I feel like I do not really us nil :enable-function oo-enable-text-abbrev-pe
;; that phrase unless I am texting nil :enable-function oo-enable-text-abbrev-p.
(define-abbrev oo-text-abbrev-table "imd" "immediately")
(define-abbrev oo-text-abbrev-table "exand" "expand")
(define-abbrev oo-text-abbrev-table "ppet" "snippet")
(define-abbrev oo-text-abbrev-table "tse" "these")
(define-abbrev oo-text-abbrev-table "usu" "usually")
(define-abbrev oo-text-abbrev-table "iprac" "in practice")
(define-abbrev oo-text-abbrev-table "efy" "efficiency")
(define-abbrev oo-text-abbrev-table "evr" "everything")
(define-abbrev oo-text-abbrev-table "sen" "seen")
(define-abbrev oo-text-abbrev-table "wat" "what")
(define-abbrev oo-text-abbrev-table "dfl" "default")
(define-abbrev oo-text-abbrev-table "dflt" "default")
(define-abbrev oo-text-abbrev-table "difr" "differ")
(define-abbrev oo-text-abbrev-table "btw" "between")
(define-abbrev oo-text-abbrev-table "dif" "different")
(define-abbrev oo-text-abbrev-table "diff" "different")
(define-abbrev oo-text-abbrev-table "htat" "that")
(define-abbrev oo-text-abbrev-table "rnt" "are not")
(define-abbrev oo-text-abbrev-table "arent" "are not")
(define-abbrev oo-text-abbrev-table "tt" "the")
(define-abbrev oo-text-abbrev-table "len" "length")
(define-abbrev oo-text-abbrev-table "bf" "before")
(define-abbrev oo-text-abbrev-table "aft" "after")
(define-abbrev oo-text-abbrev-table "af" "at first")
(define-abbrev oo-text-abbrev-table "oft" "often")
(define-abbrev oo-text-abbrev-table "dsnt" "does not")
(define-abbrev oo-text-abbrev-table "ihdbtk" "I had been thinking")
(define-abbrev oo-text-abbrev-table "ihdb" "I had been")
(define-abbrev oo-text-abbrev-table "ihb" "I have been")
(define-abbrev oo-text-abbrev-table "ihbtk" "I have been thinking")
(define-abbrev oo-text-abbrev-table "ihbtkt" "I have been thinking that")
(define-abbrev oo-text-abbrev-table "ihbtkti" "I have been thinking that I")
(define-abbrev oo-text-abbrev-table "ihbtka" "I have been thinking about")
(define-abbrev oo-text-abbrev-table "comptia" "CompTIA")
(define-abbrev oo-text-abbrev-table "gt" "get")
(define-abbrev oo-text-abbrev-table "wev" "whatever")
(define-abbrev oo-text-abbrev-table "jbos" "jobs")
(define-abbrev oo-text-abbrev-table "theyll" "they will")
(define-abbrev oo-text-abbrev-table "prevl" "previously")
(define-abbrev oo-text-abbrev-table "prev" "previous")
(define-abbrev oo-text-abbrev-table "ivs" "I have seen")
(define-abbrev oo-text-abbrev-table "rxp" "regular expression")
(define-abbrev oo-text-abbrev-table "rx" "regular expression")
(define-abbrev oo-text-abbrev-table "dl" "download")
(define-abbrev oo-text-abbrev-table "vcc" "version control")
(define-abbrev oo-text-abbrev-table "wil" "will")
(define-abbrev oo-text-abbrev-table "shiftk" "SHIFT")
(define-abbrev oo-text-abbrev-table "nots" "number of times")
(define-abbrev oo-text-abbrev-table "num" "number")
(define-abbrev oo-text-abbrev-table "lins" "lines")
;; I thought that this could be a bad abbrev because it is too much line. Nil :enable-function oo-enable-text-abbrev-pa
;; spelling mistake of =the=, but then I thought if I do misspell "the" it I nil :enable-function oo-enable-text-abbrev-ps
;; very unlikely I will do so by pressing =t= again nil :enable-function oo-enable-text-abbrev-p.
(define-abbrev oo-text-abbrev-table "tht" "thought")
(define-abbrev oo-text-abbrev-table "i" "I")
(define-abbrev oo-text-abbrev-table "luis" "Luis")
;; This will not work because ";" is not a work constituent. I need to us nil :enable-function oo-enable-text-abbrev-pe
;; `aas' for this or come up with some other solution nil :enable-function oo-enable-text-abbrev-p.
;; (";;" ".")
;; TODO: move to spell-fixing abbrev nil :enable-function oo-enable-text-abbrev-p.
(define-abbrev oo-text-abbrev-table "ivb" "I have been")
(define-abbrev oo-text-abbrev-table "werent" "were not")
(define-abbrev oo-text-abbrev-table "rly" "really")
(define-abbrev oo-text-abbrev-table "aagp" "at any given point")
(define-abbrev oo-text-abbrev-table "begn" "beginning")
(define-abbrev oo-text-abbrev-table "idnt" "I do not think")
(define-abbrev oo-text-abbrev-table "idt" "I do not think")
(define-abbrev oo-text-abbrev-table "ting" "thing")
(define-abbrev oo-text-abbrev-table "ned" "need")
(define-abbrev oo-text-abbrev-table "dir" "directory")
(define-abbrev oo-text-abbrev-table "ull" "you will")
(define-abbrev oo-text-abbrev-table "spst" "supposed")
(define-abbrev oo-text-abbrev-table "hv" "have")
(define-abbrev oo-text-abbrev-table "desiding" "deciding")
(define-abbrev oo-text-abbrev-table "pkgs" "packages")
(define-abbrev oo-text-abbrev-table "pkg" "package")
(define-abbrev oo-text-abbrev-table "ftmp" "for the most part")
(define-abbrev oo-text-abbrev-table "readme" "README")
(define-abbrev oo-text-abbrev-table "sdnt" "should not")
(define-abbrev oo-text-abbrev-table "cme" "come")
(define-abbrev oo-text-abbrev-table "imed" "immediately")
(define-abbrev oo-text-abbrev-table "cesly" "successfully")
(define-abbrev oo-text-abbrev-table "owoto" "one way or the other")
(define-abbrev oo-text-abbrev-table "configs" "configurations")
(define-abbrev oo-text-abbrev-table "espace" "escape")
(define-abbrev oo-text-abbrev-table "ijwi" "I just want it")
(define-abbrev oo-text-abbrev-table "ijw" "I just want")
(define-abbrev oo-text-abbrev-table "idw" "I do not want")
(define-abbrev oo-text-abbrev-table "ij" "I just")
(define-abbrev oo-text-abbrev-table "unesy" "unnecessarily")
(define-abbrev oo-text-abbrev-table "nes" "necessary")
(define-abbrev oo-text-abbrev-table "bec" "because")
(define-abbrev oo-text-abbrev-table "aswer" "answer")
(define-abbrev oo-text-abbrev-table "dlk" "do not like")
(define-abbrev oo-text-abbrev-table "tho" "though")
(define-abbrev oo-text-abbrev-table "idkw" "I do not know why")
(define-abbrev oo-text-abbrev-table "damw" "do not ask me why")
(define-abbrev oo-text-abbrev-table "idlk" "I do not like")
(define-abbrev oo-text-abbrev-table "ilk" "I like")
(define-abbrev oo-text-abbrev-table "auly" "automatically")
(define-abbrev oo-text-abbrev-table "dsl" "Domain-Specific-Language")
(define-abbrev oo-text-abbrev-table "fn" "function")
(define-abbrev oo-text-abbrev-table "fns" "functions")
(define-abbrev oo-text-abbrev-table "ig" "instagram")
(define-abbrev oo-text-abbrev-table "econf" "Emacs configuration")
(define-abbrev oo-text-abbrev-table "kbdm" "keyboard macro")
(define-abbrev oo-text-abbrev-table "kbdms" "keyboard macros")
(define-abbrev oo-text-abbrev-table "msw" "Microsoft Windows")
(define-abbrev oo-text-abbrev-table "imho" "in my humble opinion")
(define-abbrev oo-text-abbrev-table "imo" "in my opinion")
(define-abbrev oo-text-abbrev-table "fyi" "for your information")
(define-abbrev oo-text-abbrev-table "lmk" "let me know")
(define-abbrev oo-text-abbrev-table "afaik" "as far as I know")
(define-abbrev oo-text-abbrev-table "idk" "I do not know")
(define-abbrev oo-text-abbrev-table "gonna" "going to")
(define-abbrev oo-text-abbrev-table "otc" "on the contrary")
(define-abbrev oo-text-abbrev-table "st" "sometimes")
(define-abbrev oo-text-abbrev-table "tbh" "to be honest")
(define-abbrev oo-text-abbrev-table "qwerty" "QWERTY")
(define-abbrev oo-text-abbrev-table "ngl" "not going to lie")
(define-abbrev oo-text-abbrev-table "tfb" "to be frank")
(define-abbrev oo-text-abbrev-table "ndo" "window")
(define-abbrev oo-text-abbrev-table "tis" "its")
(define-abbrev oo-text-abbrev-table "amly" "automatically")
(define-abbrev oo-text-abbrev-table "rn" "right now")
(define-abbrev oo-text-abbrev-table "bly" "probably")
(define-abbrev oo-text-abbrev-table "lk" "like")
;; I want the word =config= to stay the same too much for this to be useful nil :enable-function oo-enable-text-abbrev-p.
;; Right now it is frankly more of an impediment for me than something that nil :enable-function oo-enable-text-abbrev-pt
;; helps me nil :enable-function oo-enable-text-abbrev-p.
(define-abbrev oo-text-abbrev-table "questioin" "question")
(define-abbrev oo-text-abbrev-table "ur" "your")
(define-abbrev oo-text-abbrev-table "wiht" "with")
(define-abbrev oo-text-abbrev-table "ith" "with")
(define-abbrev oo-text-abbrev-table "abilit" "ability")
(define-abbrev oo-text-abbrev-table "ko" "K.O.")
(define-abbrev oo-text-abbrev-table "dat" "that")
(define-abbrev oo-text-abbrev-table "incc" "increase")
(define-abbrev oo-text-abbrev-table "incs" "increase")
(define-abbrev oo-text-abbrev-table "decs" "deccrease")
;; TODO: Add a condition preventng it from expanding if I am writing a file path nil :enable-function oo-enable-text-abbrev-p.
(define-abbrev oo-text-abbrev-table "econfigg" "Emacs configuration")
(define-abbrev oo-text-abbrev-table "configg" "configuration")
(define-abbrev oo-text-abbrev-table "obvl" "obviously")
(define-abbrev oo-text-abbrev-table "obv" "obvious")
(define-abbrev oo-text-abbrev-table "appr" "appropriate")
(define-abbrev oo-text-abbrev-table "ofc" "of course")
(define-abbrev oo-text-abbrev-table "ok" "O.K.")
(define-abbrev oo-text-abbrev-table "iis" "it is")
(define-abbrev oo-text-abbrev-table "bc" "because")
(define-abbrev oo-text-abbrev-table "iow" "in other words")
(define-abbrev oo-text-abbrev-table "uun" "up until now")
(define-abbrev oo-text-abbrev-table "exwm" "EXWM")
(define-abbrev oo-text-abbrev-table "fe" "for example")
(define-abbrev oo-text-abbrev-table "evaled" "evaluated")
(define-abbrev oo-text-abbrev-table "imma" "I am going to")
;; From https://sachachua.com/blog/2015/01/developing-emacs-micro-habits-text-automation nil :enable-function oo-enable-text-abbrev-p/
(define-abbrev oo-text-abbrev-table "iwt" "I want to")
(define-abbrev oo-text-abbrev-table "hw" "however")
(define-abbrev oo-text-abbrev-table "ths" "this")
(define-abbrev oo-text-abbrev-table "otoh" "on the one hand")
(define-abbrev oo-text-abbrev-table "otth" "on the other hand")
(define-abbrev oo-text-abbrev-table "kinda" "kind of")
(define-abbrev oo-text-abbrev-table "ohter" "other")
(define-abbrev oo-text-abbrev-table "fi" "for instance")
(define-abbrev oo-text-abbrev-table "youve" "you have")
(define-abbrev oo-text-abbrev-table "youd" "you would")
(define-abbrev oo-text-abbrev-table "il" "I will")
(define-abbrev oo-text-abbrev-table "theres" "there is")
(define-abbrev oo-text-abbrev-table "itss" "it is")
(define-abbrev oo-text-abbrev-table "im" "I am")
(define-abbrev oo-text-abbrev-table "illl" "I will")
(define-abbrev oo-text-abbrev-table "cant" "cannot")
(define-abbrev oo-text-abbrev-table "idd" "ID")
(define-abbrev oo-text-abbrev-table "dont" "do not")
(define-abbrev oo-text-abbrev-table "wontt" "will not")
(define-abbrev oo-text-abbrev-table "doesnt" "does not")
;; Not sure I actually want this abbrev because =wont= is actually a word nil :enable-function oo-enable-text-abbrev-p.
(define-abbrev oo-text-abbrev-table "ine" "one")
(define-abbrev oo-text-abbrev-table "mispelling" "misspelling")
(define-abbrev oo-text-abbrev-table "ry" "very")
(define-abbrev oo-text-abbrev-table "wont" "will not")
(define-abbrev oo-text-abbrev-table "thats" "that is")
(define-abbrev oo-text-abbrev-table "u" "you")
(define-abbrev oo-text-abbrev-table "ul" "you will")
(define-abbrev oo-text-abbrev-table "dnt" "don't")
(define-abbrev oo-text-abbrev-table "wo" "without")
(define-abbrev oo-text-abbrev-table "ive" "I have")
(define-abbrev oo-text-abbrev-table "ik" "I know")
(define-abbrev oo-text-abbrev-table "plx" "complex")
(define-abbrev oo-text-abbrev-table "ribe" "describe")
(define-abbrev oo-text-abbrev-table "iff" "if and only if")
(define-abbrev oo-text-abbrev-table "addd" "additionally")
(define-abbrev oo-text-abbrev-table "weve" "we have")
(define-abbrev oo-text-abbrev-table "whats" "what is")
(define-abbrev oo-text-abbrev-table "havent" "have not")
(define-abbrev oo-text-abbrev-table "didnt" "did not")
(define-abbrev oo-text-abbrev-table "shouldnt" "should not")
(define-abbrev oo-text-abbrev-table "isnt" "is not")
(define-abbrev oo-text-abbrev-table "fo" "of")
(define-abbrev oo-text-abbrev-table "ud" "you would")
(define-abbrev oo-text-abbrev-table "fwis" "from what I see")
(define-abbrev oo-text-abbrev-table "fwiu" "from what I understand")
(define-abbrev oo-text-abbrev-table "youre" "you are")
(define-abbrev oo-text-abbrev-table "wouldnt" "would not")
(define-abbrev oo-text-abbrev-table "woudnt" "would not")
(define-abbrev oo-text-abbrev-table "coudnt" "could not")
(define-abbrev oo-text-abbrev-table "couldnt" "could not")
;; These abbrevs are focused on spelling mistakes.
;; Here I focus on fixing unambiguous spelling mistakes.
(define-abbrev oo-text-abbrev-table "onw" "own")
(define-abbrev oo-text-abbrev-table "frst" "first")
(define-abbrev oo-text-abbrev-table "edting" "editing")
(define-abbrev oo-text-abbrev-table "alread" "already")
(define-abbrev oo-text-abbrev-table "htats" "that is")
(define-abbrev oo-text-abbrev-table "whehther" "whether")
(define-abbrev oo-text-abbrev-table "somehting" "something")
(define-abbrev oo-text-abbrev-table "hte" "the")
(define-abbrev oo-text-abbrev-table "te" "the")
(define-abbrev oo-text-abbrev-table "th" "to have")
(define-abbrev oo-text-abbrev-table "ot" "to")
(define-abbrev oo-text-abbrev-table "wnat" "want")
(define-abbrev oo-text-abbrev-table "stoped" "stopped")
(define-abbrev oo-text-abbrev-table "capfs" "completion-at-point-functions")
(define-abbrev oo-text-abbrev-table "suprise" "surprise")
(define-abbrev oo-text-abbrev-table "functoin" "function")
(define-abbrev oo-text-abbrev-table "refect" "reflect")
(define-abbrev oo-text-abbrev-table "dint" "did not")
(define-abbrev oo-text-abbrev-table "orignal" "original")
(define-abbrev oo-text-abbrev-table "eachother" "each other")
(define-abbrev oo-text-abbrev-table "dn" "do not")
;;; provide
(provide '911-text-abbrevs)
;;; 911-text-abbrevs.el ends here
