;;; 990-config-abbrev.el --- abbrev configuration -*- lexical-binding: t; -*-
;;
;; Copyright (c) 2024 Free Software Foundation, Inc.
;;
;; Author: Luis Henriquez-Perez <luis@luishp.xyz>
;; Homepage: https://github.com/Luis-Henriquez-Perez/dotfiles/
;;
;; This file is not part of GNU Emacs.
;;
;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License as
;; published by the Free Software Foundation, either version 3 of the
;; License, or (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful, but
;; WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
;; General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program. If not, see <http://www.gnu.org/licenses/>.
;;
;;; Commentary:
;;
;; This is my configuration for abbrev.
;;
;;; Code:
;;;; requirements
(require '050-base)
(require 'abbrev)
;;;; prevent greedy expansion with `backward-word'
(abbrev-table-put global-abbrev-table :regexp "\\<\\(\\sw+\\)\\Sw*")
;;;; automatically add period
;; I do not like manually adding periods to the end of sentences.  Having moved
;; from using one space after a sentence to two, I find it particularl daunting
;; to type period, space, space whenever I am ending one sentence and starting a
;; new one.  With this customization when I type space, space, following a word
;; it is converted into period space space.  Additionally, if I end a sentence
;; line with two spaces and I press ESC, the trailing two spaces are replaced
;; with a period.
(defun! oo--add-period-maybe (expand-fn)
  "Add a period when necessary."
  (prog1 (funcall expand-fn)
    (when (or (derived-mode-p 'text-mode) (oo-in-string-or-comment-p))
      (set! eol (line-beginning-position -1))
      (set! rx "\\([^\n!.?[:blank:]]\\)\\([[:blank:]][[:blank:]]\\)\\([^[:blank:]]+\\)")
      (cond ((looking-back rx eol)
             (replace-match "\\1.\\2\\3" nil nil nil 0))
            ((looking-back "\\([^!.?[:blank:]]\\)[[:blank:]]\\{2,\\}" eol)
             (replace-match "\\1."))))))
;;;; pulse expansion
;; You would be surprised at how much of an aesthetic improvement little things
;; like this can make a difference.
(defun! oo--pulse-expansion (expand-fn)
  "Pulse around the expansion of an abbrev."
  (aprog1! (funcall expand-fn)
    (and it
         last-abbrev-location
         (require 'pulse nil t)
         (pulse-momentary-highlight-region last-abbrev-location (point)))))
;;;; ensure `post-self-insert-hook' is run after each word
;; Captain fails to capitalize the beginning of a sentence if the beginning of a
;; sentence was generated by the expansion of an abbrev because Captain
;; captializes a word during `post-insert-hook' and a multi-word expansion will
;; skip calling that hook after each word except the last one.  So here I call
;; the hook myself at the proper places.
(defun! oo--ensure-self-insert (expand-fn)
  "Run `post-insert-hook' after each word in a multi-word expansion."
  (aprog1! (funcall expand-fn)
    (when (and it last-abbrev-location)
      (set! end (point))
      (save-excursion (goto-char last-abbrev-location)
                      (while (re-search-forward ".+?[[:blank:]]" end t nil)
                        (run-hooks 'post-self-insert-hook))))))

;;;; predicates
(defun! oo-use-text-abbrev-p ()
  "Return non-nil when text abbrevs should be enabled.
This is when the current major-mode is derived from text-mode or point is in a
string or comment."
  (or (derived-mode-p 'text-mode)
	  ;; These cases prevent abbreviation from expanding words outside of a
	  ;; string or comment when in some programming mode.
	  (cl-case (oo-in-string-or-comment-p)
		(string
		 (set! string-beg (car (bounds-of-thing-at-point 'string)))
		 (set! word-beg (save-excursion (backward-word) (point)))
		 (> word-beg string-beg))
		(comment
		 (set! comment-beg (save-excursion (comment-beginning) (point)))
		 (set! word-beg (save-excursion (backward-word) (point)))
         ;; The first word of a comment actually starts at `comment-beg' but
         ;; this never happens for a string.
         (>= word-beg comment-beg)))))

(defun oo-in-org-mode-p ()
  "Return non-nil if the current buffer is in org-mode."
  (declare (pure t) (side-effect-free error-free))
  (derived-mode-p 'org-mode))

(defun oo-in-elisp-mode-p ()
  "Return non-nil if current buffer is in emacs-lisp mode."
  (declare (pure t) (side-effect-free error-free))
  (derived-mode-p 'emacs-lisp-mode))

(defun oo-in-elisp-code-p ()
  "Return non-nil if current buffer is elisp code."
  (declare (pure t) (side-effect-free error-free))
  (and (derived-mode-p 'emacs-lisp-mode)
       (not (oo-in-string-or-comment-p))))

(defun oo-in-elisp-comment-p ()
  "Return non-nil if currently in an emacs-lisp comment."
  (declare (pure t) (side-effect-free error-free))
  (and (derived-mode-p 'emacs-lisp-mode)
       (oo-in-string-or-comment-p)))

(defun oo-in-blog-post-p ()
  "Return non-nil if the current buffer is for one of my blog posts."
  (declare (pure t) (side-effect-free error-free))
  (and (derived-mode-p 'org-mode)
       (stringp default-directory)
       (string= (expand-file-name default-directory)
                (expand-file-name "~/Documents/MyBlog/org/posts/"))))

;;;; expansion functions
(defun! oo-expand-org-package-link ()
  "Prompt for package and insert the corresponding org package link."
  (set! desc (package--query-desc))
  (set! link (cdr (assoc :url (and desc (package-desc-extras desc)))))
  (insert (format "[[%s][%s]]" link (package-desc-name desc))))

(defun! oo-expand-package-link ()
  "Prompt for package and insert the corresponding package link."
  (set! desc (package--query-desc))
  (set! link (cdr (assoc :url (and desc (package-desc-extras desc)))))
  (insert link))

(defun oo-expand-elisp-defun ()
  "Insert elisp defun template."
  (tempel-insert 'fn))

(put 'oo-expand-elisp-defun 'no-self-insert t)

(defun oo-expand-elisp-var ()
  "Insert elisp defun template."
  (tempel-insert 'vr))

(defun! oo-expand-callable-doc-link ()
  "Insert an org link to a helpful callable snapshot.
Find the appropriate documentation for the callable in the documentation
directory.  If it does not exist create it and add it."
  (set! doc-dir (expand-file-name "~/Documents/MyBlog/org/documentation/"))
  (set! helpful-switch-buffer-function #'ignore)
  (set! symbol (helpful--read-symbol "Callable: " (helpful--callable-at-point) #'fboundp))
  (set! html-file (expand-file-name (format "%s-helpful-callable--%s.html" emacs-version symbol) doc-dir))
  (unless (file-exists-p html-file)
    (and (set! help-buffer (helpful-callable symbol))
         (set! html-buffer (htmlize-buffer help-buffer))
         (progn (with-current-buffer html-buffer
                  (write-region (point-min) (point-max) html-file nil 'quiet))
                (kill-buffer help-buffer)
                (kill-buffer html-buffer))))
  (insert (format "[[file:%s][%s]]"  html-file symbol)))

(defun! oo-expand-variable-doc-link ()
  "Insert an org link to a helpful callable snapshot.
Find the appropriate documentation for the callable in the documentation
directory.  If it does not exist create it and add it."
  (set! doc-dir (expand-file-name "~/Documents/MyBlog/org/documentation/"))
  (set! helpful-switch-buffer-function #'ignore)
  (set! symbol (helpful--read-symbol "Variable: " (helpful--variable-at-point) #'helpful--variable-p))
  (set! html-file (expand-file-name (format "%s-helpful--%s.html" emacs-version symbol) doc-dir))
  (unless (file-exists-p html-file)
    (and (set! help-buffer (helpful-variable symbol))
         (set! html-buffer (htmlize-buffer help-buffer))
         (progn (with-current-buffer html-buffer
                  (write-region (point-min) (point-max) html-file nil 'quiet))
                (kill-buffer help-buffer)
                (kill-buffer html-buffer))))
  (insert (format "[[file:%s][%s]]"  html-file symbol)))

(defun! oo-expand-config-link ()
  "Expand an org link for a configuration file."
  (setq doc-dir (expand-file-name "~/Documents/MyBlog/org/documentation/"))
  (set! lisp-dir (expand-file-name "lisp" user-emacs-directory))
  (appending! files (directory-files lisp-dir t (rx ".el" eol)))
  (pushing! files (expand-file-name user-init-file))
  (pushing! files (expand-file-name "early-init.el" user-emacs-directory))
  ;; Save a snapshot of my configuration file.
  (set! config-file (completing-read "" files))
  (set! html-file (expand-file-name (file-name-nondirectory file) doc-dir))
  (set! config-buffer (create-file-buffer config-file))
  (set! html-buffer (htmlize-buffer config-buffer))
  (unless (file-exists-p html-file)
    (with-current-buffer html-buffer
      (write-region (point-min) (point-max) html-file nil 'quiet)))
  (kill-buffer html-buffer)
  ;; TODO: make the file path relative.
  (insert (format "[[file:%s][%s]]" html-file (file-name-nondirectory path))))
;;; provide
(provide '990-config-abbrev)
;;; 990-config-abbrev.el ends here
