;;; 990-config-abbrev.el --- abbrev configuration -*- lexical-binding: t; -*-
;;
;; Copyright (c) 2024 Free Software Foundation, Inc.
;;
;; Author: Luis Henriquez-Perez <luis@luishp.xyz>
;; Homepage: https://github.com/Luis-Henriquez-Perez/dotfiles/
;;
;; This file is not part of GNU Emacs.
;;
;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License as
;; published by the Free Software Foundation, either version 3 of the
;; License, or (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful, but
;; WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
;; General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program. If not, see <http://www.gnu.org/licenses/>.
;;
;;; Commentary:
;;
;; This is my configuration for abbrev.
;;
;;; Code:
;;;; requirements
(require '050-base)
(require 'abbrev)
(message "Loaded config-abbrev...")
;;;; prevent greedy expansion with `backward-word'
(abbrev-table-put global-abbrev-table :regexp "\\<\\(\\sw+\\)\\Sw*")
;;;; make the parents
(abbrev-table-put text-mode-abbrev-table :enable-function  #'oo-in-text-p)
(abbrev-table-put global-abbrev-table :parents (list text-mode-abbrev-table emacs-lisp-mode-abbrev-table))
;;;; load abbrevs
;; This is a bit crude.  Iwdb precise to not load the elisp abbrev table when
;; enabling abbrev mode in a text-mode but it is not significant because it
;; Emacs loads abbrevs so fast.
(defun oo-load-abbrevs-h ()
  "Load abbrev files.
This function is designed to be added to `abbrev-mode-hook'.  It loads all my
abbrevs and removes itself from the hook."
  (require '910-text-mode-abbrev-table)
  (require '910-emacs-lisp-mode-abbrev-table)
  (remove-hook 'abbrev-mode-hook #'oo-load-abbrevs-h))
;;;; automatically add period
;; I do not like manually adding periods to the end of sentences.  Having moved
;; from using one space after a sentence to two, I find it particularl daunting
;; to type period, space, space whenever I am ending one sentence and starting a
;; new one.  With this customization when I type space, space, following a word
;; it is converted into period space space.  Additionally, if I end a sentence
;; line with two spaces and I press ESC, the trailing two spaces are replaced
;; with a period.
(defun! oo-add-period-maybe-a (expand-fn)
  "Add a period when necessary."
  (prog1 (funcall expand-fn)
    (when (or (member major-mode '(org-mode text-mode)) (oo-in-string-or-comment-p))
      (set! eol (line-beginning-position -1))
      (set! rx "\\([^\n!.?[:blank:]]\\)\\([[:blank:]][[:blank:]]\\)\\([^[:blank:]]+\\)")
      (cond ((looking-back rx eol)
             (replace-match "\\1.\\2\\3" nil nil nil 0))
            ((looking-back "\\([^!.?[:blank:]]\\)[[:blank:]]\\{2,\\}" eol)
             (replace-match "\\1."))))))
;;;; pulse expansion
;; You would be surprised at how much of an aesthetic improvement little things
;; like this can make a difference.
(defun! oo-do-pulse-expansion-a (expand-fn)
  "Pulse around the expansion of an abbrev."
  (aprog1! (funcall expand-fn)
    (and it
         last-abbrev-location
         (require 'pulse nil t)
         (pulse-momentary-highlight-region last-abbrev-location (point)))))
;;;; ensure `post-self-insert-hook' is run after each word
;; Captain fails to capitalize the beginning of a sentence if the beginning of a
;; sentence was generated by the expansion of an abbrev because Captain
;; captializes a word during `post-insert-hook' and a multi-word expansion will
;; skip calling that hook after each word except the last one.  So here I call
;; the hook myself at the proper places.
(defun! oo-ensure-self-insert-a (expand-fn)
  "Run `post-insert-hook' after each word in a multi-word expansion."
  (aprog1! (funcall expand-fn)
    (when (and it last-abbrev-location)
      (set! end (point))
      (save-excursion (goto-char last-abbrev-location)
                      (while (re-search-forward ".+?[[:blank:]]" end t nil)
                        (run-hooks 'post-self-insert-hook))))))
;;;; predicates
(defun! oo-in-text-p ()
  "Return non-nil when text-mode abbrevs should be enabled.
This is when the current major-mode is derived from text-mode or point is in a
string or comment."
  (or (member major-mode '(org-mode text-mode vc-git-log-edit-mode))
	  ;; These cases prevent abbreviation from expanding words outside of a
	  ;; string or comment when in some programming mode.
	  (cl-case (oo-in-string-or-comment-p)
		(string
		 (set! string-beg (car (bounds-of-thing-at-point 'string)))
		 (set! word-beg (save-excursion (backward-word) (point)))
		 (> word-beg string-beg))
		(comment
		 (set! comment-beg (save-excursion (comment-beginning) (point)))
		 (set! word-beg (save-excursion (backward-word) (point)))
         ;; The first word of a comment actually starts at `comment-beg' but
         ;; this never happens for a string.
         (>= word-beg comment-beg)))))

(defun oo-in-org-mode-p ()
  "Return non-nil if the current buffer is in org-mode."
  (declare (pure t) (side-effect-free error-free))
  (derived-mode-p 'org-mode))

(defun oo-enable-elisp-abbrev-p ()
  "Return non-nil if current buffer is in emacs-lisp mode."
  (declare (pure t) (side-effect-free error-free))
  (derived-mode-p 'emacs-lisp-mode))

(defun oo-in-elisp-code-p ()
  "Return non-nil if current buffer is elisp code."
  (declare (pure t) (side-effect-free error-free))
  (and (derived-mode-p 'emacs-lisp-mode)
       (not (oo-in-string-or-comment-p))
       ;; This is to avoid cases where we have an abbrev in a preceding string.
       ;; I do not want that to be expanded.
       (word-at-point)))

(defun oo-in-elisp-comment-p ()
  "Return non-nil if currently in an emacs-lisp comment."
  (declare (pure t) (side-effect-free error-free))
  (and (derived-mode-p 'emacs-lisp-mode)
       (oo-in-string-or-comment-p)))

(defun oo-in-blog-post-p ()
  "Return non-nil if the current buffer is for one of my blog posts."
  (declare (pure t) (side-effect-free error-free))
  (and (derived-mode-p 'org-mode)
       (stringp default-directory)
       (string= (expand-file-name default-directory)
                (expand-file-name "~/Documents/MyBlog/org/posts/"))))
;;;; expansion functions
;; (defvar oo-blog-dir "~/Documents/MyBlog/org/documentation/")

(defun! oo-expand-blog-buffer ()
  "Insert link of buffer.
Meant to be used in a blog buffer."
  (set! doc-dir (expand-file-name "~/Documents/MyBlog/org/documentation/"))
  (set! buffer (completing-read "Buffer: " (buffer-list)))
  (quitif! (not buffer))
  (set! html-file (expand-file-name (format "%s--%s.html" emacs-version (buffer-name)) doc-dir))
  (with-current-buffer (htmlize-buffer buffer)
    (quiet! (write-region (point-min) (point-max) html-file))
    (kill-buffer)))

(defun! oo-expand-org-package-link ()
  "Prompt for package and insert the corresponding org package link."
  (set! desc (package--query-desc))
  (set! link (cdr (assoc :url (and desc (package-desc-extras desc)))))
  (insert (format "[[%s][%s]]" link (package-desc-name desc))))

(defun! oo-expand-package-link ()
  "Prompt for package and insert the corresponding package link."
  (set! link (intern (completing-read
                      "Install package: "
                      (mapcan
                       (lambda (elt)
                         (and (or (and (or current-prefix-arg
                                           package-install-upgrade-built-in)
                                       (package--active-built-in-p (car elt)))
                                  (not (package-installed-p (car elt))))
                              (list (symbol-name (car elt)))))
                       package-archive-contents)
                      nil t)))
  ;; (set! desc (package--query-desc))
  ;; (set! link (cdr (assoc :url (and desc (package-desc-extras desc)))))
  link)

(defvar helpful-switch-buffer-function)

(declare-function helpful--callable-at-point "helpful")
(declare-function helpful-callable "helpful")
(defun! oo-expand-callable-doc-link ()
  "Insert an org link to a helpful callable snapshot.
Find the appropriate documentation for the callable in the documentation
directory.  If it does not exist create it and add it."
  (set! doc-dir (expand-file-name "~/Documents/MyBlog/org/documentation/"))
  (set! helpful-switch-buffer-function #'identity)
  (set! symbol (helpful--read-symbol "Callable: " (helpful--callable-at-point) #'fboundp))
  (set! html-file (expand-file-name (format "%s-helpful-callable--%s.html" emacs-version symbol) doc-dir))
  (unless (file-exists-p html-file)
    (set! help-buffer (quiet! (helpful-callable symbol)))
    (quitif! (not help-buffer) "No help buffer.")
    (set! html-buffer (quiet! (htmlize-buffer help-buffer)))
    (quitif! (not html-buffer) "No html buffer.")
    (with-current-buffer html-buffer
      (quiet! (write-region (point-min) (point-max) html-file))
      (kill-buffer help-buffer)
      (kill-buffer)))
  (insert (format "[[file:%s][%s]]"  html-file symbol)))

(declare-function htmlize-buffer "htmlize")

(declare-function helpful--read-symbol "helpful")
(declare-function helpful--variable-at-point "helpful")
(declare-function helpful-variable "helpful")
(defun! oo-expand-variable-doc-link ()
  "Insert an org link to a helpful callable snapshot.
Find the appropriate documentation for the callable in the documentation
directory.  If it does not exist create it and add it."
  (set! doc-dir (expand-file-name "~/Documents/MyBlog/org/documentation/"))
  (set! helpful-switch-buffer-function #'identity)
  (unwind-protect (set! symbol (helpful--read-symbol "Variable: " (helpful--variable-at-point) #'helpful--variable-p))
    (or symbol (unexpand-abbrev))
    (goto-char last-abbrev-location))
  (set! html-file (expand-file-name (format "%s-helpful-variable--%s.html" emacs-version symbol) doc-dir))
  (unless (file-exists-p html-file)
    (set! help-buffer (helpful-variable symbol))
    (quitif! (not help-buffer) "No help buffer.")
    (set! html-buffer (htmlize-buffer help-buffer))
    (quitif! (not html-buffer) "No html buffer.")
    (with-current-buffer html-buffer
      (write-region (point-min) (point-max) html-file)
      (kill-buffer help-buffer)
      (kill-buffer)))
  (insert (format "[[file:%s][%s]]"  html-file symbol)))

(defun! oo-expand-config-link ()
  "Expand an org link for a configuration file."
  (set! doc-dir (expand-file-name "~/Documents/MyBlog/org/documentation/"))
  (set! lisp-dir (expand-file-name "lisp" user-emacs-directory))
  (appending! files (directory-files lisp-dir t (rx ".el" eol)))
  (pushing! files (expand-file-name user-init-file))
  (pushing! files (expand-file-name "early-init.el" user-emacs-directory))
  (set! config-file (completing-read "Config file: " files))
  (set! name-ext (file-name-nondirectory config-file))
  (set! name (file-name-sans-extension name-ext))
  (set! html-file (expand-file-name (format "%s-%s.html" emacs-version name) doc-dir))
  (unless (file-exists-p html-file)
    (with-temp-buffer
      (insert-file-contents config-file)
      (set! html-buffer (htmlize-region (point-min) (point-max)))
      (with-current-buffer html-buffer
        (write-region (point-min) (point-max) html-file nil 'quiet)
        (kill-buffer))))
  (set! relative-path (file-relative-name html-file (file-name-directory (buffer-file-name))))
  (insert (format "[[%s][%s]]" relative-path name-ext)))
;;;; updating abbrevs
(defun oo-write-abbrev-file-a (&rest _)
  "Override `write-abbrev-file' with my own function."
  (quiet! (oo-update-abbrev-tables))
  (oo-log 'trace "Updating abbrevs."))

;; I only want this function to add complex abbrevs. abbrev
(defun oo-add-abbrev (arg)
  "Add the abbrev I mean."
  (interactive "P")
  (add-abbrev text-mode-abbrev-table "text-mode" arg))

(defun oo-inverse-add-abbrev (arg)
  "Add the abbrev I mean."
  (interactive "P")
  (inverse-add-abbrev text-mode-abbrev-table "text-mode" (or arg 1)))

(defun! oo-update-abbrev-tables ()
  "Update abbrev tables and commit changes."
  (dolist (table abbrev-table-name-list)
    (set! file (expand-file-name (format "910-%s.el" table) oo-lisp-dir))
    (when (and (abbrev--table-symbols table) (file-exists-p file))
      (set! buffer (or (get-file-buffer file) (find-file-noselect file nil t)))
      ;; TODO: handle better opening an existing buffer.
      (unwind-protect
          (with-current-buffer buffer
            (goto-char (point-min))
            (when (re-search-forward "^(define-abbrev-table" nil)
              (goto-char (match-beginning 0))
              (set! beg (point))
              (forward-sexp)
              (delete-region beg (point))
              (goto-char beg)
              (insert (oo-abbrev-table-string table)))
            (save-buffer)
            (when (equal 'edited (vc-state file))
              (set! backend (car (vc-deduce-fileset nil t 'state-model-only-files)))
              (set! commit-msg (format "Add abbrevs to the %s..." (string-remove-prefix "910-" (file-name-base file))))
              (message "update table: %S %S %S %S %S" file (vc-state file) (vc-root-dir) backend commit-msg)
              ;; TODO: inhibit opening buffers.
              (vc-git-checkin (list file) commit-msg)))
        (kill-buffer buffer)))))

(defun! oo-abbrev-table-string (table)
  "Print TABLE as `define-abbrev-table' with aligned abbrevs and no :count."
  (set! abbrevs '())
  (set! name (symbol-name table))
  (flet! insert-at-column (column string)
    "Insert STRING at COLUMN, padding with spaces if necessary."
    (let ((pad (- column (current-column))))
      (when (> pad 0)
        (insert (make-string pad ?\s)))
      (insert string)))
  (mapatoms
   (lambda (sym)
     (let* ((name (symbol-name sym))
            (expansion (symbol-value sym))
            (hook (symbol-function sym))
            (plist (symbol-plist sym))
            ;; I checked the properties and the only ones that I will
            ;; realistically use are these two.
            (case-fixed (plist-get plist :case-fixed))
            (enable-function (plist-get plist :enable-function))
            (entry (list name expansion)))
       ;; There's one entry whose name is the entry string.  Looks like ("" nil
       ;; nil).  No point in having that in the table (it is probrably always
       ;; implicitly there though).
       (unless (string-empty-p name)
         (and hook (setq entry (append entry (list hook))))
         (and enable-function (setq entry (append entry (list :enable-function enable-function))))
         (and case-fixed (setq entry (append entry (list :case-fixed case-fixed))))
         (push entry abbrevs))))
   (symbol-value table))
  (setq abbrevs (sort abbrevs (-on #'string< #'car)))
  (with-temp-buffer
    (erase-buffer)
    (insert (format "(define-abbrev-table '%s\n  '(" name))
    (set! column (current-column))
    (dolist (abbrev abbrevs)
      (set! (name expansion hook . plist) abbrev)
      (insert-at-column column (format "%S\n" abbrev)))
    ;; This is the last newline.
    (delete-char -1)
    (insert-at-column (current-column) "))")
    (buffer-string)))
;;; provide
(provide '990-config-abbrev)
;;; 990-config-abbrev.el ends here
